### ISSUE TITLE
Provide A-SHOP Non-Fishing Day Reasons

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#1007]
FYI:  @melinashak-noaa

**Comment by VanessaTuttle-NOAA** [comment]
(1) Steaming to/from grounds
(2) Weather
(3) Looking for fish
(4) Mechanical breakdown
(5) Cleaning factory
(6) Other (notes)

**Comment by toddhay-NOAA** [comment]
Thanks!

**Comment by BHHorness-NOAA** [comment]
list provided

**Comment by melinashak-noaa** [comment]
added this to the couch config
