### ISSUE TITLE
11/13/2019 Mockups Review Feedback

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#1024]
- [x] All Tables - Enable Column Resizing
- [x] QA/QC Tab - Add Handle to drag up/down to increase/decrease the Errors v. Data tables
- [x] QA/QC Tab - Errors Table - Possible Status types include Unresolved, Resolved, Override
- [x] QA/QC Tab - Errors Table - Error Levels include Warning, Error, Data Processing
- [x] QA/QC Tab - General Error Table Columns available on all of the Tabs
      -- Level
      -- Status
      -- Description
      -- Note
- [x] QA/QC Tab - Columns per Trips/Hauls/etc. Tabs - review the data models to define those
- [x] Trips tab-specific column should be defined by the Trips model (WCGOP or A-SHOP)
- [x] QA/QC Tab - Error Table - Status Filtering using toggle buttons of:  Unresolved, Resolved, Override
- [x] QA/QC Tab - Data Tables - Shrink the size of the Trip, Haul, Catch, Specimen columns
- [x] QA/QC Tab - All Data Tables - Enable Inline Column Editing
- [ ] In Season

**Comment by melinashak-noaa** [comment]
https://github.com/nwfsc-fram/boatnet/issues/939
