### ISSUE TITLE
Review and Identify Appropriate Trip Hierachy Columns for QA/QC Data Tables

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#1026]
For the different trip data tables (Trips, Hauls, Catch, etc.), we need to identify the appropriate columns that will be used.  These will likely very across the different A-SHOP and WCGOP (and survey for that matter) programs, so this should be fed into the component as part of the config file.  We should review the data models for A-SHOP and WCGOP to help determine what to display for the data tables

**Comment by melinashak-noaa** [comment]
wcgop columns: https://drive.google.com/file/d/1PxR-CSfwnhYcJKlghOASLTixx3z0EN97/view
