### ISSUE TITLE
Build is broken - webpack/ node-fibers building issue?

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1028]
Just started getting an error when I run lerna bootstrap. Will is also getting this error as well when running the latest version of the code from master. Looks like webpack pulled in a broken package of fibers. We're investigating to get lerna bootstrap working again. 
![image](https://user-images.githubusercontent.com/44685558/68906794-61c34800-06fa-11ea-9e87-e00fad4b8d4b.png)

**Comment by wsmith-nwfsc** [comment]
I get this error as well (my system tries to build node-fibers but fails with a bunch of C++ errors.)

I don't see any bugs filed against node-fibers at the moment, but there may be a flood soon.

We may just have to wait this out, but shall poke around to see what package got upgraded and broke everything.

**Comment by wsmith-nwfsc** [comment]
Kicking off a Jenkins build to see if we get this there.

**Comment by wsmith-nwfsc** [comment]
Weirdness appears to be related to fibers 3.x not being compatible with Node 12. No idea why we didn't see this before, but I believe I've fixed this by bumping fibers version to 4.
#1029
