### ISSUE TITLE
Access CouchDB with SQL and Visualize with Zeppelin/Spark

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1039]
Develop method for accessing couch data with SQL-like interface.  Explore interacting with Apache Spark and Zeppelin.

**Comment by wsmith-nwfsc** [comment]
I've forked a dumping tool that I used for querying our dataset from flat files, will elaborate more during meeting

https://github.com/wsmith-nwfsc/couchdb-dump

**Comment by wsmith-nwfsc** [comment]
I have this working with Spark now, will fill you in on the details. Drill performance seems better so far, but still messing with Spark settings (plus it's talking to CouchDB with no data dumping needed.)

**Comment by jimfellows-NOAA** [comment]
satisfied with the progress here, closing out
