### ISSUE TITLE
Integrate virtual keyboard into boatnet

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#105]

**Comment by wsmith-nwfsc** [comment]
This repo has been forked as ngx7-material-keyboard which integrates fixes and updates to angular 7:
https://github.com/ngx-material-keyboard/core/issues/50 so we'll try that.

**Comment by wsmith-nwfsc** [comment]
Initial attempts to use https://github.com/martywallace/vue-keyboard didn't quite work, but worth revisiting.
Various alternatives abound, e.g. https://github.com/icebob/vue-touch-keyboard

**Comment by melinashak-noaa** [comment]
there's also this, but doesn't look like it has a close button https://virtual-keyboard.js.org/vuejs/

**Comment by wsmith-nwfsc** [comment]
> there's also this, but doesn't look like it has a close button https://virtual-keyboard.js.org/vuejs/

Looks really cool. https://franciscohodge.com/project-pages/simple-keyboard/demo/#emoji

**Comment by ericbrasseur-NOAA** [comment]
Oh we need a fish emoji keyboard so observers can make easy comments like sick fish!

**Comment by melinashak-noaa** [comment]
created a pull request for this https://github.com/nwfsc-fram/boatnet/pull/310

**Comment by SaOgaz-NOAA** [comment]
Hey @melinashak-noaa, can we close this ticket?

**Comment by melinashak-noaa** [comment]
yep closing
