### ISSUE TITLE
refactor to use all_doc_types view with reduce instead of a zillion lookup views

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1063]

**Comment by wsmith-nwfsc** [comment]
A couple notes:
* We don't need to use reduce for this. Reduce is useful for summation and math across the dataset, but not needed for lookups views:
  * To get a list of all doc types, just use all_doc_types?group=true
  * To get a certain set of lookups, just use startkey and endkey, e.g.
all_doc_types?startkey="beaufort"&endkey="beaufort0"

I set the Reduce on obs-web/all_doc_types to NONE, so it's rebuilding at the moment, but I think the queries above are valid.
https://docs.couchdb.org/en/stable/ddocs/views/intro.html
https://docs.couchdb.org/en/stable/ddocs/views/collation.html

**Comment by wsmith-nwfsc** [comment]
Oops, I was wrong about group=true working without a reduce. Updating my comment above
