### ISSUE TITLE
Implement OLE data model/couch doc

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1081]
This ticket involves:
- [x] making some sample declaration couch docs
- [x] adding the model to the  bn-models lib
- [ ] have the app pull and write to one of the sample declarations.

**Comment by wsmith-nwfsc** [comment]
Relates to #972

**Comment by SaOgaz-NOAA** [comment]
Never been this satisfied to see poorly formatted data :). Now I just have to test a write.

![image](https://user-images.githubusercontent.com/54552385/70554554-29186200-1b32-11ea-8ed5-750926a34660.png)

**Comment by SaOgaz-NOAA** [comment]
Okay, got a super simplified and pretty much useless test function that is updating couch successfully! I'll take it for now.  Gonna open a new ticket for next sprint to really start working on the integration of the data models into the code base.
