### ISSUE TITLE
OTS Trip creation / editing tracking

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1084]
Is there a way for staff / admin to track when a trip was created and when edits were made?

**Comment by sethgerou-noaa** [comment]
Been thinking about this one - It can be tricky to view a history of the updates to a Couch document.  In speaking with Will, I believe we've come up with a pretty nice way of capturing/showing a document's history.  More to come.

**Comment by sethgerou-noaa** [comment]
done
