### ISSUE TITLE
OTS Add "No observer required" to selected trips 

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1085]
If a vessel has the good fortune of not being selected for their initial two trips they could become uncertain if the trip is selected or not because un-selected trip are not labelled as such. Including some language to give them confidence that no observer is required and they are using the system correctly will reduce calls to coordinators.

**Comment by sethgerou-noaa** [comment]
Makes sense - will add this functionality.
