### ISSUE TITLE
OTS Show short notice warning when moving trip start date

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1086]
If a trip is created outside the 48 hour window no short notice would be shown. If a fishermen however then edits the start date to within 48 hours they should see the warning. 

Example: skipper knows he must give 48 hours notice so he creates a trip starting in 3 days. After the trip is created he edits the trip to start in 1 day. He should see a warning after making that edit.

**Comment by sethgerou-noaa** [comment]
Makes sense - will add this functionality.

**Comment by sethgerou-noaa** [comment]
let's review this together when we meet - this functionality is implemented (the warning displays any time a date within 48 hours of now is selected), but sounds like you're not seeing the warning when you expect to.

**Comment by sethgerou-noaa** [comment]
48 hour notice stops showing up - check for condition that makes the boolean wrong
