### ISSUE TITLE
OTS not allowing creation of 2nd trip

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1087]
I was playing around with FV Timmy Boy creating, editing and closing trips. I had no issues creating, cancelling, editing trips until after I had played around with the system for a while. 

The initial trip was Nov 26-28 so I should have been able to create a trip starting on the 28th or later. Not sure how I broke things.

**Comment by sethgerou-noaa** [comment]
@scottleach-NOAA Thanks Scott.  Would you please explain a bit more?  Are you saying the "New Trip" button is greyed out with only one active trip?  Or are you saying during trip creation dates are not available that you think should be based on the dates of the existing trip?

**Comment by scottleach-NOAA** [comment]
I can click on the new trip button and the new trip page opens. However All the dates on the calendar are grayed out. I advanced the calendar into 2021 and the dates remain grayed out.

**Comment by sethgerou-noaa** [comment]
Ah, OK.  Sounds like a bug - though this is also the sort of tricky situation we run into when we try to make sure one trip remains ahead of another.  eg, create trip 1, create trip 2, cancel trip 1, create trip with start date after end of trip 2.  Will investigate and let you know what I come up with.
