### ISSUE TITLE
Fix extra decimals bug during ETL

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#1088]
Due to how Javascript handles numbers, some numbers are having decimal places randomly added. Example: 2.3 turns into 2.3000000000000003

**Comment by NickShafferNOAA** [comment]
I think the npm module decimal.js might be a solution to this. It has 275k weekly downloads and good documentation. Need to test, and if it works need to refactor to use it anywhere we have floating point data.

**Comment by wsmith-nwfsc** [comment]
I think this is OK, it's how IEEE 754 floating point values are stored in most languages (including Oracle)

**Comment by BHHorness-NOAA** [comment]
Not a problem - ignore.
