### ISSUE TITLE
OTS Can't create new trips in android

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1104]
Not sure if this is a bug or me needing instruction

When accessing OTS from my android phone I can log in and navigate around without issue. I can also edit created trips. Clicking on the create new trip button doesn't open the trip creation. The button pulses white showing it has been pressed but no other action occurs. I have replicated this using chrome and firefox. Android version is 10.

**Comment by scottleach-NOAA** [comment]
Here is a video

**Comment by scottleach-NOAA** [comment]
Here is a video. Github doesn't support videos so I just zipped the file. 
  
[OTS video.zip](https://github.com/nwfsc-fram/boatnet/files/3902782/OTS.video.zip)

**Comment by sethgerou-noaa** [comment]
when you have a chance, please log out and back in, give it the app 15 - 20 seconds to update itself, then refresh.  Then see if you can create a trip.  My theory is that I had made some changes that broke the app -should be working now - I just tested on an android phone and did not experience this issue.
