### ISSUE TITLE
Taxonomy Alias Review

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1108]
Some Issues:
- too many Taxonomy-Alias docs - especially for Lookups
- alias stores entire taxonomy - when combined with high number of docs, makes for slow loads
- confusing difference between shared scientific name doc and individual common name docs
- formatting not standardized - capitalization + all caps stored in common name

Some possibilities:
- taxonomy/alias db
- single lookup doc combining scientific name, common name(s) per program
- reference the taxonomy via ID?
-

**Comment by wsmith-nwfsc** [comment]
Review complete. Action item is ticket #1118
