### ISSUE TITLE
Taxonomy Alias refactor and rebuild data

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#1118]

**Comment by wsmith-nwfsc** [comment]
If you need to, I recommend you ignore all the internet arguments about how to implement Title Case and just use https://www.npmjs.com/package/title-case

**Comment by NickShafferNOAA** [comment]
This kept getting pushed on the backburner, but got to it today. Refactored the code. It was quite a simple change in itself, but can't quite build the project to run the script due to build errors caused by refactoring to use the boatnet npm module. Needing to push model changes to npm to eliminate issues to run the code to rebuild all the aliases.

**Comment by NickShafferNOAA** [comment]
Rebuilt the taxonomy-alias documents (to have one per taxonomy doc) + the catch-grouping documents because those have an embedded taxonomy-alias document. 

I just kicked off the script for a fresh pull of wcgop data, it is building haul/catch documents with the refactored docs without issue.
