### ISSUE TITLE
OTS additional trip creation question for EM EFP

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1135]
EM EFPs can choose to fish maximized retention or optimized retention. Maximized retention trips should never be selected for observer coverage. Optimized retention should be selected for observer coverage. 

After a EM EFP permit is entered the following question should be asked.
Will this trip be maximized retention?
Yes
No
I don't know

No and I don't know should have the opportunity for an observer selection.

**Comment by sethgerou-noaa** [comment]
If a user creates a trip having selected 'No' or 'I don't know', and the trip is selected, when the user edits the trip and changes to 'Yes', should that remove the selection for the trip?

**Comment by scottleach-NOAA** [comment]
That is correct. If a user changes the EM EFP trip to maximized retention yes then there wouldn't be an observer selection but that yes should carry forward to the next EM EFP no or don't know trip.

**Comment by sethgerou-noaa** [comment]
ok, makes sense. thanks!
