### ISSUE TITLE
Tallies Screen

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#114]
- [x] Update mockup (add Tally link to Hauls screen - should be on Catch screen)
- [x] Create initial components
- [x] Create button grid
- [x] Create routes (+ catch param)
- [x] Create/ identify Tally data models (initial pass)
- [x] Sound
- [x] Working as a PWA #327 
- [x] Control buttons row
- [x] Vuex state machine #328 
- [x] Create Tally data in pouch/couch + sync (temp schema)
- [x] Tally Mode +- functionality
- [x] Settings: Enable/ Disable Sound
- [x] Import SPECIES until we have Taxonomy imported
- [x] Decouple data from button layout
- Modify Layout functionality:
  - [x] Reset Data
  - [x] Add Named Species
  - [x] Delete Tally
  - [x] Move Tally  
  - [x] Add Existing Species Tally
  - [x] Add Temp Species
  - [x] Name Temp Species
  - [x] Modify Disp. (?)
- [x] Last clicked indicator (little +/- badge?)
- [x] All Tallies For ... functionality
- [x] Loading of Template Layouts
- [x] Weights For ...functionality
- [x] History functionality
- [x] Menu/UI for Template Layout Loading
- [ ] Saving of Template Layouts + Menu / UI
- [x] PDF Report Generation
- [ ] Scale buttons to fill screen consistently

## For later:
- [ ] Scratch Pad - UNID1, UNID2, etc then add species/dis later (how is this different from Add Temp Species? - these buttons would be predefined and already shown on the palette)
- [ ] Settings TBD (Default Colors?)
- [ ] Multi-page functionality (?)

**Comment by wsmith-nwfsc** [comment]
Since we haven't imported taxonomy, I need to (temporarily?) import SPECIES to get this working. #342

**Comment by ericbrasseur-NOAA** [comment]
![tally weight pop up](https://user-images.githubusercontent.com/45770674/58514152-fee2f200-8155-11e9-9955-43700eae19b6.jpg)
example of tally weights pop up with option to include/exclude count.  tallied would be default.

**Comment by wsmith-nwfsc** [comment]
Thanks @ericbrasseur-NOAA, I'll go with that

**Comment by wsmith-nwfsc** [comment]
![image](https://user-images.githubusercontent.com/12972097/58745200-c9166580-8402-11e9-82f0-4a0b8c66bc00.png)
Tinkering a little with saving templates, but ready to demo on Monday
