### ISSUE TITLE
upgrade bn-pouch for ashop app

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1152]
run yarn add @boatnet/bn-pouch@latest
then lerna bootstrap, lerna clean, lerna run build

**Comment by melinashak-noaa** [comment]
The newest vue-pouch version changed the order of arguments so the current queries need to be modified in order to work with the new update. 

In the example below must reorder arguments in order to work with the new pouch
For example the old query statement format: $pouch.query(db, 'map/reduce function', options)
new one query format: $pouch.query('map/reduce function', OPTIONAL options, OPTIONAL db)

Old Version: https://www.npmjs.com/package/pouch-vue/v/0.1.37
New Version: https://www.npmjs.com/package/pouch-vue/v/0.3.5

**Comment by sethgerou-noaa** [comment]
Shoutout to @melinashak-noaa !  Thanks for doing this first and providing examples of what changed in Pouch - made this much easier for me to implement on Obs-Web.
