### ISSUE TITLE
Ashop people can't login

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1194]
![image](https://user-images.githubusercontent.com/44685558/71700692-467bcd00-2d7a-11ea-9870-edb4c4a0bef1.png)
![image](https://user-images.githubusercontent.com/44685558/71700699-4c71ae00-2d7a-11ea-94dc-870a46adc237.png)
![image](https://user-images.githubusercontent.com/44685558/71700712-6c08d680-2d7a-11ea-91cb-652211a0107b.png)

**Comment by wsmith-nwfsc** [comment]
Going to do some initial sanity checks here. 
The auth server should be handling all the couchdb user creation, pw changes,  etc. The behavior she is seeing seems to indicate that isn't happening correctly.

**Comment by wsmith-nwfsc** [comment]
Also, I'm assuming this is for the specific user we've discussed offline. Other ashop users are able to login ok AFAIK.

**Comment by melinashak-noaa** [comment]
yes vanessa was able to login successfully, but jeannine and cassandra both ran into issues

**Comment by wsmith-nwfsc** [comment]
@melinashak-noaa Jeannine said it seemed to be working when she logged into observer-web, but it's unclear how that could be the case, since directly logging into couchdb wasn't working for her, so it may have just appeared to be working for her (not sure if she saw sync etc.)
Still investigating...

**Comment by wsmith-nwfsc** [comment]
@melinashak-noaa brainstorming possible issues:

* Something unique in the ashop code, vs obs-web code. We want to re-verify that the user is able to login to observer-web and that the DB sync occurs.

* Possible CouchDB issues
  * Maybe for some reason the password isn't able to be stored in CouchDB exactly. I don't see any limitations in the documentation, but one possibility--maybe it's super long or has unusual characters. 
  * Possible misconfiguration of the prod couchdb

* Still walking through the code to see if there's something unusual in there. Again, the weird thing is that 3 users can login OK, and 2 users cannot

Potentially, the prod couchDB is misconfigured.

**Comment by wsmith-nwfsc** [comment]
Verified that user cannot login to observer-web either, with the same error.
I have a proposed fix that I think will resolve this, #1229

**Comment by wsmith-nwfsc** [comment]
Aiming to deploy this proposed fix early this week

**Comment by wsmith-nwfsc** [comment]
I rolled out this change. I'm hoping this fixes this specific issue, but if not, it will make troubleshooting easier.
