### ISSUE TITLE
Connect Drill to Oracle

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1245]
Use JDBC to connect local drill node to Oracle IFQ Admin.

**Comment by jimfellows-NOAA** [comment]
Connected successfully to Local Express and IFQADMIN.

See https://drill.apache.org/docs/rdbms-storage-plugin/#Example-Oracle-Configuration

**Comment by wsmith-nwfsc** [comment]
Very cool, interested to hear about this at next team meeting.
