### ISSUE TITLE
Stock Synthesis: Simple Model Build

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1257]
Continues #1232 

After SS binary is built on Jenkins, build the contents of https://vlab.ncep.noaa.gov/redmine/projects/ss_examples/repository/Simple in the vlab repo. 

- [x] Create new jenkins job if appropriate (future ss builds will be larger)
- [x] Pull https://vlab.ncep.noaa.gov/redmine/projects/ss_examples/repository (use correct git ssh link from the redmine site, this is not a git link)
- [x] Extract ss, copy to jenkins instance (from previous pipeline build)
- [x] Execute ss executable on Simple directory
- [ ] Archive artifact

**Comment by k-doering-NOAA** [comment]
@wsmith-nwfsc need any info or help from me or @iantaylor-NOAA?

**Comment by wsmith-nwfsc** [comment]
I've been out for part of this week, but I think I have what I need to try and drop this in. I'll see if I can get it running soon, possibly today.

**Comment by k-doering-NOAA** [comment]
No rush, thanks, Will!

**Comment by wsmith-nwfsc** [comment]
@k-doering-NOAA I'm putting this job together, but I don't seem to have access to https://vlab.ncep.noaa.gov/redmine/projects/ss_examples/repository (either with my noaa credentials or with the stock synthesis build account.) Do you have access to grant those permissions?

**Comment by wsmith-nwfsc** [comment]
* it appears something changed on the Jenkins server which is preventing the stock synthesis build from executing correctly (nothing changed script wise,) so investigating what's up there

**Comment by wsmith-nwfsc** [comment]
@k-doering-NOAA 
Seems to be working! I takes a little under 2 minutes to run.
After it runs, should I just zip up the whole Simple directory for the finished "artifact"?
Here's the end of the run and a directory listing:

```
In final section 
Finish time: Wed Mar  4 23:34:54 2020
Elapsed time: 0 hours, 1 minutes, 39 seconds.
Final gradient: 1.93926e-06

 finished COVAR.SSO
 finished forecast for reporting
 finished STD quantities for reporting
 mceval counter: 0
 finished posteriors reporting
 finished SS_summary.sso
 finished rebuilder.sso 
 finished SIStable.sso 
 writing big output now 
 finished report.sso
 Write new starter file 
 Write new forecast file 
 Write new control file 

!!  Run has completed  !!            See warning.sso for N warnings: 1
```

```
[Pipeline] sh (Get dir listing)
+ ls -alh CumReport.sso Forecast-report.sso ParmTrace.sso Simple echoinput.sso fmin.log ss ss.log warning.sso wtatage.ss_new
-rw-r--r-- 1 498 498    0 Mar  4 23:27 CumReport.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:31 Forecast-report.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:31 ParmTrace.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:31 echoinput.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:31 fmin.log
-rwxrwxrwx 1 498 498 3.7M Mar  4 23:03 ss
-rw-r--r-- 1 498 498    0 Mar  4 23:31 ss.log
-rw-r--r-- 1 498 498    0 Mar  4 23:31 warning.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:31 wtatage.ss_new

Simple:
total 9.5M
drwxr-xr-x 2 498 498 4.0K Mar  4 23:34 .
drwxr-xr-x 4 498 498  203 Mar  4 23:33 ..
-rw-r--r-- 1 498 498 301K Mar  4 23:34 CompReport.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:33 CumReport.sso
-rw-r--r-- 1 498 498  21K Mar  4 23:34 Forecast-report.sso
-rw-r--r-- 1 498 498    1 Mar  4 23:33 ParmTrace.sso
-rw-r--r-- 1 498 498 993K Mar  4 23:34 Report.sso
-rw-r--r-- 1 498 498 6.1K Mar  4 23:34 SIS_table.sso
-rw-r--r-- 1 498 498  24K Mar  4 23:34 admodel.cov
-rw-r--r-- 1 498 498 142K Mar  4 23:34 admodel.dep
-rw-r--r-- 1 498 498  24K Mar  4 23:34 admodel.hes
-rw-r--r-- 1 498 498  19K Mar  4 23:33 control.ss
-rw-r--r-- 1 498 498  20K Mar  4 23:34 control.ss_new
-rw-r--r-- 1 498 498 3.3M Mar  4 23:34 covar.sso
-rw-r--r-- 1 498 498  19K Mar  4 23:33 data.ss
-rw-r--r-- 1 498 498  19K Mar  4 23:34 data.ss_new
-rw-r--r-- 1 498 498 5.6K Mar  4 23:34 derived_posteriors.sso
-rw-r--r-- 1 498 498 101K Mar  4 23:33 echoinput.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:33 fmin.log
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 forecast.ss
-rw-r--r-- 1 498 498 4.2K Mar  4 23:34 forecast.ss_new
-rw-r--r-- 1 498 498  136 Mar  4 23:33 gradient.1
-rw-r--r-- 1 498 498 1.5K Mar  4 23:33 gradient.2
-rw-r--r-- 1 498 498 1.6K Mar  4 23:33 gradient.3
-rw-r--r-- 1 498 498 1.8K Mar  4 23:33 gradient.4
-rw-r--r-- 1 498 498 2.3K Mar  4 23:33 gradient.dat
-rw-r--r-- 1 498 498    0 Mar  4 23:34 posterior_obj_func.sso
-rw-r--r-- 1 498 498 3.1K Mar  4 23:34 posterior_vectors.sso
-rw-r--r-- 1 498 498 4.8K Mar  4 23:34 posteriors.sso
-rw-r--r-- 1 498 498    0 Mar  4 23:34 rebuild.sso
-rw-r--r-- 1 498 498    1 Mar  4 23:33 runnumber.ss
-rwxr-xr-x 1 498 498 3.7M Mar  4 23:33 ss
-rw-r--r-- 1 498 498  768 Mar  4 23:33 ss.b01
-rw-r--r-- 1 498 498  768 Mar  4 23:33 ss.b02
-rw-r--r-- 1 498 498  768 Mar  4 23:33 ss.b03
-rw-r--r-- 1 498 498  768 Mar  4 23:33 ss.b04
-rw-r--r-- 1 498 498  768 Mar  4 23:33 ss.bar
-rw-r--r-- 1 498 498 468K Mar  4 23:34 ss.cor
-rw-r--r-- 1 498 498 1.3K Mar  4 23:34 ss.eva
-rw-r--r-- 1 498 498  119 Mar  4 23:34 ss.log
-rw-r--r-- 1 498 498 2.2K Mar  4 23:33 ss.p01
-rw-r--r-- 1 498 498 2.2K Mar  4 23:33 ss.p02
-rw-r--r-- 1 498 498 2.2K Mar  4 23:33 ss.p03
-rw-r--r-- 1 498 498 2.2K Mar  4 23:33 ss.p04
-rw-r--r-- 1 498 498 2.2K Mar  4 23:33 ss.par
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 ss.r01
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 ss.r02
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 ss.r03
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 ss.r04
-rw-r--r-- 1 498 498 4.0K Mar  4 23:33 ss.rep
-rw-r--r-- 1 498 498  17K Mar  4 23:34 ss.std
-rw-r--r-- 1 498 498  17K Mar  4 23:34 ss_summary.sso
-rw-r--r-- 1 498 498 2.4K Mar  4 23:33 starter.ss
-rw-r--r-- 1 498 498 2.5K Mar  4 23:34 starter.ss_new
-rw-r--r-- 1 498 498  482 Mar  4 23:34 warning.sso
-rw-r--r-- 1 498 498 162K Mar  4 23:34 wtatage.ss_new

```

**Comment by k-doering-NOAA** [comment]
@wsmith-nwfsc this is great news, thanks so much for working on this!

Yes, it make sense to zip the Simple directory... Hmm, do you expect there to be an advantage to selecting only certain files? Many of the files we would probably never look at, but it might be helpful to keep everything for now if there isn't a big penalty in terms of speed or storage?

**Comment by wsmith-nwfsc** [comment]
I think it's small enough that we can happily just zip up the whole Simple folder.

This jenkins job is stock-synthesis-model, and we can use that as a jumping off point for building more interesting stuff.

**Comment by k-doering-NOAA** [comment]
Sounds good - and I see the job in my account.

I will brainstorm tomorrow about where to go next and how to incorporate the current jenkins jobs  into our SS development workflow - I think already it will be useful to the SS developers!

**Comment by wsmith-nwfsc** [comment]
Cool. 
The archived Simple folder (including a copy of the ss binary used to create the output) is less than 3 megabytes, so we should be good to proceed!

**Comment by wsmith-nwfsc** [comment]
For the next phase, we'll probably want to create a new github issue (and can reference this one)

**Comment by wsmith-nwfsc** [comment]
![image](https://user-images.githubusercontent.com/12972097/75934828-7f93f480-5e32-11ea-81c0-98d64b029690.png)

**Comment by wsmith-nwfsc** [comment]
Next steps outlined in #1401
