### ISSUE TITLE
Plan relation between Couch WCGOP Trips & Operations going forward

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1261]
How are we going to relate wcgop-trips & wcgop-operations data for reporting purposes going forward?  In order to reduce the number of custom views written into couch, we may want to use the all-trips and all-operations views as the source, and do most of the processing with drill after doing a basic dump from couch.

 _Option 1_
Use wcgop-operations-flat-YYYY, which associates every trip document with its corresponding operations documents for a given year.  Means we'll have to create an extra view for every year.

_Option 2_
Use all-trips & all-operations, which cover all wcgop trips & operations.  After dumping those views, we can do any processing/relating between the two with Apache Drill.  

all-trips.json = 0.2 GB
all-operations = 6.5 GB
all-operations-flat-2019 = 0.5 GB

**Comment by wsmith-nwfsc** [comment]
I like the idea of partitioning by year, and we can query across all years as desired. At least this would be a good starting point that allows us to keep queries smaller as we start to develop this capability.

**Comment by jimfellows-NOAA** [comment]
Yea, that may make more sense from a storage perspective too...I wasn't sure if creating those views for every year would eventually be a drag on Couch.

 We could still partition by year with Option 2, but it might be redundant dumping out data into JSON without any transformation from its form in couch.  In my head the flow of data would look like:
1. Dump all-trips, all-operations to JSON
2. Convert JSON to parquet
3. Flatten & partition with Drill to something like below:

_drill_data_storage/trips_
- _/trips_2019_
- _/trips_2018_
- _/trips_2017..._

**Comment by jimfellows-NOAA** [comment]
keeping the status quo for now, planning on building out year-specific views to link wcgop-trips and operations.
