### ISSUE TITLE
update gear performance widget

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1265]
1 - No problem
2 - Problem: Fouled set / Net twisted / Wires crossed
3 - Problem: Net or codend ripped
4 - Problem: Net or codend lost
5 - Problem: Crab pot in haul
6 - Problem: Net hung up on some obstacle and vessel had to back down
7 - Problem: Other.  [Include COMMENTS field here, with maybe 50-100 characters of space]
8 - Fishing duration affected (does not include Shortwiring): Deployment and retrieval times do not reflect true fishing time

The codes are irrelevant, we just want the associated info.

**Comment by melinashak-noaa** [comment]
added config for these values

**Comment by wsmith-nwfsc** [comment]
Probably already know this, but these are in lookups-dev (doc type: gear-performance)

**Comment by melinashak-noaa** [comment]
oh yeah those are the ones i just added the other day
