### ISSUE TITLE
Configure SparkSession that connects directly to CouchDB

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1284]
Looking into a way to use Spark to read JSON/document data straight from CouchDB and save results into parquet files.  I've been able to first dump Couch data out and save as JSON and then read files into Spark, but we could cut out the JSON file step and go directly from Couch to Parquet via Spark.

@wsmith-nwfsc have you had any luck doing this?

https://stackoverflow.com/questions/45207011/how-to-connect-to-cloudand-couchdb-using-sparksql-in-datascience-experience

**Comment by wsmith-nwfsc** [comment]
Going to review my notes on this, I think I had it working at one point

**Comment by wsmith-nwfsc** [comment]
I dusted off my notes and have this working, somewhat:

![image](https://user-images.githubusercontent.com/12972097/74561064-c4f09080-4f1c-11ea-8a9e-18f33bf4853b.png)

![image](https://user-images.githubusercontent.com/12972097/74561203-01bc8780-4f1d-11ea-9d53-44bc0585efd5.png)

**Comment by wsmith-nwfsc** [comment]
![image](https://user-images.githubusercontent.com/12972097/74561330-3d575180-4f1d-11ea-9219-db09482e0204.png)

**Comment by wsmith-nwfsc** [comment]
This was from my hastily scribbled notes, not exactly sure what I was doing here, but for future reference:

```
spark-shell --packages org.apache.bahir:spark-sql-cloudant_2.12:2.4.0
* added spark-defaults.conf
spark.jars.packages	org.apache.bahir:spark-sql-cloudant_2.12:2.4.0
https://github.com/apache/bahir/tree/master/sql-cloudant

compatibility issue? https://mvnrepository.com/artifact/org.apache.bahir/spark-sql-cloudant get new version
changed to spark.jars.packages	org.apache.bahir:spark-sql-cloudant_2.11:2.4.0
WORKING!
Not using config options?
https://stackoverflow.com/questions/48055133/sparksession-not-picking-up-runtime-configuration

Added under interpreter options. Working!!!!!!

set PATH=%PATH%;c:\spark-2.4.4-bin-hadoop2.7\bin
spark-submit --master local[*] --deploy-mode client spark-rumble-1.3.jar --shell yes
```

**Comment by jimfellows-NOAA** [comment]
thanks for digging all this up.  Created a zeppelin interpreter with my user/pw:host built in, but I think I need to play around with the jar that I'm trying to use...

![image](https://user-images.githubusercontent.com/57507677/74564734-94acf000-4f24-11ea-91af-20780f25236f.png)

![image](https://user-images.githubusercontent.com/57507677/74564904-ee151f00-4f24-11ea-8da3-1c2527a1f03f.png)

**Comment by wsmith-nwfsc** [comment]
Shall definitely try to be more exacting with my notes when I get this up and running on old ironsides. Hard part was definitely getting the correct version of various Jars to be aware of each other.

**Comment by wsmith-nwfsc** [comment]
Also, the warning you highlighted seems OK--I've gotten that one from the beginning.

**Comment by wsmith-nwfsc** [comment]
One note for the future is that I had to roll back to ```org.apache.bahir:spark-sql-cloudant_2.11:2.4.0``` (I forget exactly how I did that. Guess we'll find out...)
