### ISSUE TITLE
Pulled new version of boatnet and now getting issues when running dev-auth-server

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1312]
![image](https://user-images.githubusercontent.com/44685558/73987493-71b38800-48f5-11ea-9f13-32a33bd8e9c0.png)

**Comment by melinashak-noaa** [comment]
Followed [this ](https://github.com/nwfsc-fram/boatnet/tree/master/apps/dev-auth-server) and ran yarn install and created my own authProxyConfig.json file

**Comment by wsmith-nwfsc** [comment]
Looks like you're on the "fixes" branch, is that just to fix this issue?
Weirdly, it looks like your configuration is using an old version of typescript. Hmmm

![image](https://user-images.githubusercontent.com/12972097/73988137-a5db7880-48f6-11ea-95dc-4e8e90900be4.png)

**Comment by wsmith-nwfsc** [comment]
Can't repro, looks like your environment is in a weird state.
I'd rm -rf your node_modules folder in boatnet and start over.

**Comment by melinashak-noaa** [comment]
Hmmmm getting this error again, I've rm -rf node_modules and yarn_lock, then ran lerna bootstrap, lerna clean, but still getting the same error 

Also followed this guide as well https://github.com/nwfsc-fram/boatnet/blob/master/docs/dev-notes/README.md#troubleshooting-build-issues

**Comment by wsmith-nwfsc** [comment]
I cleared out my yarn.lock, etc, and I am getting this error now too. Taking a closer look.
dev-auth-server doesn't build on Jenkins so we won't see the error there.

**Comment by melinashak-noaa** [comment]
upgraded typescript in dev-auth-server/package.json to 3.6.4 and now it's working
