### ISSUE TITLE
Duplicate Observer Documents in CouchDB

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1313]
Discussed issue with Nick already, creating issue for tracking.  Looks like a set of observer/person documents were generated once in an earlier ETL, and then a duplicate set of observers with different couch_ids but the same information was created again, resulting in duplicate documents for each observer.  Sounds like the initial set of docs could be removed, and this issue will be resolved.

Observer count info and couch documents for 2017-2019 analysis can be found in the spreadsheet here:
\\nwcfile\FRAM\Users\James.Fellows\oracle_to_couch_qc\duplicate_observers_in_couch.xlsx

**Comment by NickShafferNOAA** [comment]
Already figured out how this happened and made the tiny fix in the etl code. There's just the issue of pulling down and deleting the right documents.
