### ISSUE TITLE
ETL A-SHOP Trips Data (>2007)

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#133]
- [x] Trips
- [x] Hauls
- [x] Samples
- [x] SampleSpecies
- [x] Specimens
- [x] Baskets

**Comment by toddhay-NOAA** [comment]
it looks like you're done with this initial task @NickShafferNOAA , if so, feel free to close this out.

**Comment by NickShafferNOAA** [comment]
Basic structure and most look up data in place and done for these. Closing the ticket.
