### ISSUE TITLE
Research Drill Query Optimization

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1331]
Trying to increase the speed on my local drill setup, and get a better idea of what we might be able to do on a more powerful / sustainable distributed setup.

Things that look interesting:
[Drill Docs](https://drill.apache.org/docs/performance-tuning-introduction/) (whole section looks good)
[Drill's Built-In Partitioning](https://drill.apache.org/docs/partition-by-clause/)
[Table Metastores](https://drill.apache.org/docs/using-drill-metastore/)

**Comment by wsmith-nwfsc** [comment]
Once I get old ironsides back, we should get some more visibility on this too.

**Comment by jimfellows-NOAA** [comment]
Yea I agree, looking forward to seeing old ironsides back in action.  Creating table metadata seems useful on a more powerful set up, I think my limiting factor right now is my embedded setup / local machine.

Using Drill's new CREATE TABLE XYZ PARTITION BY (YEAR) functionality was helpful just from a coding perspective, as before I was creating subdirectories via script, now its done automatically.
