### ISSUE TITLE
Stock Synthesis: Next Steps

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1401]
Continues #1257 

Notes to go through/ strategize from @k-doering-NOAA 
---

Here are some ideas on next steps to 1) make what you have already built useful to the SS team and 2) expand on the existing jobs.

using what is already there
- accounts for team members so they can trigger builds/see artifacts themselves
- maybe setup a weekly cron build?
- maybe you could show me around the jobs a bit so I can get a better feel on how it is set up? I can then educate the rest of the SS team on this. Another possibility is that you can meet with all of us, but that would be harder to coordinate because of everyone's schedules.

directions forward

1. using the stock-synthesis-build to create all the executables we distribute.
 - need to build ss.exe and ss_trans.exe at a minimum; maybe also ss_opt.exe
 - it would be great to build windows and mac versions
 - this would be 9 total executables.
- I think for now we will manually post the exes to vlab ( https://vlab.ncep.noaa.gov/web/stock-synthesis/document-library/-/document_library/0LmuycloZeIt/view/5042555) as we won't want to automatically post every build...but maybe you can convince me otherwise! It does seem like it is a task we could automate. 

2. create some tests for stock-synthesis-model
 - ss_summary.sso contains some model quantities.
 - it would be great to compare these against an older version and see if they have change more than some tolerance level.
 - TOTAL_LogL is a good quantity to start with (maybe tolerance level ~1 to start with?)
 - maybe we could do this via the command line? KD could also modify some existing R code to do this.

3. Run more models
 - I can add a more models to the SS_examples repo.
 - we can set these up to also run with SS. The model files from these should also be saved like for the simple model.
 - the SS team currently has 27 models to run, although we may expand this set in the future.

* We intend to have a brief meeting to go over what's currently in place and discuss the above

**Comment by k-doering-NOAA** [comment]
Relevant to number 2 and 3 in the above list: R code to run SS models in a loop and put output in a spreadsheet, and use the r4ss package functions to create plots: https://github.com/r4ss/testing/blob/master/run_SS_test_set.R . We are working on improving this code still (need to figure out how to better catch errors and parse them so we know which model is producing them).

**Comment by wsmith-nwfsc** [comment]
Attaching sequence diagrams for today's meeting
![stock-synthesis-build](https://user-images.githubusercontent.com/12972097/78065142-aff28400-7347-11ea-9dda-5024f91efc91.png)
![stock-synthesis-model](https://user-images.githubusercontent.com/12972097/78065148-b1bc4780-7347-11ea-8b49-f99ded38de2d.png)

**Comment by k-doering-NOAA** [comment]
These are great, thanks @wsmith-nwfsc !

**Comment by k-doering-NOAA** [comment]
I had some time Friday to start thinking more about next steps and wrote some pseudocode for comparing results of Simple to a previous run.

**Purpose**: Compare likelihood components and look for a change in >2 likelihood units (somewhat arbitrary limit)

**Data**
- Old ss_summary.sso from simple model (stored within vlab SS_models repository)
- New ss_summary.sso from simple model run using Jenkins

Table within ss_summary.sso looks like:
```
#_LIKELIHOOD 
Label logL*Lambda
TOTAL_LogL 6.58543e+18
Catch 3.60731e-13
Survey 103.192
Length_comp 774.179
Age_comp 752.837
Size_at_age 81.7489
Recruitment 6.45347e+18
InitEQ_regime 0
Sum_recdevs 1.00429e-09
Forecast_Recruitment 1.31963e+17
Parm_priors 3.13582
Parm_softbounds 0.0012046
Parm_devs 0
F_Ballpark 0
Crash_Pen 0
```

**Pseudocode**
- [ ] Pull the likelihood table from old and new ss_summary.sso text files. Get text and values stored as separate columns.
- [ ] Round all values within the table to 3 decimal places.
- [ ] Find the difference between these values: new likelihood - old likelihood.
- [ ] Look for diffs greater than or equal to 2. If there are any, return the names and values of the components with differences and maybe the other model files as an artifact? If there aren’t any differences, Jenkins passess and no artifacts are necessary to return.

**Some options on tools to use**:
- Linux command line and AWK (I recently learned about this option; it would take a bit of googling for me to figure out how to write this code)
- R (seems unnecessary to use R for this purpose, but I could easily write code to do this in R.)
- Something else?

@wsmith-nwfsc I wonder if you have any suggestions on a tool to use to do this next step, as I imagine you are familiar with some options I have not thought of. 

Also, I am happy to  add more details to this if anything is unclear and don't mind taking a stab at writing some code, either.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA for putting this together. Your description and suggestions all look good to me. I would note, however, that the example table of likelihood values seems to be from a model that did not have a good solution (`TOTAL_LogL 6.58543e+18`). In general, the values to be compared will probably be in the hundreds or thousands at most, as in the example below:
```
#_LIKELIHOOD 
Label logL*Lambda
TOTAL_LogL 412.776
Survey -5.43203
Age_comp 417.968
Recruitment 0
InitEQ_regime 0
Sum_recdevs -8.42443e-009
Forecast_Recruitment 2.09974e-017
Parm_priors 0.239765
Parm_softbounds 0
Parm_devs 0
F_Ballpark 0
Crash_Pen 0
```
This is relevant because the rounding should probably be on the actual values, not the significant digits shown in scientific notation. That is the values of `Forecast_Recruitment 2.09974e-017` above, and some alternative, like `Forecast_Recruitment 9.9999e-017` are both essentially zero and the difference between them could be ignored.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA good point, thanks! I just grabbed this from the first model I found, which I ran without optimizing. And I also agree with your explanation of how rounding should be done.

**Comment by k-doering-NOAA** [comment]
@wsmith-nwfsc I was wondering if you have any advice about tools to use to implement the pseudocode I describe? If you are busy and can't think about this right now, feel free to say so, and perhaps I will try coding up something in a tool I can use.

**Comment by wsmith-nwfsc** [comment]
Sorry for the delayed response!

I like the idea of using R (instead of awk) to perform the analysis steps you described, which will give us a good starting point to expand on in the future (where awk would eventually reach its limit)

I believe getting a Docker container with R running on it would be the next step, and then we can try to get the other required libraries on it (via CRAN I think?) and run some more complex analysis in the future.

**Comment by k-doering-NOAA** [comment]
Thanks for your feedback, @wsmith-nwfsc ! I appreciate input from someone who doesn't use R for everything whether or not it is correct. R it is, then (and it means I don't have to learn something new to me ). 

For the analysis I described, I actually don't think we would need to download additional packages, but if we do, I think it would be fairly straightforward to do so. I would typically run
```
install.packages("packagename")
```
within an R session, which I think you could do via the command line using something like
```
rscript -e "install.packages("packagename")"
```
as long as rscript.exe is in the PATH. Not sure how this translates to Linux, as I've only done this on windows. This [guide on invoking R from the command line ](https://cran.r-project.org/doc/manuals/R-intro.html#Invoking-R-from-the-command-line) might come in handy.

Do you think you would have some time in the near future to add R to the Docker container? If not, I can give it a shot. 

I can also start writing some R code to do this analysis, which I don't think will take too long at all.

**Comment by wsmith-nwfsc** [comment]
@SaOgaz-NOAA may have some input as far as adding R to docker-- did we end up doing this somewhere else? (Or do we just have it installed directly on the nwctantalus server)

**Comment by wsmith-nwfsc** [comment]
I believe getting R on docker would be as simple as using the r-base docker hub image, https://hub.docker.com/_/r-base

Then the Jenkins job would copy the .sso files of interest (to be determined how/where we would store these--currently we have the newest .sso file as a Jenkins artifact, so possibly just stick the "known reference" one in source control is easiest.

**Comment by wsmith-nwfsc** [comment]
I created a new (empty) Jenkins pipeline named stock-synthesis-compare as a starting point. The stock-synthesis-model job is probably a good reference to copy, and we'll need to create a new Dockerfile and Jenkinsfile to perform this task (in the local gitlab, similar to how stock-synthesis-model is already set up.)

**Comment by k-doering-NOAA** [comment]
Okay, that makes sense!

I'm thinking a known reference one in https://vlab.ncep.noaa.gov/redmine/projects/ss_examples/repository to compare from the artifact ss_summary.sso would be a good starting point.  I think that way it would be easy to swap out as well, if we had a reason for doing so.

I was thinking to add it to the same folder as the model files are in currently, unless some place else is better?

**Comment by k-doering-NOAA** [comment]
Okay, thank you for setting up the new empty pipeline! If you want, I have some time to work on this this afternoon, and then maybe I can ask you questions if I get stuck?

**Comment by iantaylor-NOAA** [comment]
The r4ss package that we maintain here at NWFSC includes functions to parse the Stock Synthesis .sso files, but loading it each time would be slow as the package depends on a handful of other packages.

More efficient would be to just use r-base and load the single r4ss function "SS_read_summary" either directly from GitHub (https://raw.githubusercontent.com/r4ss/r4ss/development/R/SS_read_summary.R) or mirrored on VLab or somewhere else.

Loading that function could be at the top of the script that @k-doering-NOAA writes to compare files.

**Comment by k-doering-NOAA** [comment]
I had forgotten that function existed, thanks, Ian! It seems like using and loading just that function for the purpose of this analyses is a good idea. (or, just using the parts of it we want).

I was trying to avoid r4ss for this step to make the analysis independent of r4ss::SS_output() and r4ss::SS_plots() having to work (which doesn't always happen with i/o changes), but I think using the SS_read_summary() is itself independent of those functions.

**Comment by SaOgaz-NOAA** [comment]
I did end up using a couple different R dockers when I was trying to get the bar_job working. But I was having issues getting one of the R package installs to work properly. So in the end I just had Marcus install R onto nwctantalus.

**Comment by k-doering-NOAA** [comment]
Thanks to @wsmith-nwfsc  and @SaOgaz-NOAA, I was able to get an initial job running that sends back the differences between a new model run and a reference model run as an artifact. I used https://hub.docker.com/r/rocker/r-ver/ for the Docker image at @SaOgaz-NOAA 's suggestion. I did not need to load any extra packages, so did not encounter issues with this docker image.

To do next:

- [ ] Make this a fully automated test by telling jenkins the build failed when the differences between log likelihoods are too large.
- [ ] Get input from the SS team on criteria for too large of model diffs.
- [ ] Test the differences between more inputs for Simple.
- [ ] Extend the approach to multiple models

@wsmith-nwfsc, feel free to look at the jenkins file i wrote and offer suggestions or just directly push changes, as I am new to both jenkins and the linux command line. In particular, I had problems with folders being cached (I expected a blank workspace each time I ran jenkins, but it seems that folders and files created in previous runs persisted; I would prefer a blank workspace each time, if there is a way to get this, unless you advise against it) and it appeared that cd did not actually work unless used in the same line as another command (which is fine, now that I understand).

**Comment by k-doering-NOAA** [comment]
I am making good progress on getting these jobs set up! We now have:
- A job to build all linux versions of SS (stock-synthesis-build-linux)
- Automated testing of 1 model 

Next steps are:

- [ ] Extend the approach to multiple models
- [ ] Add in a more complete testing model that RM is developing
- [ ] Develop a new job that tests r4ss::SS_output and r4ss::SS_plots (https://github.com/r4ss/r4ss)

**Comment by wsmith-nwfsc** [comment]
We have this up and running pretty well now, so closing out this issue, as it's gotten pretty large. 
We can refer to it in future, more bite-sized issues.
