### ISSUE TITLE
Add logging capabilities to couch-to-parquet python script

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1410]
Add logging to python script that pulls data from couch and transforms the data into queryable parquet files for apache drill.

@wsmith-nwfsc alright to continue down this path with Python?  Let me know if there's a preference to develop the reporting ETL process in a specific language, Python was just familiar and seemed like a good tool for the job.

**Comment by wsmith-nwfsc** [comment]
Generally we're trying to keep stuff in typescript + node.js world when possible, but I think using python for scripting applications like this is fine, especially since you've already been successful so far.

**Comment by jimfellows-NOAA** [comment]
Replace print statements with logging functionality in python scripts, and created logging class.  Will likely need to fine tune this later, but for now this should help when the couch-to-drill extraction process is run automatically on a schedule.

New code checked in to fram-data/boatnet-internal/boatnet-reports/couch-to-parquet-pipeline
