### ISSUE TITLE
Create Apache Drill Find Fishing Area Function

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1418]
Need function for observer analysts report that returns a fishing area based on latitude.  Will be an exploratory exercise in created drill custom functions.

Oracle code below:
```
 FUNCTION Fnd_Fishing_Area (p_lat IN INTEGER) RETURN NUMBER IS
v_rtrn NUMBER;
BEGIN
   CASE WHEN p_lat > 40.166667 
   THEN v_rtrn:= 100;
   WHEN p_lat BETWEEN 36.0 AND 40.166667 
   THEN v_rtrn:= 200;
   WHEN p_lat BETWEEN 34.45 AND 36.0 
   THEN v_rtrn:= 300;
   WHEN p_lat < 34.45
   THEN v_rtrn:= 400;
   ELSE v_rtrn := NULL;
   END CASE;


   RETURN v_rtrn;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
 END Fnd_Fishing_Area

```

**Comment by jimfellows-NOAA** [comment]
Function JAR created and tested on my machine in embedded mode.  Checked in code and created readme.md here: boatnet-internal/boatnet-reports/drill-simple-udfs.

**Comment by wsmith-nwfsc** [comment]
This is awesome.

**Comment by jimfellows-NOAA** [comment]
Thanks! Excited to get this started, looking into aggregate funcs now...
