### ISSUE TITLE
Taxonomy-TaxonomyAlias Mismatches

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1424]
Still looking for how prevalent this issue is, but ran into this specific example today on DEV.  Common name in alias doc is Warty Sea Cucumber, scientific name is Phalaropus lobatus AKA [Red-Necked Phalarope](https://en.wikipedia.org/wiki/Red-necked_phalarope):

```
{
    "_id": "22f26efc097ff8682bf3aae781787c1f",
    "type": "taxonomy-alias",
    "taxonomy": {
        "_id": "b630d3c9a52c46b9eb7325eda1b544a2",
        "type": "taxonomy",
        "taxonomyId": "b630d3c9a52c46b9eb7325eda1b544a2",
        "level": "Species",
        "taxonomyName": "Phalaropus lobatus",
        "scientificName": "Phalaropus lobatus",
        "parent": "b630d3c9a52c46b9eb7325eda1a450de",
        "itisTSN": 176735,
        "wormsAphiaId": null,
        "isInactive": null,
        "legacy": {
            "wcgopSpeciesId": 10704,
            "ashopSpeciesId": null,
            "dwId": null
        }
    },
    "commonNames": [
        "Warty Sea Cucumber"
    ],
}
```

**Comment by jimfellows-NOAA** [comment]
Haven't been able to find any other examples, so may just be a one-off, but its a little tricky to figure out a programmatic way to compare scientific vs common names without pulling in ITIS data.

**Comment by NickShafferNOAA** [comment]
Side note: no common names were taken from ITIS, only from the source systems. The scientific names + hierarchies were taken solely from ITIS. 

I believe this is a one off bug. I hard coded a handful of items during some of the initial taxonomy ETL, and I found a typo in there. This wcgop id is incorrectly assigned to this taxonomy item, which cascaded down to this incorrectly assigned alias. This should now be fixed.
