### ISSUE TITLE
Duplicate Taxonomy Documents

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1425]
Ran into a handful of taxonomy documents (~15 pairs in total) with the same scientific name, taxonomy level, and parent ID.  Seems like these should be consolidated:

Doc#1
```
{
    "_id": "4fa0ab1f2ccf04160ab89da3e3ac950b",
    "type": "taxonomy",
    "taxonomyId": "4fa0ab1f2ccf04160ab89da3e3ac950b",
    "level": "Family",
    "taxonomyName": "Alepocephalidae",
    "scientificName": "Alepocephalidae",
    "parent": "4fa0ab1f2ccf04160ab89da3e3ac94d3",
    "itisTSN": 162303
...
```

Doc#2
```
{
    "_id": "4fa0ab1f2ccf04160ab89da3e3ac9bc0",
    "type": "taxonomy",
    "taxonomyId": "4fa0ab1f2ccf04160ab89da3e3ac9bc0",
    "level": "Family",
    "taxonomyName": "Alepocephalidae",
    "scientificName": "Alepocephalidae",
    "parent": "4fa0ab1f2ccf04160ab89da3e3ac94d3",
    "itisTSN": 162303,
...
}
```

Dropped the other examples in an excel file here:
`\\nwcfile\FRAM\Users\James.Fellows\oracle_to_couch_qc\duplicate_taxonomies.xlsx`

**Comment by NickShafferNOAA** [comment]
Hm, this is interesting. Such a small number of duplicates seems to imply it's some kind of edge case. Not sure how this could've happened off the top of my head, will need to investigate.
