### ISSUE TITLE
Create Apache Drill Listagg function

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1427]
A function similar to Oracle's listagg will be very helpful for reporting purposes.

**Comment by jimfellows-NOAA** [comment]
Able to compile with new function, may need to revisit functionality, but closing this for now.

**Comment by jimfellows-NOAA** [comment]
still having trouble getting this to function properly, Apache Drill aggregate functions that deal with string values aren't all that well supported or easy to implement...

**Comment by jimfellows-NOAA** [comment]
Might be a solution here: https://issues.apache.org/jira/browse/DRILL-6963

**Comment by jimfellows-NOAA** [comment]
Jar compiles and working for ArrayAgg function!  Could be super useful for reporting:

![image](https://user-images.githubusercontent.com/57507677/85154749-b1c43900-b20c-11ea-8ab4-ce272a24dae5.png)

**Comment by jimfellows-NOAA** [comment]
fyi for larger datasets, run `ALTER SYSTEM SET `planner.enable_hashagg` = false`

**Comment by wsmith-nwfsc** [comment]
Super awesome.
More options coming soon with Mongo
