### ISSUE TITLE
Docker DNS Lookups Failing (Pacfin, others)

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1458]
Something seems up with our docker instances running the pacfin jobs. They started failing yesterday, and based on what I've googled so far, seems like something might be up with how our hosts are setup. Is there a way I can go in and check the configuration of our servers running the jobs? Also have there been any recent changes/upgrades to these servers? 

Build [job](https://jenkins.nwfsc2.noaa.gov/job/pacfin-data-pull-build/92/console)
**Fails at**: npm install -g typescript
**Error message**: Failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443

[Pacfin-update-column](https://jenkins.nwfsc2.noaa.gov/job/pacfin-column-update-check/99/console)
**Fails at**: RUN yum -y install oracle-nodejs-release-el7
**Error message**: Could not resolve host: yum.oracle.com; Unknown error

One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 5 for Oracle Linux 7Server (x86_64)),
 and yum doesn't have enough cached data to continue

**Comment by wsmith-nwfsc** [comment]
Yesterday DNS lookups seemed to have stopped working inside our Docker images (they work fine on the jenkins server itself.) Poking around to see what might have changed.

**Comment by wsmith-nwfsc** [comment]
Jenkins update seemed to be the culprit. Never version of Jenkins seems to have fixed this, will re-open if still broken.
