### ISSUE TITLE
Create storage-plugins-override.conf for Drill

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1459]
Need to create a config file that stores custom storage plugins for drill, instead of using the REST API.  Also will likely need to figure out the best way to set environmental variables for relevant data storage directories for Drill.  For starters, would like my extract/ETL scripts to reference these configs.

Not sure if this is something you've already done @wsmith-nwfsc, but might be useful for future implementations of drill.

https://drill.apache.org/docs/configuring-storage-plugins/#configuring-storage-plugins-with-the-storage-plugins-override.conf-file

**Comment by jimfellows-NOAA** [comment]
Created working copy on my machine.  Usage in production will have to be adjusted, but works for my purposes now.  Checked into GitLab at boatnet-internal/boatnet-reports/drill.

**Comment by wsmith-nwfsc** [comment]
Thanks, this will be useful. I've only configured this through the Drill Web UI.
