### ISSUE TITLE
Fix issues with Spark inferring schema of Couch JSON data

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1492]
Having problems with Spark inferring the schema of JSON files pulled from CouchDB, causing errors / missed data when transforming into Parquet.

Example issue below shows that in the wcgop-operations, spark is inferring that gearType is a string, not a structure object as it should be.  When tring to query gearType.description in Drill, I get null, not the actual description value.  Compare to intendedGearType, which is being correctly read:

![image](https://user-images.githubusercontent.com/57507677/78803724-31639b00-7974-11ea-9281-2bbd32187f26.png)

Going to attempt to use a sample dataset to build a schema and save it to a file, and then reuse the schema correctly.  Approach might also speed up the Spark portion of the ETL.

Something like...
- https://gist.github.com/giefferre/0998159953466b4273ec8f921d6dc773
- https://stackoverflow.com/questions/40957585/create-spark-dataframe-schema-from-json-schema-representation/40957586

**Comment by wsmith-nwfsc** [comment]
I'm looking in our bn-models project (boatnet-module repository) and I see that we didn't define it explicitly in ``gear-type.ts```:
```
// TODO interface definition

// from lookups
export type GearType = any;
```

This is the definition that wcgop-operation uses.

However, wcgop-trip.ts uses:
```
export interface WcgopTrip extends BaseTrip {
  gearType?: string;
```
So, I think the solution here is to fix the inconsistency. @NickShafferNOAA which record does your ETL use, should we just make gearType a string across the board?

**Comment by jimfellows-NOAA** [comment]
Haven't gotten to the official bottom of why spark is interpreting gearType as a string, as I see the data existing as a its own document in Couch:

![image](https://user-images.githubusercontent.com/57507677/80757678-5ff31280-8ae9-11ea-9493-e7714451c5ea.png)

My guess is there are a few instances where that's not the case, and the inconsistency forces spark to default to casting the val as a string.  I've been able to extract the "description" field out of there with: `regexp_extract(ops.doc.gearType, '(?<="description":").+?(?=\")', 0))`, hoping this goes away when our data starts to really take shape, but drill has some pretty good tools to handle situations like this too.

Only thing to come out of this is to remember to define that gear-type.ts interface and make sure it's used where needed @wsmith-nwfsc @NickShafferNOAA.
