### ISSUE TITLE
tripsApiBaseUrl on prod deployment not getting a value from authService

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1499]
![image](https://user-images.githubusercontent.com/38139361/79011647-52192580-7b19-11ea-9a81-0b6ade335a3b.png)

trips-api.ts has:
const jwt = authService.getCurrentUser() ? authService.getCurrentUser()!.jwtToken : '';

const tripsApiBaseUrl = authService.getTripsApiUrl() ? authService.getTripsApiUrl() : '';
const tripsApiUrl = tripsApiBaseUrl + '/api/v1/trips';
const catchApiUrl = tripsApiBaseUrl + '/api/v1/tripCatch';
const cruiseApiUrl = tripsApiBaseUrl + '/api/v1/cruise';

Looks like the tripsApiBaseUrl ternary is returning an empty string (it's not getting a value from authService.getTripsApiUrl()  )

**Comment by sethgerou-noaa** [comment]
seems to not get an initial value for a while, and eventually does.  Try replicating via an incognito window.

**Comment by wsmith-nwfsc** [comment]
Delayed with work on couchdb, should get to this this spring (barring other emergencies)

**Comment by neilriley-NOAA** [comment]
@wsmith-nwfsc Is there any chance you can bump this ticket on your priority list? the trip number is critical to our next phase of testing.  

cc @sethgerou-noaa

**Comment by neilriley-NOAA** [comment]
@wsmith-nwfsc Just wondering if you have a timeline on when this issue will be addressed? I think we need to push this up the priority list.

@sethgerou-noaa @BHHorness-NOAA

**Comment by wsmith-nwfsc** [comment]
Underway, hoping to have this sorted out today.

**Comment by neilriley-NOAA** [comment]
@BHHorness-NOAA & @wsmith-nwfsc this is the issue we need fixed ASAP
cc @sethgerou-noaa

**Comment by wsmith-nwfsc** [comment]
Roger, circling back to it now.

**Comment by neilriley-NOAA** [comment]
Thanks @wsmith-nwfsc

**Comment by neilriley-NOAA** [comment]
@wsmith-nwfsc Just wondering about the time frame on this fix? We are doing a demo for the EM folks at the Region on Wednesday. Will this be fixed before then?

**Comment by wsmith-nwfsc** [comment]
Yes, I'm working with Sara and Seth this afternoon to close it out. Will be sure to have it tested before Wednesday.

**Comment by neilriley-NOAA** [comment]
Sweet

**Comment by wsmith-nwfsc** [comment]
Some Dev Notes for this afternoon,

https://www.webapps.nwfsc.noaa.gov/observer-web/login

Seems to be successfully getting 
![image](https://user-images.githubusercontent.com/12972097/88578467-7849cf00-cffd-11ea-958d-3dce1bdecd8e.png)

from both my main browser and incognito windows

**Comment by wsmith-nwfsc** [comment]
- [ ] Fix apiURL to new domain

**Comment by wsmith-nwfsc** [comment]
Fixed a related issue during yesterday's meeting via https://github.com/nwfsc-fram/boatnet-module/pull/73. On target to get a fix for this out this afternoon.

**Comment by wsmith-nwfsc** [comment]
Testing what I think is the fix for this now.

**Comment by wsmith-nwfsc** [comment]
Fixed. @sethgerou-noaa this was a race condition in helpers/trips-api.ts where there were a bunch of const strings defined, based on calls to the bn-auth service which wasn't necessarily done with its required queries to get that info. I replaced with functions and the issue seems to be resolved. I've deployed the new observer-web via the usual jenkins build.

**Comment by neilriley-NOAA** [comment]
@wsmith-nwfsc thanks for fixing. I need to do more testing but so far so good in a couple quick tests. I was able to update an existing record and have it pull the tripid, add a missing trip and the Elogbook pulls data from trips page to the Elogbook.
