### ISSUE TITLE
Investigate evaluations modeling

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1518]
Looking into how evaluations will be modeled in CouchDB.  Currently used as a period over which debriefers review observer performance, Oracle data looks like it exists in OBSPROD.EVALUATIONS.

**Comment by melinashak-noaa** [comment]
Hi Jim, I've created a model in couch [here](https://github.com/nwfsc-fram/boatnet-module/blob/master/bn-models/src/models/_common/evaluation-periods.ts) and currently using this to store evaluation periods in couch. It's pretty up to date although I'm not using the tripIds field. Didn't realize there's one modeled in obsprod. If I'm missing anything that they already have then we can definitely look into adding it.

**Comment by jimfellows-NOAA** [comment]
Great, modeling makes sense to me.  Seems like it should be fairly simple to adjust if we need to going forward too.  Oracle data also has EVAL_STATUS and SIGNED_DATE included as well, so those could be potential attributes added to the model if we need them.

_Oracle Data Example_
| EVALUATION_ID| OBSERVER| EVALUATION_START|EVALUATION_END|EVALUATION_STATUS|SIGNATURE_DATE|DEBRIEFER|
| -------------:|-------------:| -----:|-------:|-------:|-------:|-------:|
|12345|JOHN SMITH|2/1/2020|2/29/2020|SIGNED|3/15/2020|JIM|
|12346|JOHN SMITH|3/1/2020|3/31/2020|AVAILABLE|NULL|JIM|
|12347|JOHN SMITH|4/1/2020|4/30/2020|NEW|NULL|JIM|

**Comment by jimfellows-NOAA** [comment]
Closing this, can make other issues if needed to address other eval modeling questions.
