### ISSUE TITLE
Create Zeppelin observer reports example

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1542]
investigate usage of the debriefers' observer evaluation forms to transfer aspects of that into a regular zeppelin notebook.  Have an example of the template debriefers use to log observer progress, will use that to start identifying possible ideas.

**Comment by jimfellows-NOAA** [comment]
Will look into using the evaluation data in Couch to create a report, kicking to new milestone.

**Comment by jimfellows-NOAA** [comment]
Have a working example with drop downs for observers activity and performace.  Would like to get some taxonomy related graphics, but will need to adjust parquet taxonomy data first.  Closing ticket with good v1 example.

**Comment by wsmith-nwfsc** [comment]
Awesome, I think the parquet file approach is going to be our best bet for queries that are fast enough. See notes on #1568
