### ISSUE TITLE
DW - migrate to new dev server

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#1544]
boatnet-internal ```#3```

**Comment by wsmith-nwfsc** [comment]
New PG12 server is up, so can continue with this

**Comment by wsmith-nwfsc** [comment]
Refactored the DW build to run in Docker.

**Comment by wsmith-nwfsc** [comment]
Working with IT on this new server, slow going with other DW updates taking priority. Hoping I can make the service run in a podman pod so we don't have this painful migration again.

**Comment by SaOgaz-NOAA** [comment]
I'm closing this ticket for now, we can open a new one when it comes time to get dev warehouse up and running again.
