### ISSUE TITLE
EM logbook field format

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1586]
@sethgerou-noaa Is there an option to reformat the entry fields of the EM logbook with something that is a little cleaner? Right now they are just a line and some of the formatting is off.  I was thinking about the fields you see in a lot of websites these days where the field has distinct boundaries.  See attached.  Just a thought.

![field format](https://user-images.githubusercontent.com/31421964/83170437-631df600-a0c9-11ea-9b7b-7d6bfe64caf6.JPG)

**Comment by sethgerou-noaa** [comment]
try reformatting fields to look like: 
![image](https://user-images.githubusercontent.com/38139361/83195763-98d5d580-a0ef-11ea-9d80-74ac1010f413.png)
