### ISSUE TITLE
Add trip waived or not covered flag to OTS

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1605]
@sethgerou-noaa @johnlafargue-noaa 

From @scottleach-NOAA email:

More thoughts on trip waived box. Only staff can waive a trip. Staff should be able to check this box while creating a trip and also mark it on a fisherman created trip. If a fisherman creates a trip and the trip comes back selected and then staff waives the trip we can't just change the trip to not selected we should have language that says trip selected, observer requirement waived. 

On Tue, Jun 2, 2020 at 3:27 PM Scott Leach - NOAA Affiliate <scott.leach@noaa.gov> wrote:
Neil,
I talked to LaFargue and the reason we are currently not using OTS for trip selection was concern over having real and test data in the system. 

Something we should also look into doing is adding trip waived or trip not covered box that can be checked by staff. As we are currently not covering any EM trips this would be useful.

**Comment by sethgerou-noaa** [comment]
staff button to waive the trip.  scott/john to provide dropdown options for waived reason.
user sees if trip is Waived (waived button?)

**Comment by sethgerou-noaa** [comment]
implemented
