### ISSUE TITLE
Huge lag when changing vessels under trips

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1608]
Whenever I try to select a new vessel the app takes several minutes to load
See vid, gave up before I finished recording
[https://share.icloud.com/photos/03iY6LmBQCAnHj4fP9DeuRFqw]

@neilriley-NOAA  @sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
Note: there was some failure of apple cloud yesterday around 7 pm est.  NO idea if that affected performance, but after leaving the app open all night on my iPad (and logged in) performance seems to be back to normal.  I click and things respond.

**Comment by neilriley-NOAA** [comment]
Good to know. I have been accessing from a Samsung s7 and my Dell laptop and have not had any performance issues. I am going to close out this ticket and we an revisit if the issue persists.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I don't have permission to close these. I will leave it to you
