### ISSUE TITLE
Trips: NEw Trip: Time selector

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1609]
This is horrible on an iPad.  I cant type, no scroll thing is displayed and I can barely access the up down arrows.  Flicking doesnt work if it was meant to. 
![image](https://user-images.githubusercontent.com/45770674/83581108-bee5e600-a4f2-11ea-87bd-306fa2877f43.png)
@neilriley-NOAA @sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
Note, using an iPad with a physical keyboard will test without keyboard too

**Comment by ericbrasseur-NOAA** [comment]
No change still horrible without keyboard.  Flick would be nice the Optecs time selector

**Comment by sethgerou-noaa** [comment]
look at other time picker components - this one isn't customizable.

**Comment by neilriley-NOAA** [comment]
I have never been a fan of this time picker either. would be good to see other options.

**Comment by sethgerou-noaa** [comment]
I've added an alternate time picker right below the old one - just refresh the page.
Note: I have it currently set to select minutes in 10 minute intervals, but could be 5, or 1 if we want.
Please take a look and let me know what you think.

**Comment by neilriley-NOAA** [comment]
We need to record the time down to the minute.

**Comment by ericbrasseur-NOAA** [comment]
Not liking this new one either![image](https://user-images.githubusercontent.com/45770674/83678848-3c613300-a593-11ea-972e-ef08691592a6.png)

It’s kinda weird

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa, @ericbrasseur-NOAA  Have you found any time selectors for the next version of OPTECS that folks have liked?

**Comment by sethgerou-noaa** [comment]
not really.  

Where date and time are entered together, the old style component with the up and down carats and the numbers in the middle is used, 
![image](https://user-images.githubusercontent.com/38139361/83683615-88fc3c80-a59a-11ea-9db8-bdfff5b0c7ff.png)

when it's time only, it's just a text box with a : mask. 
![image](https://user-images.githubusercontent.com/38139361/83683746-bc3ecb80-a59a-11ea-900a-3b5a2f9a124d.png)
(which of course we could do if we can't find a picker we like.)

**Comment by ericbrasseur-NOAA** [comment]
![image](https://user-images.githubusercontent.com/45770674/83690105-f9a85680-a5a4-11ea-96bc-d73f6530296d.jpeg)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the fix looks good to me. I was not bale to create multiple trips.

@ericbrasseur-NOAA  can you test this one again.
