### ISSUE TITLE
App stays logged in forever, security concern

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1610]
I stopped using the app yesterday and did not log out, this morning when I opened the app (pretty sure I left it open in the background) I was still logged in and able to navigate without entering my credentials again.  Note I am online.  THis could be a security issue.  OPTECS has the same behavior but is an offline app with no access to vessel information and on an encrypted secure device. 
@neilriley-NOAA 
@sethgerou-noaa

**Comment by sethgerou-noaa** [comment]
discuss with Will

**Comment by sethgerou-noaa** [comment]
Should be resolved with @wsmith-nwfsc 's updates to bn-auth.
