### ISSUE TITLE
Trip calendar cannot select following month even though some dates displayed

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1614]
![image](https://user-images.githubusercontent.com/45770674/83664995-a1ab2900-a57f-11ea-9757-291195b5908b.png)
In this image I wanted the trip to go to July 1, seems silly to not be able to select the dates while displaying them, either hide dates or allow to be selected.
@neilriley-NOAA @sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
Note I can advance to next month and select the 1st, and then it reverts to the same view with highlights

**Comment by sethgerou-noaa** [comment]
explore other scroll/picker options.

**Comment by sethgerou-noaa** [comment]
Found a flag that allows the selection of next month dates from the current month.

**Comment by neilriley-NOAA** [comment]
This is better, but only displays the a limited number of days from the next month. It would be nice if it displayed an additional week in the next month. Right now if I was going to have a trip end after Aug 1, you would still need to click on the next month.

![image](https://user-images.githubusercontent.com/31421964/86628578-f0811f80-bf7e-11ea-872a-77c9a5249c61.png)
