### ISSUE TITLE
Logbook capture

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1616]
Why is logbook capture not populated with available open or completed but not closed trips? If captain or anyone else is submitting a logbook image for a trip, why make them renter it?  Wouldn’t it be best to show what is expected?
@neilriley-NOAA 
@sethgerou-noaa

**Comment by sethgerou-noaa** [comment]
remove as menu option - add button on trips page - a way of submitting the details and logbook capture for a trip that was not properly entered into the app when it should have been.

**Comment by ericbrasseur-NOAA** [comment]
My suggestion would be to eliminate logbook capture and simp;y integrate in into trips.  Create rules in trips that prompt to close active and finished trips, while allowing new trips to be created .

**Comment by sethgerou-noaa** [comment]
logbook capture removed and replaced with log missing trip functionality on trips page
