### ISSUE TITLE
User config: what are toggles on bottoms in captain mode

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1617]
The toggles on the bottom of user config are active but do not seem to do anything. Not sure what they are or if they should be displayed when I am in captain mode.
![image](https://user-images.githubusercontent.com/45770674/83667017-a1605d00-a582-11ea-8a42-b23aaa0dff74.png)
![image](https://user-images.githubusercontent.com/45770674/83667038-a9b89800-a582-11ea-81a4-e46e23d2b42e.png)
@neilriley-NOAA 
@sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
Roger

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa This can be closed
