### ISSUE TITLE
Permits/vessels/fishery filters

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1619]
None of my assigned vessels have permits, but i would think that permits/vessels and fisheries should be linked.  I should not be able to enter a fishery I don’t have a permit for.  Is it possible to filter each vessel by their associated permits?  How does one add a new permit?
@neilriley-NOAA @sethgerou-noaa

**Comment by neilriley-NOAA** [comment]
@ericbrasseur-NOAA the EM permits are assigned to actual vessels in the EM fishery, so you won't see them. The permits for other fisheries are not linked to the vessels.  The intent is to only have trips logged in EM to start.
