### ISSUE TITLE
Elogbook: 0 persist when trying to enter numbers

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1620]
When I click on a field that requires a number but displays a default 0 or 00000 the zeros persist and require me to delete them or type after them.  I would expect them to disappear so I can type normally.
![image](https://user-images.githubusercontent.com/45770674/83668275-8a226f00-a584-11ea-8a6c-2a746399dee1.png)
![image](https://user-images.githubusercontent.com/45770674/83668305-91e21380-a584-11ea-8872-6cf6a1571ee3.png)
@neilriley-NOAA 
@sethgerou-noaa

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the zeros look like they are still there.

**Comment by sethgerou-noaa** [comment]
Please verify that you are seeing the latest version of the app - Trip # field should now read Trip # (read only)  If so, you should now Crew Size has no default 0 value to clear.  As for the Trip # 00000s - that's just a placeholder as fetching a new tripNum isn't implemented yet.  Needs some discussion re: whether the person completing the logbook would have access to an existing Trip #, would want to generate a new Trip #, or if both cases are true.

**Comment by neilriley-NOAA** [comment]
I didn't have the up-to-date version. works now
 the Trip # 00000s as a placeholder makes sense. agree this needs discussion
