### ISSUE TITLE
Elogbook: no connection to trips? Shouldn’t this pull data from trip selection so as not to duplicate work

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1621]
The elogbook book does not appear to be connected to vessel selection.  I would think that the trip tiles or list would be displayed by default so that the user could simply click on a trip and all those details were prefilled.
Will we connect these?
@neilriley-NOAA 
@sethgerou-noaa

**Comment by neilriley-NOAA** [comment]
Yes, these logbook will be joined to a trip. This is still under development.

**Comment by sethgerou-noaa** [comment]
this connection is now in place
