### ISSUE TITLE
Elogbook: Add Haul: Net details show after clicking away

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1622]
![image](https://user-images.githubusercontent.com/45770674/83668871-85aa8600-a585-11ea-8e60-19df2c994973.png)

Notice the gray text that should be associated with gear type.  Even though I move on to net type the gray text still persists.
Also, should net type be free field?
@neilriley-NOAA 
@sethgerou-noaa 
Source 1pad 13.15.5

**Comment by neilriley-NOAA** [comment]
@ericbrasseur-NOAA That grey text should not be there. gear type will be lookup lists. All lookup lists in the logbook are under review and incomplete.
