### ISSUE TITLE
Elogbook: Haul: Endtime autopopulated with start time

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1623]
When adding a new haul the end time is auto populated with the start time.  This will lead to errors.  The end time should be blank by default so a live data check can be triggered if left blank at save.
![image](https://user-images.githubusercontent.com/45770674/83669348-47619680-a586-11ea-9e86-1a94e2406d21.png)
@neilriley-NOAA 
@sethgerou-noaa

**Comment by sethgerou-noaa** [comment]
make departure and return dates default to blank

**Comment by sethgerou-noaa** [comment]
E-Logbook Dropdown Options Lists - Observer Target Codes
