### ISSUE TITLE
Logbook capture: no option to load from photos or a file

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1626]
Logbook capture is set up for live use only it seems.  I can see a captain taking a picture of the logbook so he could upload it at a later date.  Right now only a camera is allowed.  What if using a laptop with no camera and they want to upload from an imported file or elogbook?
@neilriley-NOAA 
@sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
@scottleach-NOAA @johnlafargue-noaa 
Hmm that seems very backwards thinking especially if we want to expand participation.  I can see users taking pics on there device to enter later.  The restriction of live picture only is limiting.  Users forget, do things out of order, leave the vessel etc.  seems wise to build it in now.

**Comment by neilriley-NOAA** [comment]
@ericbrasseur-NOAA sorry I had the wrong response earlier. we set this up to require an image to close a trip. If a captain closes a trip, he needs to upload a photo of the logbook. If the trip is closed by staff not image is required.

**Comment by sethgerou-noaa** [comment]
can now select a file or camera as image source

**Comment by sethgerou-noaa** [comment]
weird bug - think I have it fixed though
