### ISSUE TITLE
OTS - return port

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1627]
@sethgerou-noaa @scottleach-NOAA 

If "Same as Start" is select for the return port, the actual name of the return port should be displayed. Or just have them pick the return port by name.

**Comment by sethgerou-noaa** [comment]
change return to departure on departure selection.  then user can change return if necessary

**Comment by sethgerou-noaa** [comment]
changing departure port now automatically changes return port, unless return port was already changed to something different.
