### ISSUE TITLE
Able to submit the same trip multiple times and all instances show in list

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1628]
There was a delay in saving my trip entry and so I clicked save multiple times.  Each click was saved as the same trip number but multople times.  I suspect with a unique id for each
![image](https://user-images.githubusercontent.com/45770674/83671929-51859400-a58a-11ea-8cb3-3555545ea82c.png)
![image](https://user-images.githubusercontent.com/45770674/83671955-58aca200-a58a-11ea-95c1-89e6bb6e89af.png)
Will try to repeat.  To test, just click save several times when there is a lag.
@neilriley-NOAA 
@sethgerou-noaa

**Comment by ericbrasseur-NOAA** [comment]
Repeatable.  Just click submit quickly

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I was able to repeat this as well.

cc @scottleach-NOAA, @johnlafargue-noaa

**Comment by ericbrasseur-NOAA** [comment]
When this happens there are a few other bugs when trying to edit one of the trips.  Depart time is duplicated and some things cannot be edited.
![image](https://user-images.githubusercontent.com/45770674/83672989-053b5380-a58c-11ea-854e-fa22f16ff52a.png)
![image](https://user-images.githubusercontent.com/45770674/83673094-2e5be400-a58c-11ea-8ee3-4c0de185df14.png)
Second depart time is missing a digit.

**Comment by ericbrasseur-NOAA** [comment]
Recommend that to fix, prevent submit button from being clicked more than once until confirmation received.

**Comment by ericbrasseur-NOAA** [comment]
@johnlafargue-noaa @scottleach-NOAA 
FYI

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I would prioritize this one.
