### ISSUE TITLE
Trips: allow vessel capt to set a home port and default fisheries

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1630]
Would be nice if a captain could set a default port for new trips, maybe even default fisheries since they are often fishing the same for a while
@scottleach-NOAA 
@johnlafargue-noaa

**Comment by sethgerou-noaa** [comment]
We used to have this, but removed along with a bunch of user data in an attempt to store less PII.

@neilriley-NOAA what do you think about storing a home port (in user's person-alias doc) that depart and return port would default to?

**Comment by sethgerou-noaa** [comment]
actually, the default (departure + return) port is the vessel's home port (as configured in vessel management) - as long as this is set, should suffice.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa yes, I agree this should be set in the vessel management. The vessel's homeport exist in OBSPROD, so I assume this will be imported from Prod?

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA yes, what was in OBSPROD has been ETLed into Couch.  All real vessels should have a home port, which should be the default departure and return port.  (Test vessels may not have been created with a home port, so that could explain trips without a properly defaulted departure/return port)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  Looks like the ports are missing in vessel management.

![image](https://user-images.githubusercontent.com/31421964/84425207-085ec100-abd6-11ea-8fb0-5ded4ee60333.png)

**Comment by sethgerou-noaa** [comment]
looks like the table is displaying 'port', when it should be displaying 'Home Port'.  Correcting.

**Comment by neilriley-NOAA** [comment]
Looks good.
