### ISSUE TITLE
Single day trips: closing requires the same day be touched twice

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1634]
When closing a single day trip the calendar still requires a user to select a start and end date and is way not obvious.  User must click the same day twice to see the close button.  
For single day trips this should not be required.
Also I recommend not hiding the buttons.
@neilriley-NOAA 
@sethgerou-noaa 
@johnlafargue-noaa 
@scottleach-NOAA

**Comment by sethgerou-noaa** [comment]
add same day trip functionality
