### ISSUE TITLE
Close trip dialog: captain view: move buttons

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1636]
![image](https://user-images.githubusercontent.com/45770674/83683753-bf39bc00-a59a-11ea-8d62-621a60b5d416.png)
Since these buttons are on the bottom if the user adds an image(which is required for captains) the buttons are hidden at the bottom.  If they were in the top right or left the user would not have to scroll to find them.  I found this screen unintuitive.  
@scottleach-NOAA @neilriley-NOAA @sethgerou-noaa @johnlafargue-noaa

**Comment by neilriley-NOAA** [comment]
Yes I agree it is weird to scroll to have access to the buttons on the phone. Let's try moving them to the top of the screen.

**Comment by sethgerou-noaa** [comment]
add all buttons to the top ribbon of the dialog
