### ISSUE TITLE
Trip selection View error due to multiple submission?

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1637]
![image](https://user-images.githubusercontent.com/45770674/83684047-3a9b6d80-a59b-11ea-99b3-42f4cf2d59e6.png)
I am unsure if this view is as expected with no open trips.  I would think the next trip selection options would be blank if I had no upcoming trips.
@scottleach-NOAA @johnlafargue-noaa @sethgerou-noaa @neilriley-NOAA

**Comment by sethgerou-noaa** [comment]
not a bug - if trips for multiple fisheries are created, next selections for those fisheries are generated based on available rules - no fisheries other than EM EFP have selection rules.  Fishery has been limited to EM EFP only, so should not be an issue
