### ISSUE TITLE
EM EFP Permits data no longer visible

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1638]
@sethgerou-noaa @ericbrasseur-NOAA 

we created new EM EFP permits and now we can't see any data.

![image](https://user-images.githubusercontent.com/31421964/83687036-0d04f300-a5a0-11ea-915f-be0162df088f.png)

**Comment by sethgerou-noaa** [comment]
The trip was created without a gear type, and the UI can't handle currently (I added a gearType so you should be able to mess around more).

Leaving this ticket open to capture requirements:
A. require gearType, efpTypes and LE Permit for new EM EFP.
B. handle missing gearType , efpTypes and LE Permit when displaying EM EFP roster table.
