### ISSUE TITLE
Trip numbers missing

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1639]
@sethgerou-noaa  trip number should exist for all trips. 

![image](https://user-images.githubusercontent.com/31421964/83693627-4ee76680-a5ab-11ea-93cb-9f64c381f8b5.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA A trip number is now required to create a trip, and you should now see an error when the app can't get a trip number.  Would you please let me know if you get any of these errors?  And if you do, please log out and back in and see if the issue persists?  Getting these errors means the app isn't able to connect to the Trips API, which I believe means it's trying to log in with an expired JWT - if we can confirm that's what's happening for you, I'll create a separate ticket.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I got an error when I created a new trip. see screen shot below.

![image](https://user-images.githubusercontent.com/31421964/84415297-6b952700-abc7-11ea-85a1-ace5e1d08c22.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Thanks!  Do you get the same result after logging out and back in?

**Comment by neilriley-NOAA** [comment]
That is the error I got after logging out and back in.

**Comment by sethgerou-noaa** [comment]
@wsmith-nwfsc See Neil's screenshot from earlier today (not the original issue screenshot).
Obs-web prod is still sometimes not getting the correct TripsAPI url - issue #1499 - tripsApiBaseUrl on prod deployment not getting a value from authService

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  @wsmith-nwfsc wondering about a time frame on resolving the tripID error issue?  We are unable to create trips for testing, so we need to get this resolved.

**Comment by sethgerou-noaa** [comment]
@wsmith-nwfsc will need to speak to the timeframe to resolve the invalid trips api url resolution.
In the mean time, perhaps I should remove the warning so test trips can be created.

**Comment by neilriley-NOAA** [comment]
temporarily removing the error would be good.

**Comment by sethgerou-noaa** [comment]
turned off the warning - should be able to create trips without a valid trip number now.
