### ISSUE TITLE
New roles for users not saving

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1640]
@sethgerou-noaa  Trying to add the staff role & captain in User Management for @Jeibner-NOAA , but it is not saving from my end. He will need these roles for testing.

**Comment by sethgerou-noaa** [comment]
can you try logging out and back in then trying to set roles again?  You should be able to do this.

**Comment by neilriley-NOAA** [comment]
Logged out and back in and had the same issue. says it saved but did not.

**Comment by sethgerou-noaa** [comment]
@wsmith-nwfsc when the obs-web app tries to log in to apex-user-admin to update roles it's returning 'unauthorized'.  This is happening for Neil, but not for me.  Does a user need a specific apex-user-admin role to update other user's roles?

**Comment by wsmith-nwfsc** [comment]
Yes, the user requires certain roles to have access to this.
Venturing into security territory so I'll reference this in https://nwcgit.nwfsc.noaa.gov/fram-data/boatnet-internal/-/issues/6

**Comment by wsmith-nwfsc** [comment]
@neilriley-NOAA I've added the appropriate role to your account. Log out and back in again, and hopefully you'll have more luck!

**Comment by sethgerou-noaa** [comment]
Thanks @wsmith-nwfsc !

**Comment by neilriley-NOAA** [comment]
@wsmith-nwfsc works great!  Thanks.
