### ISSUE TITLE
Elog port code drop shouldn't display the state

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1647]
@sethgerou-noaa The port codes in the Elogbook don't need the state code listed for each individual port.

![image](https://user-images.githubusercontent.com/31421964/83916351-e70b5a00-a729-11ea-88cc-f3c1fde1ef1c.png)

**Comment by sethgerou-noaa** [comment]
oops, those were there just to verify my filtering by state was working - removing
