### ISSUE TITLE
searching drop down list

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1649]
@sethgerou-noaa Is it possible to have a search feature within a drop down list or must we always scroll? I am thinking about the longer look up list like Port Codes where it would be helpful to click in the field and be able to start typing the name of the field. Not sure if you have already answered this?

**Comment by sethgerou-noaa** [comment]
yep, will implement.  until a couple days ago, didn't realize how many ports there are.

**Comment by sethgerou-noaa** [comment]
implemented.
