### ISSUE TITLE
Editing maximized retention circumvents observer coverage

### ISSUE THREAD

**Issue by Jeibner-NOAA** [nwfsc-fram/boatnet#1654]
@sethgerou-noaa @scottleach-NOAA @neilriley-NOAA @ericbrasseur-NOAA 
I created a trip without maximized retention, and it was appropriately assigned observer coverage.  Then I went in to edit the trip by selecting "yes" to maximum retention, it correctly returned no observer coverage required. Then I edited it back to no maximized retention and it did not update to require observer coverage.

**Comment by ericbrasseur-NOAA** [comment]
Supper repeatable.  Edit any observer required em trip and change it to max ret and save it will drop observer then edit again to say no/dont know and it will stay dropped.

**Comment by Jeibner-NOAA** [comment]
Also, you can’t change it back so that it becomes an observer required trip.


On Jun 8, 2020, at 5:49 PM, Eric Brasseur <notifications@github.com> wrote:

﻿

Supper repeatable. Edit any observer required em trip and change it to max
ret and save it will drop observer then edit again to say no/dont know and
it will stay dropped.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nwfsc-fram/boatnet/issues/1654#issuecomment-640962614>,
or unsubscribe
