### ISSUE TITLE
Departure date after return date

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1662]
@sethgerou-noaa Departure date is after the return date. Not sure how I did this exactly other than it was thru a combination of editing the trip.

![image](https://user-images.githubusercontent.com/31421964/84201096-9e6edc00-aa5c-11ea-92f9-057a97d514aa.png)

I think @johnlafargue-noaa & @ericbrasseur-NOAA had the same issue.

**Comment by sethgerou-noaa** [comment]
@sethgerou-noaa make sure tripdates watcher is clearing out both start and end date every time a new range is selected.
