### ISSUE TITLE
Parameterize all-operations-flat & all-trips Couch views to return year-specific results

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1670]
Would be good to consolidate things such as all-operations-flat-2017, all-operations-flat-2018, and all-operations-flat-2019 into all-operations-flat, and then use startkey and endkey to specify the years desired when retrieving data.  

Current view:
```
function(doc) {
    if (doc.type == "wcgop-trip" && doc.returnDate.substring(0, 4) == "2017") {
        emit([doc._id, 0], null);
        if (doc.operationIDs) {
            for (var i in doc.operationIDs) {
                emit([doc._id, Number(i)+1], {_id: doc.operationIDs[i]});
            }
        }
    }
}
```

**Comment by wsmith-nwfsc** [comment]
Good idea. 
I did that for trips and operations in my test DB (might need to handle missing createdDate instance or pull from elsewhere though, not a foolproof view!)
```

function(doc) {
    if (doc.type == "wcgop-operation" && doc.createdDate) {
        emit(doc.createdDate.substring(0, 4), doc.createdDate);
    }
}

function(doc) {
    if (doc.type == "wcgop-trip" && doc.returnDate) {
        emit(doc.returnDate.substring(0, 4), doc.returnDate);
    }
}
```

**Comment by jimfellows-NOAA** [comment]
Just reread your email where you said you did this already, thanks for the heads start!  Really like the idea of not having one view per year.

**Comment by jimfellows-NOAA** [comment]
Trips by year was pretty straight forward:

```
function (doc) {
  if (doc.type == 'wcgop-trip' && Date.parse(doc.returnDate)) { 
    emit(parseInt(doc.returnDate), doc._rev);
  }
}
```

Trying to get something similar with operations, that references the trips return date:

```
function(doc) {
    if (doc.type == "wcgop-trip" && Date.parse(doc.returnDate)) {
        emit([Date.parseInt(doc.returnDate), 0], null);
        if (doc.operationIDs) {
            for (var i in doc.operationIDs) {
                emit([doc._id, Number(i)+1], {_id: doc.operationIDs[i]});
            }
        }
    }
}
```

This may not be that relevant if we're just replicating all of the master couch database into mongo, so won't spend too much time on this for now.

**Comment by jimfellows-NOAA** [comment]
Got operations + trips working with yearly param, linked docs ordered by composite key [year, _id, int]. Will see how limiting by year works within NiFi:

```js
function(doc) {
    if (doc.type == "wcgop-trip" && Date.parse(doc.returnDate)) {
        emit([parseInt(doc.returnDate), doc._id, 0], null);
        if (doc.operationIDs) {
            for (var i in doc.operationIDs) {
                emit([parseInt(doc.returnDate), doc._id, Number(i)+1], {_id: doc.operationIDs[i]});
            }
        }
    }
}
```

Query with start and end key: `https://nwcdevfram2.nwfsc2.noaa.gov:6984/master-dev/_design/MainDocs/_view/operations-flat-by-year?include_docs=true&startkey=[2019]&endkey=[2019, {}, {}]`
