### ISSUE TITLE
Investigate how edge case species are grouped for in-season IFQ vessel accounts

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1684]
Some questions to answer:

- How do we know that a rockfish species is nearshore, south slope, etc when recorded?  Is this from the catch category used?
- How are Chilipepper, Blue/Black Rockfish grouped?  These may have weird delineations that follow state boundaries, not those that align with "Fishing Areas", 100, 200, 300 400)

Going to find examples of these and follow the data from entry into OBSPROD to transformation into expansion tables.

**Comment by neilriley-NOAA** [comment]
@jimfellows-NOAA 

For IFQ species reporting to the vessel accounts the rockfish species nearshore, south slope, shelf, etc grouping designation is based on the correlation to the IFQ_SPECIES_GROUP_ID in the IFQ_SPECIE_GROUPINGS table. The retrieval latitude in the observer data determines the IFQ management area. 

Similarly, Chilipepper RF is reported independently in the vessel accounts. You can refer to the IFQ_SPECIE_GROUPINGS table to see how all the species correlate the appropriate IFQ area. For IFQ we don't care how these species have other state boundaries that are defined for other management areas.

**Comment by jimfellows-NOAA** [comment]
hey @neilriley-NOAA, just starting to dig through some examples.  Looking at an example of how NSLP is reported as an example, looks like usually when NSLP is specified by the observer, a species comp. record is not recorded.  Is that correct?  There are a few instances where NSLP is used, and a rockfish species comp is also recorded, but it's the minority.

After looking into these shelf/slope specific categories, I was wondering how an observer determines which catch category to use. My assumption is they don't know that they're in a "Minor Slope" or "Minor Shelf" area, or maybe they do?  For example, Splitnose has its own category, SNOS.  Based on the IFQ_SPECIE_GROUPINGS table, looks like Splitnose discard will be categorized as "Splitnose rockfish" in areas 200, 300, and 400, but "Minor Slope Rockfish North" in fishing area 100.

How does the observer know when to use NSLP vs SNOS vs URCK for a given situation?

Still wrapping my head around this, hope that makes sense.

**Comment by neilriley-NOAA** [comment]
The observer doesn't know what IFQ category to put it in or whether is reported to the VAS in a category or as an individual species. They just report the species and the correlation to the IFQ grouping and management area is done in the  WCGOP_IFQ_RECEIPTS_XML package. 

Just to be clear the IFQ_SPECIES_GROUPINGS only apply to Catch Shares and EM.

The Catch Shares fishery has specific protocols so they rarely or shouldn't use those group categories for slope or shelf categories. I need to confirm that. If they did use a catch category code like NSLP or URCK, it wouldn't get recorded as and IFQ species. In Catch Shares, they would use IFQM, IFQRF, IFQFF, etc and then the code in WCGOP_IFQ_RECEIPTS_XML package would calculate the IFQ species for that category using the rockfish species found in the other hauls within the trip.

**Comment by jimfellows-NOAA** [comment]
Looking at Catch Shares data for 2019, I do see NSLP, SSLP, and NSLF CCs used, although its primarily for Retained estimates.  I didn't see IFQRF used at all.  I'm guessing that for discarded samples observers typically use ZMIS, and then specify the actual species in the species comp, or they use the rockfish-specific CC (e.g. SNOS for Splitnose).  Either way, the IFQ_SPECIE_GROUPINGS and the XML package then together do the translation into the expansions for the relevant IFQ management groupings.

My hope is to build something similar in Couch where latitude and taxonomy / catch grouping (TBD on what these will actually be) can be used to translate to an IFQ management grouping.  But I'll have to figure out how replacing Catch Categories with Catch Groupings will function here.  

Reading through the appendix section on Rockfish codes was helpful here for me:
![image](https://user-images.githubusercontent.com/57507677/84922117-464a6200-b07a-11ea-95bc-01745f22b65e.png).  Seems like if observers use these NSLP, SSLP, SSLF categories in IFQ fisheries, they are aware of the region that they're in, and use them accordingly.

**Comment by neilriley-NOAA** [comment]
@jimfellows-NOAA Observers aren't supposed to use these categories for discard in Catch Shares except in rare instances. This was confirmed by @Jeibner-NOAA (see comments below).

That said, we will need to discuss the use of IFQM, IFQRF, IFQFF, IFQRD later to today. Observers only use IFQM right now. This is a length discussion we can have later.

from Eibner email. 
_Yes, these are typically retained catch categories used by the vessel to describe what they kept.  The observers are trained to note the rockfish species that were retained under these C.C.'s and document them in their data as specific species catch categories with their own independent estimate rather than use the vessel's NSLP, SSLP, or NSLF estimate.  However, there are times when the observer fails to note the species so we are forced to keep it as the vessel's aggregate rockfish C.C.  

I don't see these used as discarded catch categories.  If the observer took a sample for species comp, the catch category would be ZMIS, not one of these.  And if they only did visual estimates, species specific catch categories should be used.  It probably does happen for discard, but it shouldn't, and it would likely get switched to a more specific catch category._

**Comment by jimfellows-NOAA** [comment]
Wrapping up this ticket.  Takeaways:

- SSLP, NSLP etc groupings do not depend on the latitude/depth fish is caught.  A NSLP species will be categorized this way regardless of where caught
- IFQ account system always uses fishing area values.  Couch can use latitude to be more flexible, but we'll still need to report final numbers grouped by fishing area values
- Translation from catch category / species to IFQ groups is done entirely by IFQ_SPECIE_GROUPINGS and WCGOP_IFQ_RECEIPTS_XML.  
- Observers may use IFQM (IFQ mixed), and the XML package will extrapolate using other hauls to divide the weights to more specific categories (more details exist within the code of the package)

While catch categories are going away, I'm guessing things like IFQM will still be used in the field, and therefore we'll still need to have similar extrapolating functions built in the new system.  The IFQ_SPECIE_GROUPING translation to IFQ groupings will also need to be re-created using taxonomies / catch groupings.
