### ISSUE TITLE
close trip button not available after adding image

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1701]
@sethgerou-noaa 

After adding an image to a single day trip, the close trip button was not available and was unable to close the trip

![Screenshot_20200623-105247_Chrome](https://user-images.githubusercontent.com/31421964/85437872-1ef30980-b540-11ea-919f-a91b83f008e9.jpg)

**Comment by sethgerou-noaa** [comment]
did you set the 'Actual Trip Dates' on the calendar?  (You still need to confirm a start/end date for the trip with a single day trip - though you just click one date on the calendar)

**Comment by neilriley-NOAA** [comment]
Oh duh. No I didn't. If someone navigates away without selecting the trip dates. they have to start over. do you think it would be worth having a warning to remind them.?

@ericbrasseur-NOAA  what is your take?

**Comment by ericbrasseur-NOAA** [comment]
I was of the mind to preload the trip dates and ask if they were different.  Could present them as a pop up with start and end as separate entries so you can just click the one that was wrong and confirm if no change

**Comment by sethgerou-noaa** [comment]
The other way I could see doing this - rather than disabling the close trip button, the button could warn + not continue if confirmed dates have not been selected.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa can we try your suggestion. Is that a bigh left to try out?

@ericbrasseur-NOAA  I think @scottleach-NOAA  wanted them to reenter the dates. If they were pre-loaded, they may just hit enter to whatever the preloaded date is.  Scott is that right?

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA sure, that's a pretty straightforward change.
