### ISSUE TITLE
Move docs from CouchDB directly into MongoDB with Apache NiFi

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1703]
Currently have Apache NiFi set up to retrieve documents from CouchDB REST API and insert directly into a local instance of MongoDB.  However, the view result retrieved is inserted into Mongo as a single document.  Would like to access the "rows" array result of a couch view and insert each doc in the rows array as its own individual document under a common collection.  Should be able to do this all in Apache Nifi.

_Current State (All trip docs mashed into single parent document):_
![image](https://user-images.githubusercontent.com/57507677/85570042-e6a70600-b5e7-11ea-914f-8ca6b7f9d364.png)

_Desired State (Each trip doc exists independently under collection, might want to unnest "doc" here too):_
![image](https://user-images.githubusercontent.com/57507677/85570147-f9213f80-b5e7-11ea-940b-ef286a4dcbd6.png)

@wsmith-nwfsc let me know if you've already figured this one out.  Trying to bypass dumping couch results to JSON before inserting into Mongo, and get an environment to play around with on my local machine...

**Comment by wsmith-nwfsc** [comment]
Haven't looked too closely into this yet, but I suspect there's a standard way to do it possibly with RecordProcessor

**Comment by jimfellows-NOAA** [comment]
NiFi has some pretty good JSON manipulation functionality built in.  Used the JoltTransformJSON processor to manipulate the Couch response to get it ready to go into mongo:
![image](https://user-images.githubusercontent.com/57507677/85594110-7d7dbd80-b5fc-11ea-9b1b-a930f16a153b.png)

Don't entirely understand how the Jolt tool works, but here's how it gets the docs out of the rows array and into its own array:
![image](https://user-images.githubusercontent.com/57507677/85594424-c6357680-b5fc-11ea-95b0-eef3ce4b03dc.png)

Got things inserting document by document, but getting errors with larger bulk processes, i think due to schema inference.  E.g. the first trip document doesn't have a "captains" attribute, but the third one does, and either mongo or NiFi isn't happy when it sees that new field.

**Comment by wsmith-nwfsc** [comment]
When I imported into mongo, I just used https://github.com/wsmith-nwfsc/couchdb-dump and then I used the mongoimport command line tool, which worked smoothly without schema errors (7 GB imported in 3 mins.) So hopefully we can get it into mongo without too much stuff breaking.

**Comment by jimfellows-NOAA** [comment]
7GBs in 3 mins sounds nice, things are working pretty well with Nifi straight into Mongo with that schema issue resolved, but its really slow when doing stuff with JSON for large requests even under a GB.

**Comment by wsmith-nwfsc** [comment]
If it works, then I'd prefer slow but with Nifi. How long do you think it'd take for the whole DB? (I guess ideally we'd only need to do it once,  then update only on new revs after that?)

**Comment by jimfellows-NOAA** [comment]
Hmmm yea if we could figure out how to only do updates then speed wouldn't matter as much, assuming we can't get NiFi working a little faster.  The record by record NiFi to Mongo processor has update capabilities, the bulk insert doesn't.  I'm still stumbling my way through using it, right now I'm getting a java OutOfMemory error when trying to manipulate each JSON object in an array before inserting to Mongo, probably could be done a better way.  The actual insert into Mongo and pull from Couch don't seem to be the bottleneck yet...

I've been attempting to insert each document type to its own Mongo collection in an attempt to be more organized, AKA the wcgop-trip docs go to a trips collection.  Might not be necessary, I'm assuming the couchdb-dump into Mongo via mongoimport just throws all docs into a single collection.

**Comment by wsmith-nwfsc** [comment]
I got this working (to some degree) over the weekend, will tag up with you

**Comment by jimfellows-NOAA** [comment]
Been able to create loops in NiFi with incremented parameters, not exactly sure how that would work for pagination.  I've had success setting a start year attribute, using a While loop to increment the year, and then using the year as a key against the Couch trips-by-year view:

**Comment by jimfellows-NOAA** [comment]
Have NiFi getting both trips and operations from couch and inserting into separate mongo collections. Takes under a minute to get 3yrs of trips data moved over, maybe 10-15 minutes to get 3yrs of operations data.  Also replaced the trips parent data in the operations-flattened view with a tripId, should streamline things a bit:

![image](https://user-images.githubusercontent.com/57507677/87356983-f1362a80-c517-11ea-8612-b46679e6a22a.png)

Steps for operations flow:
1. GenerateFlowFile: {} as flow file body (AKA delete * for mongo collection) and start and end year attributes.
2. DeleteMongo: Clear out docs from mongo collection using {}
3. UpdateAttribute: Create new flow files eac with incremented year
4. UpdateAttribute: update couch URL with incremented year
5. InvokeHTTP: Get response from couch: `https:couchdev/master-dev/_design/MainDocs/_view/operations-flat-by-year?include_docs=true&startkey=[${incrementedYr}, 1]&endkey=[${incrementedYr}, {}]`
6. SplitJSON: Extract each doc from $.rows from http response
7. JoltTransformJSON: Extract "doc" and tripId from each JSON object from split array.

```js
[{
	"operation": "shift",
	"spec": {
      "doc": [""],
      "id": "tripId"
    }
}]
```

8. PutMongo: Insert each extraction to Mongo collection

Planning on creating other flows for smaller document datasets (e.g. ports, programs, taxonomies, etc).  Could be a process we could perform on Old Ironsides @wsmith-nwfsc?  Or, one day, New Ironsides!

**Comment by wsmith-nwfsc** [comment]
Awesome, this is amazing. I feel like this should go into a team SOP for Apache Nifi doc.

**Comment by jimfellows-NOAA** [comment]
Just so I don't lose this, here's a jolt expression that upacks view results from Couch, relables _id as CouchId, and removes the old _id for mongo purposes:
```
[{
	"operation": "shift",
	"spec": {
		"rows": {
			"*": {
				"doc": "[]",
				"id": "[&1].couchId"
			}
		}
	}
}, {
	"operation": "remove",
	"spec": {
		"*": {
			"_id": ""
		}
	}
}]
```
