### ISSUE TITLE
test: ots trips global search shaded differently (to stand out from background)

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1724]
@ericbrasseur-NOAA 
please confirm the field stands out better now.

addresses #1716

**Comment by ericbrasseur-NOAA** [comment]
Subtle but there.  Bit weird that the word global search doesn’t disappear when selecting the box.

**Comment by neilriley-NOAA** [comment]
You could also define the area where to type for the search where is a distinct box instead of a line. Same thing we did in the E-logbook screen.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa The Global Search field doesn't appear to have any defined boarder yet.


![image](https://user-images.githubusercontent.com/31421964/86944608-d8cfa580-c0fc-11ea-9c3f-516040d87bde.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA please try refreshing your browser.  CTRL + Shift + R on Chrome on PC.

should look like this now:
![image](https://user-images.githubusercontent.com/38139361/86948166-9ceb0f00-c101-11ea-9525-5f19e1f96130.png)

**Comment by neilriley-NOAA** [comment]
Refresh didn't do anything. Have logged out and logged back in as well.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Huh, that's really weird.  Would you please try again now?

**Comment by neilriley-NOAA** [comment]
no luck. 
![image](https://user-images.githubusercontent.com/31421964/86955113-ee000080-c10b-11ea-8ac3-02f43ad3a0bc.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @ericbrasseur-NOAA Ah, now I see, you both were looking at ALL Trips (which does still need the update), while I had updated OTS Trips - not the same page.  Fixing All Trips now.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @ericbrasseur-NOAA I've updated All Trips with the updated Global Search box.  Would you please confirm you're seeing the changes?  Thanks!

**Comment by neilriley-NOAA** [comment]
Looks good.
