### ISSUE TITLE
Trip API - "Fisheries" field

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1739]
@sethgerou-noaa 

I just want to confirm the "fisheries": [  "string" ] in the Trips API maps to the 'Fishery" field in the Elogbook.  Do I have that right? If so thinking we should change the API from "fisheries" to "fishery"

![image](https://user-images.githubusercontent.com/31421964/86827743-3c979700-c047-11ea-927b-e98ccdb37f50.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA you're absolutely right.  Change made in swagger and updated in TripsApi.
