### ISSUE TITLE
test: global search on ots trips page - bordered in an attempt to make it stand out more

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1743]
@neilriley-NOAA please confirm whether the global search field stands out from the table sufficiently on the ots trips page.

addresses #1724

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa It doesn't appear to have any defined boarder yet.

![image](https://user-images.githubusercontent.com/31421964/86944608-d8cfa580-c0fc-11ea-9c3f-516040d87bde.png)

**Comment by neilriley-NOAA** [comment]
Ignore previous comment. I commented on wrong ticket. I am closing this.
