### ISSUE TITLE
test: missing capture icon, and x number of closed trips are missing a logbook image warning

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1745]
@neilriley-NOAA 

please confirm the missing image icon in closed trips table and cards, and the x trips missing capture warning are as expected.  Let me know if language can be improved.

addresses #1704

**Comment by neilriley-NOAA** [comment]
the warning, icons and counts are functioning correctly. deleting an image from a closed trips is reflected in the warnings and counts. 

@scottleach-NOAA @ericbrasseur-NOAA  can you guys test the trip closure functionality to double check this is working.
