### ISSUE TITLE
EM - Add column to "All Trips" to show who created the trip

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1752]
@sethgerou-noaa Add column to "All Trips" to show who created the trip.  Not sure if this is possible, but I would think it could be useful.

cc @scottleach-NOAA @johnlafargue-noaa

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Added.  Let me know if you want to move it to the  end, and whether created date would also be useful.

**Comment by neilriley-NOAA** [comment]
I like it. can we move it to the last column to the right and yes, i think created date would be useful. users can hide these if they don't want to see them.

**Comment by sethgerou-noaa** [comment]
Done.  Also moved both created fields on Ots Trips table to end cols.

**Comment by neilriley-NOAA** [comment]
Perfect.
