### ISSUE TITLE
OTS - Unable to enter missed trip

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1754]
@sethgerou-noaa unable to enter a missed trip on my phone. after selecting an image to submit for an unlogged trip, nothing happens when I click the _Submit Images_ button. The app just hangs.

Also, per @scottleach-NOAA when adding a missed trip, the logbook image capture should be required for fishermen, but NOT required for staff.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA This is due to the TripsAPI url issue - you can't submit a missed trip without a valid TripsAPI tripNum as there's no other opportunity for a missed trip to get a valid tripNum.

@scottleach-NOAA would staff ever add an image capture, or would it be reasonable for missed trip to ask a captain for an image, but not ask a staff member?

**Comment by neilriley-NOAA** [comment]
ah. that's right. I have asked @wsmith-nwfsc to fix that TripsAPI url issue. hopefully, that moves up hi priority list.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I think a staff member could enter an image but should not be required. If staff had the image they could enter it. The more likely scenario may be for a staff to ask the captain to submit it or if the image was sent to the Third Party EM provider. Since providers will be transcribing and submitting the logbook data, I would think a provider may get the image first. 

@scottleach-NOAA

**Comment by neilriley-NOAA** [comment]
Also, can you re-format the date/time display (see screen shot) so it is a little more user friendly. 

![image](https://user-images.githubusercontent.com/31421964/87174508-1adb2180-c28c-11ea-9797-416278ee8f71.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA formatted date/times to be more friendly/readable.  Also created a (staff only) button that allows a missed trip to be submitted without an image.
