### ISSUE TITLE
WARNING: 3 closed trips are missing logbook image(s). Please correct as soon as possible.

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1756]
When this notice is displayed, it would be nice if those trips were displayed under it by default or colored to match the warning in the closed trips list.   I also notice that there are more than 3 trips with the little ! indicating no logbook image. Not sure which ones satisfy the warning or why it was triggered for some and not others.

@neilriley-NOAA @johnlafargue-noaa @scottleach-NOAA @sethgerou-noaa 
<img width="1291" alt="Screen Shot 2020-07-09 at 3 49 30 PM" src="https://user-images.githubusercontent.com/45770674/87098567-7362de00-c1fc-11ea-891c-dd76a853523e.png">

**Comment by ericbrasseur-NOAA** [comment]
Makes a little more sense in table mode.  I can see the 3 in-question now.
<img width="1291" alt="Screen Shot 2020-07-09 at 3 55 07 PM" src="https://user-images.githubusercontent.com/45770674/87098620-94c3ca00-c1fc-11ea-9f8f-a39d1ef7a971.png">

**Comment by sethgerou-noaa** [comment]
@ericbrasseur-NOAA closed trip cards are now red if they're missing a logbook image.  Also removed the ! icon from cancelled trips - as  cancelled trips won't have logbook data.
