### ISSUE TITLE
Unable to enter missing trip

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1772]
@sethgerou-noaa  Unable to enter a missing trip for a new vessel. Nothing appears to happen when I try to submit the image or if I click the submit without image button.

![image](https://user-images.githubusercontent.com/31421964/88236365-ae6c0500-cc31-11ea-8882-29dd49b490da.png)

**Comment by sethgerou-noaa** [comment]
I believe this is due to that pesky tripsApi URL issue.  @wsmith-nwfsc is actively working on it.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I was hoping that was fixed. @wsmith-nwfsc Can you put this at the top of your list to fix?
