### ISSUE TITLE
Can't submit missed trip from iPhone

### ISSUE THREAD

**Issue by johnlafargue-noaa** [nwfsc-fram/boatnet#1779]
Title says it all. Scott was able to from his iPad and both of us were able to do it from a computer.  The submit button changes color slightly like it's working but nothing happens. I tried without a photo and with.

**Comment by neilriley-NOAA** [comment]
@johnlafargue-noaa This may be the same issue I had yesterday entering a missed trip from my desktop. @sethgerou-noaa mentioned it was due to the TripAPI bug.
