### ISSUE TITLE
descriptions of icons 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1806]
@sethgerou-noaa create description of each icon when the mouse is hovered. this exists for logbook, but missing for the image present and image missing icons. wondering if we should have a legend somewhere?

![image](https://user-images.githubusercontent.com/31421964/88749529-5426e480-d108-11ea-80af-095d49a7c9c6.png)

**Comment by sethgerou-noaa** [comment]
added descriptions for icons - will remember icon legend for when we create the EM manual
