### ISSUE TITLE
New date time picker

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1808]
Some issues
When selecting time use must tap elsewhere to close it, add ok or something as this method is non intuitive and sometimes creates errors

Changing the beginning date resets everything
I can see a trip departure date changing without the end date changing and visa versa.  Very annoying. 

I still hate the time picker.

**Comment by sethgerou-noaa** [comment]
switched to auto-close on input - setting hours and minutes requires clicking in twice - if using the picker, but seems preferable to clicking outside the picker to close.

Changing the beginning date does not change the end date unless the new beginning date is after the previous end date.

Still keeping an eye out for a better time picker but have not found one.
