### ISSUE TITLE
test does creating multiple (3+) missed trips bog down the app?

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1810]

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I was able to create 4 missed trips, each with a logbook image, without experiencing any noticeable slowdown - perhaps it was an internet fluke?

**Comment by neilriley-NOAA** [comment]
I think this was a local issue at the time.  I have since been able to add multiple trips.
