### ISSUE TITLE
departure time on a closed trip isn't showing up

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1824]

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the departure time is hardly visible

![image](https://user-images.githubusercontent.com/31421964/90177726-ce3da700-dd5f-11ea-8434-b9328b758336.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA  oh, weird.  I fixed an issue where the time didn't show up on a closed trip card.  Didn't realize it was hard to read in trip details as well.  Should be fixed now.

**Comment by neilriley-NOAA** [comment]
That is a lot better. Thanks for fixing.
