### ISSUE TITLE
unable to log in to observer-web

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1831]
![login issue](https://user-images.githubusercontent.com/38139361/89236541-b9b21f80-d5a5-11ea-858c-1a3115f2db2d.JPG)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I am having this same issue.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Well carp!  what OS / browser?

**Comment by neilriley-NOAA** [comment]
It was on my android phone. I am able to login on my desktop.

**Comment by neilriley-NOAA** [comment]
![image](https://user-images.githubusercontent.com/31421964/89660020-95945e00-d885-11ea-942d-7aa591642682.png)

**Comment by sethgerou-noaa** [comment]
resolved
