### ISSUE TITLE
Selective Discards

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#1836]
Selective discards are allowed based on the rules set out for each vessel in their Vessel Monitoring Plan.
Selective discards should always be reported to species in the logbook. In EM, selective discards are
generally identified to species, however some fish can only be identified to a group level (e.g. mixed
rockfish or mixed thornyheads). In these cases, the discard weight is apportioned among IFQ categories
based on the ratio of fish from that group in the logbook.
Example:
 Logbook reports 5 pounds Dover Sole and 5 pounds English Sole discards
 EM reports 20 pounds Unidentified Flatfish discards
 EM discards are split 50 %Dover/50% English per the logbook ratio
 Final EM record is 10 pounds Dover Sole and 10 pounds English Sole discards
Whenever possible, the logbook ratio from the same trip is used, however if no species from that group
were reported in that logbook, a ratio from all trips from that vessel or from that fleet in the previous
year is used.
https://docs.google.com/document/d/18PHojNA2BWpVVmYfLj0OKMicnKr3ZRiI9hF8MO9W0Ds/edit?ts=5f29dd7e#

**Comment by neilriley-NOAA** [comment]
Link to the OFLT calc details: [OFLT calc](https://docs.google.com/spreadsheets/d/10btqj4fHWcjBeWWP8LSegV8R8vhyUL4Y/edit#gid=574788931)

OFLT exmaple data to test api: https://docs.google.com/spreadsheets/d/1aQ278AaN8Nmk25KPkQEGW6vPxJoE_6Jl/edit#gid=420592971
