### ISSUE TITLE
Knock out some Python survey issues!

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1837]
Gonna start with https://github.com/nwfsc-fram/pyFieldSoftware/issues/78

**Comment by jimfellows-NOAA** [comment]
Sara resolved issues related to QtQuick.Controls 2.2 not working and notes dialog saving issues in Hook & Line, resolved with PyQt 5.9, and probably some others.  I worked on issues #43 and #123 and fixed #42, along with some other stuff.

Closing ticket and starting new one for the next sprint: [1887](https://github.com/nwfsc-fram/boatnet/issues/1887)

**Comment by SaOgaz-NOAA** [comment]
I closed 96, and 78
