### ISSUE TITLE
Catch API - how to identify a lost codend

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1840]
@sethgerou-noaa @melinashak-noaa 

Currently in the API we have a couple of fields to identify lost gear. 
 "gearPerSet": 0,
      "gearLost": 0,
      "avgHooksPerSeg": 0

I see these related more to FixedGear lost hooks or pots. Could the gearLost field be used for a lost codend as well or do we need to create a new field to identify the lost codend?  I am thinking the later? For reference: In observer data we identify a lost codend via the "gear Performance" field.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I think I prefer the latter - let's make an explicit lost codend attribute so it's easier to detect/expand.  

Should it be isLostCodend: boolean = true, or could there be more than one lost codend per haul?  so... lostCodends: number = 3

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa it is only possible to lose 1 codend per haul so a boolean would work.  Maybe name the column isCodendLost: boolean = true.

**Comment by sethgerou-noaa** [comment]
OK, cool.  I'll add to the api and the logbook.

**Comment by sethgerou-noaa** [comment]
isLostCodend added to API and E Logbook
