### ISSUE TITLE
dupe trip number

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1844]
@sethgerou-noaa 

Some how I got a dupe trip number when I entered a missing trip (100206). When I entered the missing trip it was taking a long time for the image capture to submit. I think I hit submit a couple of times. 

![image](https://user-images.githubusercontent.com/31421964/90179720-bca9ce80-dd62-11ea-8340-691e8893af3a.png)

**Comment by sethgerou-noaa** [comment]
prevent double submission of missed trip

**Comment by sethgerou-noaa** [comment]
implemented fix.  added to testing ticket.

**Comment by sethgerou-noaa** [comment]
double submission appears fixed.  intermittent inability to submit images appears to be related to trips api race condition
