### ISSUE TITLE
trips with same date and time

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1854]
@sethgerou-noaa I was able to create 2 trips same date and same time. This should not be allowed.

![image](https://user-images.githubusercontent.com/31421964/90561073-fc065f80-e154-11ea-9eb6-d452b49c9224.png)

cc @scottleach-NOAA

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I believe this is only possible when the start and end date of both trips are the same.

The challenge is, it's valid to have a single day trip start on the same day another trip ends, so I can't prohibit starting the second trip on that day.  I believe it's even valid to have 2 single day trips occur on the same day.

I've built a validation that requires the start time of the second trip to be later than the hour of the departure time, but as we don't ask for the return time during trip creation, this is an imperfect solution.

So... if trip 1 is 8/18 1:00 - 8/18, and trip 2 start date is 8/18 (regardless of end date), only the hours of 2 and beyond are available to choose from in the time picker.  Does that work?  It would prevent the creation of 2 identical trips.  Seems like a pretty unlikely scenario though.

@scottleach-NOAA

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  I think we should implement the validation you spelled out. I don't think guys are going to intentionally enter multiple trips with the same start date/time. My concern is the they do it unintentionally. The one hour buffer would help prevent this, but as you said it is not perfect. 

@scottleach-NOAA @johnlafargue-noaa  do you guys have thoughts on this issue?

**Comment by johnlafargue-noaa** [comment]
I think that will be fine.
