### ISSUE TITLE
logbook data not showing up in data comparison screen

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1855]
@sethgerou-noaa entered logbook data via the app for trip 100208.  the weights of the catch categories does not display in the data comparison screen.

![image](https://user-images.githubusercontent.com/31421964/90568209-493bfe80-e160-11ea-8c3b-99de59618fe8.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA just fyi, now that we've decided logbook will have pacfin species code, and em review will have wcgop code, some work needs to be done to display them both on the same line.  The comparison screen was built under the assumption that both would use the pacfin code.

**Comment by neilriley-NOAA** [comment]
Oh right. I will hold off on logging any issues on this page until the species code issue is sorted out.
