### ISSUE TITLE
Create WCGOP interface models

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#188]
Create the WCGOP models for:
- WcgopTrips
- WcgopHauls
- WcgopCatch
- WcgopContainers
- WcgopSpecimens

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA, @wsmith-nwfsc - I'll set up some time for us to finalize the WCGOP models

**Comment by toddhay-NOAA** [comment]
From our Monday meeting with the Observer team (and Neil in particular), add the following properties to the WcgopHauls interfaces:

- isHaulUnsampled
- isGearLost
- sightingEvents

**Comment by wsmith-nwfsc** [comment]
We have sightingEvents in Trips already- do we want it in both, or just in Hauls?
f64205ba147f461f5add3d61e541079c38286f05 covers the above

**Comment by wsmith-nwfsc** [comment]
Sighting events handled like so b17cef9b26ea8963452aa9fe8ec124bb5c2b1e72
