### ISSUE TITLE
Elogbook - Add INVT species code to the Catch lookup

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1890]
@sethgerou-noaa

Add a couple species codes to the Catch lookup in the Elogbook. 

INVT - Invertabrates
NIFQ - Non-IFQ Fish Species 

Assuming this will be updated when @NickShafferNOAA completes his work, but would be helpful to have in the sort term. 

Also, this look up has a lot of dupes. I think this is because the list is not filtering on the active flag. This list should should only display active codes.

**Comment by NickShafferNOAA** [comment]
I have verified that both of these items are in couch.
