### ISSUE TITLE
Elogbook - unable to delete a haul

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1891]
@sethgerou-noaa we need a way to delete a haul from the elogbook.

example in tripid 100239.  I would like to remove haul 3, but able. 

![image](https://user-images.githubusercontent.com/31421964/92807847-15738380-f370-11ea-967b-91d3671a6433.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA should you be able to delete a haul with catch?  Or should you have to delete all the catch before you can delete a haul?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  I think we could have it cascade, so we don't have delete each catch record. That said, can you add a warning saying confirming you intend to delete and that all catch records will be lost?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa This is working properly.
