### ISSUE TITLE
Build 2019 Hook and Line apps for testing

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1893]
Harms mentioned that they have a version from ~2018, and it would be good to have the most up to date version (before any of our changes AKA off of master branch) for testing purposes.  This will be good for me and @SaOgaz-NOAA to have prior to going into the pilot plant anyway.

Do we need to do target stations reload here?  Can't remember, need to remember which SQLite db to use for this.  I think H&L uses PyQt 5.9 across the board, so that's what I'll build with.

**Comment by SaOgaz-NOAA** [comment]
Adding myself to this ticket so I can also get H&L clean builds going.

**Comment by jimfellows-NOAA** [comment]
Steps (I think) to build Hook and Line:

1. Get fresh db files from old GitLab repo and drop into data/:
    a. [hookandline_fpc.db](https://nwcgit.nwfsc.noaa.gov/fram-data/pyqt5-framdata/-/blob/master/data/hookandline_fpc.db)
    b. [hookandline_hookmatrix.db](https://nwcgit.nwfsc.noaa.gov/fram-data/pyqt5-framdata/-/blob/master/data/hookandline_hookmatrix.db)
    c. hookandline_cutter.db (not in GitLab)
    d. clean_sensors.db

2. Run build_hookandline_fpc.py (make sure "build" is listed as a parameter for PyCharm run config)*
3. Run build_hookandline_hookmatrix.py
4. Run build_survey_backdeck.py

*cx_Freeze wants SQLite3.dll to be in venv/DLLs.  Mine was in venv/Scripts/.  I created a DLLs folder and copied there.

Not sure if the DB files need any scrubbing prior to build.  The only one that looks like it has any substance is hookandline_fpc.db.  I don't see a target_stations_lu table, so I'm assuming that those don't need to be loaded for H&L, but could be wrong.

**Comment by SaOgaz-NOAA** [comment]
Okay, I've got builds of master with console on for all three H&L parts.
