### ISSUE TITLE
Establish jenkins auto-build + deployment to dev server

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#190]

**Comment by wsmith-nwfsc** [comment]
Jenkins building all of boatnet/ again (from github.) Still have to configure deployment to web.

**Comment by toddhay-NOAA** [comment]
#191

**Comment by toddhay-NOAA** [comment]
Depends on #191

**Comment by wsmith-nwfsc** [comment]
For some reason, git polling is failing like so (from the Polling Log)
{pre}
 > git log --full-history --no-abbrev --format=raw -M -m --raw 36a5b7bafe0cb7227175f3553365df9d54b739cc..69266abbcbd1b1909544543d4477ca57b0b34871 # timeout=10
ERROR: Failed to determine if we want to exclude 69266abbcbd1b1909544543d4477ca57b0b34871
hudson.plugins.git.GitException: Command "git log --full-history --no-abbrev --format=raw -M -m --raw 36a5b7bafe0cb7227175f3553365df9d54b739cc..69266abbcbd1b1909544543d4477ca57b0b34871" returned status code 128:
stdout: 
stderr: fatal: Invalid revision range 36a5b7bafe0cb7227175f3553365df9d54b739cc..69266abbcbd1b1909544543d4477ca57b0b34871
{pre}

**Comment by wsmith-nwfsc** [comment]
Created standalone Jenkins SOP from Brandon's transition document

**Comment by wsmith-nwfsc** [comment]
Requires a manual click of "Build Now" but this is working. Auto-deploys to https://nwcdevfram.nwfsc.noaa.gov:10443/login
(also, certificate is good on nwcdevfram, so need to figure out how to do this on nwcdevmeow1)
