### ISSUE TITLE
Revise ifq-grouping doc set

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1901]
- [x] Include couch_id for catch-groupings array
- [x] Remove taxonomies array from catch-groupings, not needed
- [x] Load to couch prod

**Comment by jimfellows-NOAA** [comment]
Docs loaded to prod.  @sethgerou-noaa @melinashak-noaa if you need to play around with these in prod they're in there.  If data needs to be added, changed or rearranged let me know.

**Comment by melinashak-noaa** [comment]
Thanks for getting the docs in order. Looks like we all the IFQ grouping doc are there. Just noticed a few  discrepancies from Neil's EM [doc](https://docs.google.com/spreadsheets/d/1DLxs6uU3t7i1mBEHbWNxTboQGv5K1Gj-tSL0acfxPUk/edit?ts=5f34092a#gid=9952348) listed below

Note: Created a view, pacfin-codes-to-ifq-groupings, that maps pacfin codes to ifq groups, to run a few spot checks. 

These species are showing up in multiple IFQ-grouping documents, but believe they should only be in one. 
- BCAC (Bocaccio Rockfish) Showing in both the Minor Shelf Rockfish North and Bocaccio Rockfish. Should be in Bocaccio only
- CLRP - Chilipepper and minor shelf, belongs in chilipepper
- YTRK (Yellowtrail rockfish) showing in minor shelf and yellowtail rockfish, belongs in yellowtail 
A few others: CWCD, POP, SNOW, STRY

Don't see these species showing up in any of the ifq-grouping docs. In Neil's doc they are listed under minor shelf rockfish
- DBRK (Darkblotched Rockfish) 
- NUSF - same for this as well

These species are missing, not showing up in any doc
- OFLT (Other Flatfish) 
- RSOL(Rock Sole)

**Comment by jimfellows-NOAA** [comment]
Thanks for checking these out.  The species showing up across multiple ifq-groupings is I think due to them being listed that way in Oracle's ifq_specie_groupings table.  For Bocaccio, here's what Oracle shows for 2020:

![image](https://user-images.githubusercontent.com/57507677/93269806-995caf80-f764-11ea-8938-33721431497e.png)

which is the logic behind the Bocaccio taxonomy doc being listed once under the ifq-grouping doc name = "Minor Shelf Rockfish North" with a upper latitude of 40.166667 and no lower bound, and once under the ifq-grouping "Bocaccio Rockfish" with a lower latitude bound of 40.166667 and no upper bound.

![image](https://user-images.githubusercontent.com/57507677/93270012-040deb00-f765-11ea-9faf-9ab91827b04a.png)

Those other species you listed look like they follow suit, so there might be a difference between my data pull from oracle and Neil's spreadsheet.

**Darkblotched** should have its own ifq-grouping doc: 6bd01c3bb9ff036c690d288d3e74f884

Does **NUSF** need an ifq-grouping?  There's no reference to it in the Oracle WCGOP DB as a catch category or ifq grouping

"**Other Flatfish**" is an ifq-grouping (6bd01c3bb9ff036c690d288d3e75186a) in there now.  There's also a catch category/grouping called Other Flatfish (OFLT), but it doesn't have a corresponding ifq grouping.

I think RSOL is actually a genus-level taxonomy doc (species ID: 10362, taxonomyId 4fa0ab1f2ccf04160ab89da3e39a4fb5) and its listed that way under the Other Flatfish ifq grouping, so maybe that's why it doesn't have a pacfin code in there?

**Comment by neilriley-NOAA** [comment]
@jimfellows-NOAA You are correct about Bocaccio RF. I didn't realize it was part of the Minor Shelf North. I went back and checked the original outreach documentation and the way you have it matches up. 

I don't believe NUSF needs an ifq-grouping. that is a code the EM software was using.

**Comment by jimfellows-NOAA** [comment]
Thinking about how we've converted FISHING_AREA to latitude bounds.  I think we can do this as long as we also carry the FISHING_AREA or actual catch latitude through to wherever we're writing expansions that we make available to SDM.  If we rely purely on IFQ group name, we won't be able to differentiate between Bocaccio caught in fishing area 200 and fishing area 300.  Just something to keep in mind.
