### ISSUE TITLE
Pull First receiver (buyers) from PERMITS database

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1904]
@sethgerou-noaa  Just getting some of our conversation from today into a ticket:

with gf permits, we've taken the approach of always querying permits, instead of making a copy in couch - so we don't/can't get out of sync. We should do the same with Buyers so we have a standardized list.  This same list will be used in the observer data. 

SDM should be able to expose via web service.

link is the public list of permits:    [https://www.webapps.nwfsc.noaa.gov/apex/ifq/f?p=112:45::::::](https://www.webapps.nwfsc.noaa.gov/apex/ifq/f?p=112:45::::::)

Follow-up issue.
Possible need to alter API. The api currently just accepts buyers as an array of strings
do we need to switch that to be something like buyer name and license number
similar to fishTickets array containing fishTicketNumber and fishTicketDate for each fish ticket?

**Comment by sethgerou-noaa** [comment]
Ask SDM about API availability of buyers + logic to differentiate sites
