### ISSUE TITLE
Elogbook - tabbing into the return date picker stuck in loop unable to tab out

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1907]
@sethgerou-noaa when I tab the cursor from the decimal degree longitude field the return date field (which was already filled out. Should be able to freely tab from one filed to the next or out the the date picker.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA when you are in a date picker component, you can hit Tab, then Esc, then Tab to the next field.  hopefully this is sufficient, as I don't really want to have to create custom functionality for a pre-built (date picker) component.

**Comment by neilriley-NOAA** [comment]
Oh ok. that will have to work. I didn't know if there was an easy fix. Kind of annoying but most logbook data should be entered via the API so hopefully we just view data through this app most of the time.
