### ISSUE TITLE
elogbook - clear the catch record after saving new catch data

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1908]
@sethgerou-noaa - in the elogbook, after submitting the new catch record, the previously submitted data should be cleared automatically before entering the next record.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 
The current Submit/Update functionality is designed so a user can save as they go - to minimize the change of data loss.
for example a user might want to complete the user details then hit Submit/Update to save, then get started on haul details.
I could see having 2 buttons, one that says Save, which does the above, and then Submit/Update could kick you back out to the Task Management screen (after it saves).

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA - do we need to discuss?  didn't see a reply from you...

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa No need to discuss. I am not sure this is worth changing. Seems cleaner to have one button. We can revisit if it becomes an issue.
