### ISSUE TITLE
Implement CouchDB Clustering

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#191]

**Comment by toddhay-NOAA** [comment]
Awaiting upgrade of CouchDB to the latest version, which in turn is waiting for the upgrade of our server to the latest version of CentOS

**Comment by toddhay-NOAA** [comment]
I checked with Shane in IT yesterday on this and he's swamped, so this has been down in the priority queue.  He also indicated that he's having an issue with getting the replication working between the primary and the clone.

**Comment by toddhay-NOAA** [comment]
Shane is currently working on implementing clustering between the primary and secondary CouchDB servers, so as to enable the newly generated user databases to replicate between the two servers, i.e. they would get picked up as they are created/established, and added to the clustering.

**Comment by toddhay-NOAA** [comment]
@wsmith-nwfsc , please get with Shane when you're back and assist him with setting up the CouchDB clustering.

**Comment by wsmith-nwfsc** [comment]
This will cover replication of the userDB's between servers, as described in #400

**Comment by wsmith-nwfsc** [comment]
#550
