### ISSUE TITLE
Protected species

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1924]
@sethgerou-noaa @melinashak-noaa 

Here is the listed of protected species. I am not sure if there is an  easy way to tease out all mammals and birds. If not let me know and I compile the list.

**Protected species:**
Chinook salmon
Coho salmon
Pink salmon
Sockeye salmon
Chum salmon
green sturgeon
Eulachon
Dungeness crab
All sea birds
turtles
All marine mammals

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @BHHorness-NOAA 

There are only a few bird species listed as protected for our purposes (listed below). All other bird codes should be made available to the EM providers.

**Sea birds listed as protected species:** 
Short-tailed Albatross
Marbled Murrelet
CA Least Tern
Pink-footed Shearwater

All mammal codes need to be listed as protected species and made available to the EM providers.

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa @sethgerou-noaa @BHHorness-NOAA 

I am not sure how or if we need to flag these species in the database.  What we do need to do is be conscious of them and if we get any data for any of the protected species we need to do an expanded count for them. This would be the same way we do weight expansion, but using the count instead of the weight. These aren't IFQ species so we won't need to report them to the vessel account.

**Comment by melinashak-noaa** [comment]
@sethgerou-noaa  @NickShafferNOAA 
Would it make sense to add an isProtected field to the taxonomy-alias doc. Similar to how we curerntly have the isMixed field. Then we would know which counts need expanding.

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa Yes, I think adding a flag to the taxonomy-alias makes sense.

**Comment by melinashak-noaa** [comment]
updated database to have isProtected flag and updated code to validate and expand counts when present.
