### ISSUE TITLE
EM Priority species

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1925]
@sethgerou-noaa ; @melinashak-noaa 

Only report 2 priority species. 

Cowcod Rockfish: WCGOP species code = 360
Yelloweye Rockfish: WCGOP species code = 322

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @melinashak-noaa 
I got confirmation the priority species should always have a weight and count. If either the count or weight is missing, it should be flagged so we can follow-up. Therefore the API should not reject a submission from either the logbook or the EM provider.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Thanks for getting clarification on this. 
Makes me wonder how we call attention to submissions that are missing info...

- I could see a page that lists all submission errors, and provides links to examine / correct.

- Or the task management page could have an errors count per trip - and clicking into the logbook or review could highlight errors somehow.

Speaking of which - do we need some way to view an EM review? (perhaps similar to how the e-logbook displays logbook submissions, or maybe a page that just displays the JSON)  Currently the app only exposes review info via the comparison screen.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 
I agree at the very least we need a page that lists all submission errors, and provides links to examine / correct. 

We probably do need a way to review the EM details outside of the comparison screen. I want to give that a little more thought and address it in a separate ticket.

**Comment by melinashak-noaa** [comment]
updated database to have isWcgopEmPriority flag and updated code validate and expand counts when present.
