### ISSUE TITLE
eLogbook - Dupe species codes

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1926]
@sethgerou-noaa 

There multiple dupe species codes in the elogbook lookup. I am wondering this needs to be filtered based on active codes. I think there is an active flag for reference or will this be corrected when @NickShafferNOAA loads codes on his end? 

![image](https://user-images.githubusercontent.com/31421964/94051995-333be200-fd8d-11ea-8c69-3034f67b8fdf.png)

**Comment by sethgerou-noaa** [comment]
this issue has been resolved - dupes are gone
