### ISSUE TITLE
Develop sample flattened views in CouchDB

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#193]
We should explore building out a few very flattened views that we can use for potential debriefing and reporting in general.  I'm thinking that these views would be at the following grains:

- Containers (i.e. baskets)
- Specimens (i.e. fish)
- Catch (i.e. species total weight - for those that don't have baskets)

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA, once you have the WCGOP data transferred over, I'll then want you to work up some flattened views for driving our reports.

**Comment by Mak-NOAA** [comment]
@wsmith-nwfsc  I'm building the flattened view starting with Trip/Operation. I have a few questions:
1) Can you please paste the example you demoed where you joined in our weekly meeting or point me to it?
2) Shouldn't the trip model contain a list of operations? https://github.com/nwfsc-fram/boatnet/blob/master/libs/bn-models/models/wcgop/wcgop-trip.ts 
I know I need to get a list of trips and loop through its operations but I don't see a list.

@toddhay-NOAA  do we want to make the flattened views WCGOP/ASHOP specific?

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, the WcgopTrip extends BaseTrip, which has an array of operation IDs:

https://github.com/nwfsc-fram/boatnet/blob/master/libs/bn-models/models/_base/base-trip.ts

```typescript
export interface BaseTrip extends Base {
  operationIDs?: CouchID[]; // Haul/ Set UUID's
  captain?: Person;
  vessel?: Vessel;
  crew?: Person[];
  // Do we want plannedDeparturePort?
  departureDate?: BoatnetDate;
  returnDate?: BoatnetDate;
  departurePort?: Port;
  returnPort?: Port;
  // Metadata
  isExpanded?: boolean;
  doExpand?: boolean; // should expand or not after manual calculation

}
```

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , yes the flattened views will be A-SHOP and WCGOP-specific.

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , for the sample views, you'll want to iterate across the various arrays, as discussed here:

https://docs.couchdb.org/en/stable/ddocs/views/intro.html

search for forEach which takes you to:

```typescript
function(keys, values, rereduce) {
    var unique_labels = {};
    values.forEach(function(label) {
        if(!unique_labels[label]) {
            unique_labels[label] = true;
        }
    });

    return unique_labels;
}
```

One note however.  Operation/Haul/Set documents are actually separate documents then Trip documents.  So you'll need to determine if we can query across documents as part of this.

**Comment by wsmith-nwfsc** [comment]
I'm not sure you can (or want to query) the operation documents inside each trip. This would probably be something our UI would perform. The get operation is extremely fast.
Also note that once you start creating a view with a lot of data in the "emit", this is probably a good sign that you should just  tack on the `?include_docs=true` query and the view returns the entire doc. In that case, the view would be useful for enumerating all `trip` docs (and the client side would arrange the document data in the data table as it sees fit, using the full doc returned via `include_docs=true`)

Example:
```
https://nwcdevfram2.nwfsc.noaa.gov:6984/lookups-dev/_design/optecs_trawl/_view/all_vessel_names
```
And if the UI wanted to get all the vessel data past that, just
```
https://nwcdevfram2.nwfsc.noaa.gov:6984/lookups-dev/_design/optecs_trawl/_view/all_vessel_names?include_docs=true
```

**Comment by wsmith-nwfsc** [comment]
Also, see this:
https://docs.couchdb.org/en/stable/ddocs/views/joins.html

**Comment by wsmith-nwfsc** [comment]
Using the example code in the above link, I made an attempt at a "flattened" view (instead of emitting 5 docs like they do in the example.)
See:
https://nwcdevfram2.nwfsc.noaa.gov:6984/wsmith-test/_design/test/_view/test-join?include_docs=true

**Comment by Mak-NOAA** [comment]
thanks @wsmith-nwfsc I'm checking it out. Yeah I thought I'm gonna have a million things to "emit" so can I somehow emit all?

**Comment by Mak-NOAA** [comment]
Very nice @wsmith-nwfsc  , so as long as we include the ID of the child doc, using the `include_docs` option, we can extract all columns without requiring to emit each one explicitly?

**Comment by wsmith-nwfsc** [comment]
@Mak-NOAA Yes, it appears so! You kind of have to roll the records together, but it includes all the fields, so you won't have to maintain a huge list of items to emit in the view.

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , you'll want to incorporate the latest feedback that I provided to #69 (https://github.com/nwfsc-fram/boatnet/issues/69#issuecomment-486508305) as you develop these flattened views.  Please provide an update as to how you're making out with this particular task.

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA   the views should be created in master-dev correct?

**Comment by toddhay-NOAA** [comment]
yes

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , please provide an update on this task.

**Comment by Mak-NOAA** [comment]
Planning to have a few of the views created by end of week.

**Comment by Mak-NOAA** [comment]
@wsmith-nwfsc I have created 5 flattened views in the master-dev couchDB, can you please review? I don't know if we don't have data or my couchdb just times out:
1) all-operations-flattened
2) all-catch-flattened
3) all-catch-species-flattened
4) all-baskets-flattened
5) all-specimens-flattened

@toddhay-NOAA  there's no need to flatten trips as there's already all-trips

**Comment by wsmith-nwfsc** [comment]
@Mak-NOAA This is a good start, all-operations-flattened I think basically contains all the data.
For all-catch-flattened (and probably the others, I haven't looked at them yet) it won't quite work as it's written, e.g. you can't do this:
```
doc.operationIDs[i].catches
```
But, since the data for a trip is contained within wcgop-trip and wcgop-operation, the all-operations-flattened  view may be enough, and the UI could flatten the records.

**Comment by toddhay-NOAA** [comment]
Remember, I want us to try and actually create truly flattened views on the CouchDB side of the house and then compare that to if we don't completely flatten and then just return that to the client for flattening.  I would like to understand the performance of those two approaches.

**Comment by wsmith-nwfsc** [comment]
Show functions are useful to transform doc data, such as flattening:
https://docs.couchdb.org/en/2.3.1/ddocs/ddocs.html?highlight=show%20functions

**Comment by Mak-NOAA** [comment]
@wsmith-nwfsc do you know if there's a solution so that I could get all catches in an operation like doc.operationIDs[i].catches ? I'll read the links you shared but if it's impossible then I don't want to chase the rainbow

**Comment by wsmith-nwfsc** [comment]
The catches are already in the operation, but you won't be able to iterate on them (via forEach) in the top-level all-operations-flattened view, which operates on `wcgop-trips`. If you have a view that works on `wcgop-operations` then you could do a `forEach` loop on the catches in that. But not sure of the best way to tie the two together--I'd take a closer look at the `List functions` to see if that'll work.

**Comment by toddhay-NOAA** [comment]
Thanks to @NickShafferNOAA who put together a views-test database in the dev CouchDB server for us, with about 20 trips or so (and associated operations as well) from WCGOP that we can use for trying out various views, so please start using this for testing purposes @Mak-NOAA

**Comment by Mak-NOAA** [comment]
Thanks @NickShafferNOAA , that will definitely help experiment with the views!

**Comment by Mak-NOAA** [comment]
experimented with list functions but stuck as @wsmith-nwfsc mentioned, we can't access 2nd level down below operations. I found that's true even with List functions.

Hence:
https://stackoverflow.com/questions/55987610/is-there-a-way-to-join-more-than-2-documents-in-a-map-function

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , the link that Will provided above seems to do the trick:

https://nwcdevfram2.nwfsc2.noaa.gov:6984/master-dev/_design/MainDocs/_view/all-operations-flattened?startkey=[%22189700cdcd4f9426eb10e711e1000cde%22]&endkey=[%22189700cdcd4f9426eb10e711e1000cde%22,{}]&include_docs=true

**Comment by Mak-NOAA** [comment]
Just to close the loop here based on the weekly meeting. We will make 2 calls from the UI, one to get all-trips and a second call for everything else from all-operations-flattened using include_docs=true

@wsmith-nwfsc sounds right?

**Comment by toddhay-NOAA** [comment]
I actually think you'll just pull from the all-operations for the second call as that will return the operations JSON documents and then you can work with it from there.

**Comment by Mak-NOAA** [comment]
ok so call 1: all-trips and call 2: all-operations?

**Comment by toddhay-NOAA** [comment]
yes, that is correct @Mak-NOAA

**Comment by wsmith-nwfsc** [comment]
archived this DB (new one didn't get these operations)
https://nwcdevfram2.nwfsc2.noaa.gov:6984/master-dev-backup-5-23-2019/_design/MainDocs/_view/all-operations-flattened?startkey=[%22189700cdcd4f9426eb10e711e1000cde%22]&endkey=[%22189700cdcd4f9426eb10e711e1000cde%22,{}]&include_docs=true
