### ISSUE TITLE
Optecs 2021 Dev Issues!

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1934]
First tracking issue for any work related to our development work for for 2021 season.  Link to JIRA / GitHub issues in comments below.

**Comment by jimfellows-NOAA** [comment]
wrapped up the following and sent off to Optecs testers for review:
https://www.fisheries.noaa.gov/jira/browse/FIELD-2046
https://www.fisheries.noaa.gov/jira/browse/FIELD-2019
https://www.fisheries.noaa.gov/jira/browse/FIELD-1837

Also worked on 
https://www.fisheries.noaa.gov/jira/browse/FIELD-2023
https://www.fisheries.noaa.gov/jira/browse/FIELD-2045

**Comment by SaOgaz-NOAA** [comment]
wrapped up:
https://www.fisheries.noaa.gov/jira/browse/FIELD-1904
https://www.fisheries.noaa.gov/jira/browse/FIELD-2025
https://www.fisheries.noaa.gov/jira/browse/FIELD-2032
