### ISSUE TITLE
Fishery lookup in OTS and EM should exclude inactive fisheries

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1937]
@sethgerou-noaa 
The fisheries below are inactive and should not be included in the fishery lookup list of OTS or the API documentation.

FISHERY | FISHERY DESC
10	CA Coonstripe Prawn
1	Limited Entry Trawl
17	CA and OR Pink Shrimp
6	CA Open Access Fixed Gear
32	CA SFCFA Yellowtail RF Jig EFP
14	CA Prawn
7	CA Spot Prawn

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Are these completely inactive?  Meaning no program / app currently uses them?  WCGOP, ASHOP etc.
Trying to determine whether I set them to isActive: false, or just isEm: false

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  These would be isActive: false

They are no longer observed so these codes would only show in legacy data.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Thanks!  I've set isActive: false on the requested docs - in both DEV and PROD

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa     two additional fisheries you can change to inactive that we no longer observe. 

25 = PSMFC Discard Handling Research
15 = Pacific Hake

**Comment by sethgerou-noaa** [comment]
I set these species inactive
