### ISSUE TITLE
EM API documentation - Fate lookups

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1939]
@sethgerou-noaa  the Fate lookups on the API documentation need to be updated with the code below. I suspect we will have to add more when the hook and line protocols are developed. 

Code | Lookup | Description
-- | -- | --
1 | Unintentional Discard | Catch that was not   deliberately removed from the gear by crew, but fell out/off of the fishing   gear.
2 | Unknown | Catch taken out of   view of the camera or unsorted catch on deck when camera fails.
3 | Discarded – General | Catch released. No   damage apparent that would deem
4 | Discarded – Damaged | Catch   with scavenger predation or general damage, deeming catch unmarketable, which   is released. Count required for IFQ species AND for decomposed fish that are   indistinguishable from IFQ. Do not include weight, as it is not   representative of the live fish.
5 | Throwback | Catch previously   identified as retained and has now been discarded or utilized on-board.
6 | Utilized On-board | Catch   is consumed/intended to be consumed by crew, or used as/intended to be used   as bait. It might be filleted onboard. This catch will not show up on a fish   ticket with retained catch. Fish with this fate are treated as discards in   the database.

**Comment by sethgerou-noaa** [comment]
I've added these

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa these codes needed to replace the other codes. Sorry I wasn't more clear.

**Comment by sethgerou-noaa** [comment]
ah, ok, all but this list set to isActive = false
