### ISSUE TITLE
Add EM Image upload reasons lookups

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1942]
@sethgerou-noaa Here is a list of image submission reasons and descriptions

Species ID confirmation - Unknown species for additional review
Compliance  - catch handling issues, camera views (dirty cams, camera views inconsistent with VMP, color issues), lighting, etc
Protected species interaction (Mammal, Bird, etc)
Safety incident - 
Other -

**Comment by sethgerou-noaa** [comment]
This is done - should appear in api-docs in a few minutes
