### ISSUE TITLE
API lookups - group mammal and bird species codes together

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1946]
@sethgerou-noaa as discussed last week, I think we should explore the possibility of grouping mammal and bird species codes together in the API lookups

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @NickShafferNOAA We discussed this in a data team meeting last week.
This sort of categorization doesn't currently exist in Boatnet - as I recall, Nick was going to determine what broad categorization/grouping exists in Oracle currently, and then we can determine how to incorporate in Boatnet.

Would this sort of broad categorization eventually be relevant to the observer tablet app too (all taxonomy-alias and catch-grouping), or is this just needed for EM (only isEm taxonomy-alias and catch-grouping)?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @NickShafferNOAA each species in the obsprod.SPECIES table this categorization associated. 

I am not sure if this would be useful in the observer tablet app. that would be a good question for @Jeibner-NOAA

**Comment by Jeibner-NOAA** [comment]
@sethgerou-noaa  @NickShafferNOAA  @neilriley-NOAA 
Yes, I think that would be useful as we move toward getting rid of Catch Categories.

**Comment by NickShafferNOAA** [comment]
speciesCategory and speciesSubCategory attributes have been added to alias documents based on the fields from the oracle database.

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA  Great. Thanks!
