### ISSUE TITLE
Add "IsTarget?" flag to catch groupings and/or species to Boatnet

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1947]
@sethgerou-noaa @melinashak-noaa @NickShafferNOAA @BHHorness-NOAA 

Add "IsTarget?" flag to catch groupings and/or species to Boatnet to clearly identify the codes used for Target Strategy at the haul level. Currently, some codes are flagged in OBSPROD with "Target" in the catch category name.  

 _DTS   Dover/Thornyheads/Sablefish - Target_  

https://www.fisheries.noaa.gov/jira/browse/FIELD-1229

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA is this something you are working?

**Comment by NickShafferNOAA** [comment]
@neilriley-NOAA  I have flagged the groupings from obsprod listed as targets. Let me know if individual species need to be flagged as well.

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA There are bunch of individual species that need to be flagged as IsTarget. The query below identifies every code used by observers since start of Catch Shares. All the codes in that list should be added to the isTarget list. This will be needed for observer data as well.

SELECT DISTINCT catch_category_code target, count (fa.fishing_activity_id) frequency
FROM
    trips t JOIN fishing_activities fa ON t.trip_id = fa.trip_id
    JOIN catch_categories cc ON target_strategy_id = cc.catch_category_id
WHERE t.return_date >= '01-JAN-11'
GROUP BY catch_category_code
ORDER BY 2 desc;

ARTH
BANK
BCAC
BLCK
BLGL
BLUR
BRSH
BRSL
BRWN
BSKT
CBZN
CHLB
CHNA
CHNK
CLPR
CNRY
COPP
DBRK
DOVR
DSRK
DTS
DWD
EGLS
GPHR
GRAS
GRDR
GSPT
IFQM
KLPR
LCOD
LSKT
LSPN
LSRK
NEST
NSHR
NSLF
NSLP
NSM
OFLT
OLVE
OSKT
PCOD
PDAB
PHLB
POP
PTRL
PWHT
QLBK
REX
ROCK
RPRW
RSOL
SABL
SCOR
SDAB
SHPD
SKAT
SLGR
SNOS
SRMP
SSHR
SSLF
SSLP
SSOL
SSPN
STRY
THDS
UHAG
UNKN
URCK
USCU
VRML
WBAS
WCRK
WDOW
YMTH
YTRK

cc @BHHorness-NOAA @sethgerou-noaa

**Comment by NickShafferNOAA** [comment]
Added flags for all specific items

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @NickShafferNOAA @melinashak-noaa @Curt-Whitmire-NOAA 

I am reopening this ticket. This was closed out with out the Target Strategy flag being added. See the list for the codes used in the observer data. I will identify the specific codes that are not part of our Catch Grouping document.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I've added the isTargetStrategy boolean to catch-grouping and taxonomy-alias models, and have created target-catch-grouping doc type.  Awaiting your list of required targets.  If the list above is accurate, I think I'll at least need a name/common name to go along with the pacfinCode in cases where we know the target-catch-grouping does not exist yet.  The rest I can probably look up / set the flag from the pacfinCode.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 

Here is a list of the targets used by observer since 2011. I have included the description and the frequency of use. I would argue we don't include any of the codes that were used less than 10 times. 


[Target_Strategies.xlsx](https://github.com/nwfsc-fram/boatnet/files/5784398/Target_Strategies.xlsx)
