### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1950]
@sethgerou-noaa add the text below to the API “Programs” documentation page before the Regions website URL

_Additional information about the Electronic Monitoring program and the provider application process is available at the West Coast Region website._

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA this has been added - will show up shortly

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa doesn't look like this changed.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Ah, hadn't re-deployed tripsApi - the updated code is up now.

**Comment by neilriley-NOAA** [comment]
Looks good now.
