### ISSUE TITLE
EM API Portal error

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1951]
@sethgerou-noaa 

I entered a valid trip number which returned an error below the field stating the weight should be a number. Not sure where that is coming from?

![image](https://user-images.githubusercontent.com/31421964/96306714-10c86d80-0fb5-11eb-8636-d62c1d4960ab.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I'll update this error message to be about the tripNum instead of weight, but the error displays when there is a line break after the tripNum (if you hit enter after the value).
