### ISSUE TITLE
API documentation formatting

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1954]
@sethgerou-noaa There are a couple annoying formatting issues on the Instructions tab of the API documentation

1. need a little space between the blue box and the https Required header.

![image](https://user-images.githubusercontent.com/31421964/96320177-7ec96080-0fc6-11eb-8fe7-e8a0c2c097c8.png)

2. Left justify these sections and make the first letters upper case in the "dates and times" header to be consistent with other sections.

![image](https://user-images.githubusercontent.com/31421964/96320120-4c1f6800-0fc6-11eb-86e4-f637b292be85.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I've implemented these changes - they'll show up when the tripsApi finishes re-deploying
