### ISSUE TITLE
catch-grouping memberships

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#1956]
edit species / membership lists for catch-grouping documents

**Comment by NickShafferNOAA** [comment]
I have added specific memberships to the groupings: Roundfish Unid(IFQ), Flatfish Unid(IFQ), and Rockfish Unid(IFQ). 

Some of the grouping membership definitions were vague and / or extremely large, so they still have no distinct list: Roundfish Unid, Fish Unidentified, Decomposed Fish, Unknown, Fish Unidentified(IFQ).

@neilriley-NOAA @BHHorness-NOAA

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA 

We still need to have membership groupings for Fish Unidentified(IFQ) and Roundfish Unid

Fish Unidentified(IFQ membership should be all species contained within Roundfish Unid(IFQ), Flatfish Unid(IFQ), and Rockfish Unid(IFQ)

Roundfish Unid is going to be tricky. If we have the category and subcategory fields then we could narrow this list of species down. The criteria below should get you what you need.

isEM = true

select * from species where 
species_category = 1 --Fish
and species_sub_category in (101, 103, 104, 105, 108, 109, 111) --Cod, Rockfish, fish other, Salmon/Trout , Tuna/Mackerel, Sculpin, Grenadier 
;

cc @BHHorness-NOAA @sethgerou-noaa @melinashak-noaa

**Comment by BHHorness-NOAA** [comment]
@neilriley-NOAA Looking ahead, does the list (Cod, Rockfish, fish other, Salmon/Trout , Tuna/Mackerel, Sculpin, Grenadier)  fully specify the membership of roundfish unid for wcgop as well?  Or is this definition limited to em?  I suppose we should canvas ashop also to see if they use it and if so, how they define it?  the trawl survey doesn't use the roundfish label, so that's not a consideration here.

**Comment by neilriley-NOAA** [comment]
@BHHorness-NOAA WCGOP doesn't have a Roundfish Unid catch category and observers rarely use the Roundfish Unid species code. The Roundfish unid species code isn't used in any of the current Catch Share calcs. I think we can say this membership is for EM.  I would guess ASHOP doesn't use it but we could ask.

**Comment by BHHorness-NOAA** [comment]
Just for future reference, it looks like roundfish and fish unid are both used in the norpac ATL_SPECIES_COMPOSITION table.  Further complication is that both have been assigned a scientific name of OSTEICHTHYES.  According to @VanessaTuttle-NOAA  these aren't broken down into individual species within the expansion logic in ashop processing.

**Comment by melinashak-noaa** [comment]
Related question https://github.com/nwfsc-fram/boatnet/issues/2035

**Comment by NickShafferNOAA** [comment]
just a quick update, currently in progress on this issue

**Comment by NickShafferNOAA** [comment]
This got placed briefly on the back burner due to other issues, the holiday, and some sick leave. Back to finishing this up. Should have the missing group memberships sorted within the next day.
