### ISSUE TITLE
OPTECS tickets

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1957]
Do the stuff

**Comment by SaOgaz-NOAA** [comment]
working on:
https://www.fisheries.noaa.gov/jira/browse/FIELD-2033

**Comment by jimfellows-NOAA** [comment]
Completed:
https://www.fisheries.noaa.gov/jira/browse/FIELD-1894

Started:
https://www.fisheries.noaa.gov/jira/browse/FIELD-1852

**Comment by SaOgaz-NOAA** [comment]
finished sprint 1!
