### ISSUE TITLE
EM Data Comparison - wrong species code

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1958]
@sethgerou-noaa I uploaded test under tripid = 100249.  The EM Data Comparison screen is displaying the wrong species code. It displays fish error 321 the data uploaded was for species codes 206 & 318

![image](https://user-images.githubusercontent.com/31421964/96625877-96a12d00-12c3-11eb-99c1-0c665a1e0ab0.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA is this still an issue?  When I pull up trip 100249 in the comparison screen I see common names, and do not see fish error 321

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa This looks ok now. Is this a result of something you fixed or was something changed with the species lists?

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 'fish error 321' is sort of a placeholder error for when the app is unable to look up the common name for a species code, so it could either be something that was wrong with the species code in the catch data, or an error in the Couch view.   Hard to say why you saw the error when you did, but I may have still been tweaking the view.

Please let me know if you see it again - there shouldn't be a reason to see it, other than an invalid species code.
