### ISSUE TITLE
OTS - Max retention trips 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1959]
@sethgerou-noaa  No one objected to the change OTS so a Max Retention trip can be logged upon return to port. This will save them having to edit the original entry and will allow them to submit the logbook image at the same time.  All other optimized retention trips would be logged prior to the trip.

Options to resolve issue:

1. Tweak OTS so any vessel fishing midwater gear does not have to enter the trip via the missed trips button. 

2. we could just leave the app as is and have them enter these as a missing trip upon return. 

cc @scottleach-NOAA ; @johnlafargue-noaa - No one seemed overly opposed to making this change to logging the trip upon return.

**Comment by sethgerou-noaa** [comment]
I'd propose we rename the 'Missing Trip' button something like 'Log Trip" - so it's at least somewhat obvious that 'New Trip' is for a trip in the future, and 'Log Trip" is for a trip that has already happened.  If I'm a user, I don't intuitively click the "Missing Trip" button at the end of a fishing trip.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I think that is a good idea and was recommended by Kate fro her user feedback.
