### ISSUE TITLE
EM logbook: species codes

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1961]
@sethgerou-noaa 

species codes submitted via the api for logbook data, should be the 4 character alpha-numeric codes. I submitted numeric codes.  I wondering if we should flag this as an error or translate the numeric code to the 4 character alpha-numeric codes.

ex. trip 100262 spp code 206 enter, app should be showing PWHT.

![image](https://user-images.githubusercontent.com/31421964/96771308-552d8200-1396-11eb-8608-3930c6e4674c.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I believe we've coded all comparisons and expansions to use either pacfin or wcgop code interchangeably regardless of whether found on a logbook or a review, and the results doc will list both codes - so the translation doesn't technically NEED to be performed.

I could see rejecting a submission if it has the wrong kind of codes - after all, why would a logbook have wcgop codes?, but I'm hesitant to translate the number on the submitted document.  If the submitted code is a 3 digit numeric for example ( and should have been a 4 digit alpha code), how could we be certain the supplied number is a wcgop code (and not their own internal 3 digit code)?  The provider could certainly have an internal 123 code, that may or may not map to the correct wcgop code.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa that makes complete sense to not translate for those reasons. Could we flag these as an error stating it is an unexpected code or something and make it available in a report. I suspect if these are keyed in my the providers this would not be a big issue.  Haven't looked into whether this issue would impact expansion calcs.

**Comment by sethgerou-noaa** [comment]
This has been implemented
