### ISSUE TITLE
Logbook button back button does not work

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1963]
@sethgerou-noaa 

Logbook button back button does not work. To exit this screen you have to click the hamburger and go navigate back the Task Management 

![image](https://user-images.githubusercontent.com/31421964/96788826-ee659400-13a8-11eb-9fb9-b49be86ff3fe.png)

**Comment by sethgerou-noaa** [comment]
good grief that was a lot of work to track down the single line of code that needed to be changed!

**Comment by neilriley-NOAA** [comment]
sweet. works well. thanks for fixing.
