### ISSUE TITLE
EM validations

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1965]
@sethgerou-noaa  @melinashak-noaa 

Here are a couple validations that I think we need to address upon submission via the api. There are number other checks we need to do on the data, but I think that is a separate discussion on how to do this.

--
Trip returnDateTime is before   departureDateTime
Haul endDateTime is before the   startDateTime

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA do you see these as typical validations - where we would reject the submission if returnDateTime was before departureDateTime, or would we accept the submission and log an error?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa Yes, I see these as a typical validation. We check for this specific error upon data entry for observer data, so seems fitting we do the same here.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA ok, sounds good.  Time permitting on today's EM Dev call, let's see if we can come up with any other validations we might want for logbook and review submissions.

**Comment by sethgerou-noaa** [comment]
remove deliveryDate from haul details

Required - reject if missing: tripnum, source, fishery, fisherySector, 

departure date time and return date time must be in correct order

does skipperName match a valid skipper for vessel - if not put a warning in errors
update trips api fate lookups to match api docs fate lookups

in trips api docs program section add buyers link:
https://www.webapps.nwfsc.noaa.gov/apex/ifq/f?p=112:45:::NO::P45_VIEW_ALL:

if logbook is submitted with no fish ticket or fish ticket date add error to errors array - missing fish ticket

provider - reject if missing
errors for missing reviewerName, totalReviewTime, systemPerformance, catchHandlingPerformance

if have haul but missing: haulNum, gearTypeCode - reject
require details relevant to gear type
require start and end details for logbook, depth not required for em review

if have catch but missing disposition, species code,  - reject
error if fate is missing

timeOnDeck is only valid for Pacific Halibut - add error if included with any other species

**Comment by neilriley-NOAA** [comment]
Latitude > 49 degrees should be an error.

**Comment by melinashak-noaa** [comment]
Okay, just started working on this just need some clarification on a few things: 

What is fate? 

What's the difference between fishery and fisherySector? In our current model I only see fisherySector, does fishery need to be added as well? 

What are the required details for each gear type?

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa 

fate is a catch property expected on EM Review only - there's no fate validation at this point.
fate options: https://www.webapps.nwfsc.noaa.gov/trips/lookups#fate
I'll take care of the fate task for the trips api.

while the technical difference is still a little lost on me - we expect fishery on logbook, and fisherySector on em review.
fishery options: https://www.webapps.nwfsc.noaa.gov/trips/lookups#fishery
fisherySector options: https://www.webapps.nwfsc.noaa.gov/trips/lookups#fishery-sector

gearType:
if gearTypeCode is '10' or '19' - gearPerSet, gearLost, and avgHooksPerSet are required
if gearTypeCode is '1' or '2' - netType, codendCapacity, and isCodendLost are required
@neilriley-NOAA - this is what is currently implemented - would you please verify?  Looks like there are gearTypeCodes for which we don't currently require any gear details.  
**Should '4' (Danish/Scottish seine) and '3' Midwater Trawl, and '5' Other Trawl Gear be treated the same as '1' and '2'?  
Should '20' Longline (snap) be treated the same as '10' and '19'?**

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa 

Fate is the equivalent of the observer discard reason. I don't think this will impact any of the calculations.

Fishery is logged by in OTS and is part of the Trips API. Fishery Sector is essentially a subset of the fishery. For example, a vessel could have a fishery = EM EFP and a fishery sector = fixed gear whiting.

- The way we log fishery still bothers me. This is the issue I was trying to communicate the other day and wasn't getting my point across. I think we need to revisit how all this is logged. 

@sethgerou-noaa You are correct about the geartypes.
Should '4' (Danish/Scottish seine) and '3' Midwater Trawl, and '5' Other Trawl Gear be treated the same as '1' and '2
Should '20' Longline (snap) be treated the same as '10' and '19'

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa @sethgerou-noaa 
I would think any all of these validations on this ticket would be considered errors and not warnings. We can start a new ticket for new error checks and include whether any new checks are showstoppers, errors or warnings.

**Comment by melinashak-noaa** [comment]
Got it, and yes starting a new ticket with the different categories would be good.

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa 
some trips api submissions are failing with:
4|boatnet-trips-api-server-DEV  | (node:15094) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authorizedPeople' of undefined
4|boatnet-trips-api-server-DEV  |     at /opt/pm2/DEV/TripsApi/util/validator.ts:77:71
4|boatnet-trips-api-server-DEV  |     at Generator.next (<anonymous>)
4|boatnet-trips-api-server-DEV  |     at fulfilled (/opt/pm2/DEV/TripsApi/util/validator.ts:5:58)
4|boatnet-trips-api-server-DEV  |     at process._tickCallback (internal/process/next_tick.js:68:7)
4|boatnet-trips-api-server-DEV  | (node:15094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)

This is likely due to a non-existent or invalid vessel id, but the validator should return 'invalid vessel id', as it is, the validator just errors out and doesn't return anything.

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa this issue appears to be affecting all trips api catch submission.

**Comment by melinashak-noaa** [comment]
okay just fixed that, its caused when the vesselNum doesn't match up to an Id in the vessel-permission doc. Updated the code to only check captains when there is a list, if not skip this check. Probably will add some error logging around this and also a validation check on the vesselNum

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa thanks for fixing. If a captain is not in a list, we should flag these as a warning.

**Comment by melinashak-noaa** [comment]
okay got it, testing the api a bit more and think there are a few more issues I need to fix, working on them now

**Comment by neilriley-NOAA** [comment]
great. let me know when I can test. still unable to push dat via the api portal but I assume that is because fixes haven't been pushed to prod.

**Comment by melinashak-noaa** [comment]
okay you should be able to submit on the api portal now, some error messages are not showing up properly, but seth is working on that

**Comment by neilriley-NOAA** [comment]
I think I need to wait for the error messaging to work, so I know what the problem is. I just tried resubmitting an em review for trip 100249 and is failed, but wasn't clear to me as why.

**Comment by sethgerou-noaa** [comment]
I've pushed a fix to display the errors, but it requires a full build of the app, so should be available in about 20 minutes

**Comment by sethgerou-noaa** [comment]
ugh, build failed.  fixed I think.  will take another 20 minutes to know.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the messaging is working now. 

![image](https://user-images.githubusercontent.com/31421964/98169685-95662780-1ea1-11eb-9448-5dde7fc61578.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @melinashak-noaa 

The api has error for Haul level errors: 1 {"netType":["Net type can't be blank"]}
The api documentation is correctly listed as "gearTypeCode": "3"
We need to use gearTypeCode as a generic term since this field captures both trawl and fixed gear.

![image](https://user-images.githubusercontent.com/31421964/98171403-8af95d00-1ea4-11eb-8416-02379302c0aa.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the timeOnDeck is failing due to a species code issue. I think the validation is requiring speciesCode =PHLB, EM Review data will have the numeric code = 101

Catch level errors: 1 catch: 3{"timeOnDeck":["Time on deck field should be left empty except when species is of type PHLB"]}

**Comment by melinashak-noaa** [comment]
updated to remove netType check and now accepting '101' string when checking for PHLB 
https://github.com/nwfsc-fram/TripsApi/commit/69d5a6c7e55bf35a8cd9b0fc526dd573ca16ae7b

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa so just to confirm if entering  "speciesCode": 101,  are quotes required for all species code submissions or would a number be accepted without the quotes?

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA on the api portal (and TripsApi directly) either 101 or '101' should be acceptable.

**Comment by neilriley-NOAA** [comment]
perfect

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa @sethgerou-noaa 
the timeOnDeck validation is still checking for speciesCode = PHLB.  It should check for speciesCode = 101

![image](https://user-images.githubusercontent.com/31421964/98308643-69b86f80-1f7d-11eb-9bb8-a531814d8879.png)

**Comment by melinashak-noaa** [comment]
Just deployed a change to fix this now accepting species code: 'PHLB' or 101 and not '101'

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa That worked. Just successfully tested for trip 100249.
