### ISSUE TITLE
display screenshots associated with a review

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1971]
a doc of type emReviewScreenshot is written to couch, with tripNum, haulNum, timeStamp, and submissionReason properties
it may contain multiple image attachments

Example docs in: Backups/emReviewScreenshot

Screenshot API: https://github.com/nwfsc-fram/TripsApi/blob/491cca3f72a0b0754d93d669cf8240ef3279fc89/routes/index.ts#L336

**Comment by melinashak-noaa** [comment]
https://github.com/nwfsc-fram/boatnet/pull/2000
