### ISSUE TITLE
EM Task Mgt screen back buttons

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1972]
@sethgerou-noaa Once I navigate to any of the screens from EM Task Management, the back button returns you to the home screen. The back button should return the EM Task Management screen.

![image](https://user-images.githubusercontent.com/31421964/97195141-38af9200-1768-11eb-9364-e06bf99de9e8.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA please try a hard refresh (CTRL + SHIFT+ R) on the task mgmt screen - back functionality is working as you say it should for me.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa still not working

they still return to the home screen and not the EM Task Management screen

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA OK, let's spend a few minutes on the EM DEV call taking a look at this.
