### ISSUE TITLE
Elogbook "isobserved" yes/no button color

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1974]
@sethgerou-noaa 

change the "isobserved?" Yes/No button same color blue as the others in the logbook. Ex. trip 100261.

![image](https://user-images.githubusercontent.com/31421964/97218089-6fe06c00-1785-11eb-87d3-690705a90def.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA All of the 'No' buttons are darker when selected - I can change them all to the same light blue as 'Yes' if you like - but thought they more obvious when the 'No' color was different from the 'Yes' color.

**Comment by neilriley-NOAA** [comment]
Can you make them the same light blue color.

**Comment by sethgerou-noaa** [comment]
Done - should be reflected in prod in ~10 minutes
