### ISSUE TITLE
change isEM fishery lookup

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1981]
@sethgerou-noaa Please change the **"isEM" false** for the following fisheries. I think this will be cleaner and less confusing since we aren't using EM in these fisheries at this time. 

Lookup | Description | Usage | Level
-- | -- | -- | --
CA Cucumber Trawl | CA Cucumber Trawl | logbook | trip
CA Emley-Platt SFCFA EFP | CA Emley-Platt SFCFA EFP | logbook | trip
CA Fosmark EFP | CA Fosmark EFP | logbook | trip
CA Halibut | CA Halibut | logbook | trip
CA Nearshore | CA Nearshore | logbook | trip
CA Pink Shrimp | CA Pink Shrimp | logbook | trip
CA Real Good Fish Monterey Bay EFP | CA Real Good Fish Monterey Bay EFP | logbook | trip
CA Ridgeback Prawn | CA Ridgeback Prawn | logbook | trip
IPHC Directed Commercial Halibut | IPHC Directed Commercial Halibut | logbook | trip
Limited Entry Sablefish | Limited Entry Sablefish | logbook | trip
Limited Entry Zero Tier | Limited Entry Zero Tier | logbook | trip
OR Blue/Black Rockfish | OR Blue/Black Rockfish | logbook | trip
OR Blue/Black Rockfish Nearshore | OR Blue/Black Rockfish Nearshore | logbook | trip
OR Cook Midwater H&L EFP | OR Cook Midwater H&L EFP | logbook | trip
OR Pink Shrimp | OR Pink Shrimp | logbook | trip
WA Pink Shrimp | WA Pink Shrimp | logbook | trip
WC Open Access Fixed Gear | WC Open Access Fixed Gear | logbook | trip

**Comment by sethgerou-noaa** [comment]
done
