### ISSUE TITLE
Trips Screen: Create trips in PouchDB

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#20]
Throwing this your way @wsmith-nwfsc as @melinashak-noaa is focused on EDC deployment this week (and likely next as well)

**Comment by wsmith-nwfsc** [comment]
![image](https://user-images.githubusercontent.com/12972097/54468392-5f62b580-4749-11e9-9edf-735ec4877d4e.png)

**Comment by wsmith-nwfsc** [comment]
First pass at layout, still needs functionality

**Comment by wsmith-nwfsc** [comment]
Pretty awesome, trips list is completely responsive to changes on the CouchDB backend now.
![image](https://user-images.githubusercontent.com/12972097/56616888-57612580-65d3-11e9-9c22-ed73ab246781.png)
