### ISSUE TITLE
API documentation formatting

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2004]
@sethgerou-noaa Can you format the API instruction page. (see screen shot)

1. need a space row between the text and the block.
2. adjust block so we can see all the detail for Screen Shot schema.

![image](https://user-images.githubusercontent.com/31421964/98152612-dbfa5880-1e86-11eb-9972-a9ba74d8e908.png)

also add instructions for screenshot submission

**Comment by sethgerou-noaa** [comment]
added a space, added screenshot instructions
