### ISSUE TITLE
EM Review errors - Fixed Gear test trip 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2007]
@melinashak-noaa @sethgerou-noaa 

I successfully submitted EM review data for trip 100265 via the portal. There are a few bugs to resolve:

1. It stated the data submitted but there were errors. I don't see any errors listed in the "errors" tab. 
2. the species common names aren't displayed for a a few species codes

![image](https://user-images.githubusercontent.com/31421964/98179728-4675bd80-1eb4-11eb-80f5-5694c21f2029.png)

3. when a species length does not exist the field should be NULL not zero

4. No data is showing up on the data compare screen.

5.  How would I tell this is a resubmission in the UI?  Not sure if this has been built out yet?

**Comment by neilriley-NOAA** [comment]
Disregard these 2 items. This was a species code error on my part. I submitted the codes as a string and not a number.
2. the species common names aren't displayed for a a few species codes
4. No data is showing up on the data compare screen.

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa - for number 2 - string submission is correct / expected - the EM Review screen should handle string or number for speciesCode.

@neilriley-NOAA for number 4 - I caught a bug on the comparison screen - not sure whether this is what you were experiencing - but maybe I have this resolved (in PROD in about 30 minutes)

**Comment by melinashak-noaa** [comment]
1) Don't see any errors for that doc in couch. One things to note, the grey popup box that displays validation errors on the api portal page shows errors that caused that request to be rejected, that doc is not updated in couch and neither are the errors. Believe a blue box should popup when the request is accepted, but there are still errors. 
3) Fixed
5) No haven't worked on that one at all

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 

1. It's possible you saw the blue success message, which says Errors, followed by any errors, but there weren't actually any errors.
I'm adding some code to only show "Errors:  in the response message when there actually are errors.

5. I've added a revision property to the Catches model - it automatically gets incremented as new versions are submitted.  @melinashak-noaa when you get a chance, please add a revision column to EM Review table.  Note - new submissions will be revision 0 - so you may want to only display a revision number if resubmission === true.

**Comment by melinashak-noaa** [comment]
Okay added revision# here https://github.com/nwfsc-fram/boatnet/pull/2019

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @melinashak-noaa 

I  just tried to upload EM review data again via the portal for trip 100265 and doesn't appear to do anything. I did a refresh as well.

**Comment by melinashak-noaa** [comment]
Okay just deployed some changes and believe it should work now.

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa I have tested this with trip 100265.  It works.
