### ISSUE TITLE
Catch API - speciesWeight 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2018]
@sethgerou-noaa @melinashak-noaa 

Yesterday, I had logbook speciesWeight data fail to load due the weight. when speciesWeight = 1.5 it failed. I think weight should be a string and not a number.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA which screen failed to show logbook data?  need a bit more info.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa it failed to load when trying to submit via the API portal.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA  I have not been able to replicate this issue (decimal speciesWeight logbook submission via api portal fails) - have you had it happen again?  Did you get an error message specific to the weight value?

I though we had agreed numbers should be submitted as numbers, strings as strings.  
Certainly open to discussion if you like, but the value being numerical likely isn't the reason for this bug.  (decimal number speciesWeight value submissions work fine)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I can't replicate this now either. I was able to load logbook data with  speciesWeight as a number and as a sting. closing the ticket.
