### ISSUE TITLE
EM Revision count not working

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2021]
@melinashak-noaa @sethgerou-noaa 

Just resubmitted an update for trip 100249 and the revision count in Task Management did not increase. It should have changed from 1 to 2.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 

I haven't added revisions to Task Management screen yet.  I'd propose a column like errors that's like: 
Rev. LB/RV
         1/0

Wondering if we can go with an abbreviation for review that would not be confused with an abbreviation for revision.
maybe RV for review and Rev. for revision?  (and Err for error) Or other ideas for something that might be clearer?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 

I like the idea: 
Rev. LB/RV
1/0

Maybe go with RS for "Resubmission"  RV and Rev could get confusing.
