### ISSUE TITLE
PacIN species code mapping errors

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2022]
@sethgerou-noaa @melinashak-noaa 

fixed gear logbook data submission or trip 100265 has a few PacFIN species code mapping errors.

BGL1 should map to "speciesCode": "BLGL",

VALIDATION ERRORS:
fish ticket errors: {"PACFIN_SPECIES_CODE":["Pacfin species code ARR1 which maps to fish ticket 156117E is invalid"]}{"PACFIN_SPECIES_CODE":["Pacfin species code BGL1 which maps to fish ticket 156117E is invalid"]}{"PACFIN_SPECIES_CODE":["Pacfin species code BGL1 which maps to fish ticket 156117E is invalid"]}{"PACFIN_SPECIES_CODE":["Pacfin species code USRK which maps to fish ticket 156117E is invalid"]}

**Comment by melinashak-noaa** [comment]
Have a fix out for this, I'll let you know once it's deployed 
https://github.com/nwfsc-fram/TripsApi/pull/114

**Comment by melinashak-noaa** [comment]
Add nominal codes so ARR1 and BGL1 should pass, but USRK will not, still haven't even found that code in couch.

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa Is this USRK error something we need @NickShafferNOAA cleanup on his end first?

![image](https://user-images.githubusercontent.com/31421964/99011957-21133000-2502-11eb-95bd-14ba0c4fc80a.png)

**Comment by melinashak-noaa** [comment]
If this a code that should be processed then yes @NickShafferNOAA will need to add it. If its an incorrect species code then we can ignore it.

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA @melinashak-noaa 

Pacfin species code USRK is valid. It is not used by observers but could be seen in EM or on a fish ticket.

USRK = UNSP. SHARK

**Comment by sethgerou-noaa** [comment]
@NickShafferNOAA USRK catch-grouping doc does exist but has outdated "code" attribute, and is missing pacfinSpeciesCode, wcgopSpeciesCode, and isEm: true.  Please update.  I've added to the list of docs that need updating. https://github.com/nwfsc-fram/boatnet/issues/1978#issuecomment-726234140

cc  @neilriley-NOAA @melinashak-noaa

**Comment by melinashak-noaa** [comment]
closing this one for now and will continue to track on https://github.com/nwfsc-fram/boatnet/issues/1978#issuecomment-726234140
