### ISSUE TITLE
EM species weight not calculating

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2023]
@melinashak-noaa @sethgerou-noaa 

Submitted data for speciesCode = 307 and the weight didn't calculate and is not displayed.

                                 "catchId": 6,
				"disposition": "Discarded",
				"fate": "1",
				"speciesCode": "307",
				"speciesLength": 30,
				"speciesCount": 1,

![image](https://user-images.githubusercontent.com/31421964/98608721-adbeb380-22a0-11eb-82a0-a86913e9a2ad.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA which tripNum is this data for?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa tripId = 100265

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 

In expansion results I'm seeing:
"speciesWeight": "missing equation values for species: REYE"
'REYE' is not listed in the length to weight equation values, so if the species isn't in fish tickets or logbook, we're not able to calculate weight from length.

Is this an unexpected result?  Or in cases like this, should the comparison screen hide rows with no weight, or show the error in the weight column?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the row should remain visible, but I like the idea showing the error in the weight column so it is obvious. 

It is interesting this species is not in the conversion table. I was looking back at the data from last year and it appears the species shows up primarily on Logbook data as retained. I don't think we need to worry about adding it to the table as long as we flag as an error.
