### ISSUE TITLE
trips api: expect wcgop code as a number

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#2024]
- [x] - update validator
- [x] - update expansions (where necessary
- [x] - update swagger definition / openApi.yaml
- [x] - update api docs
- [x] - update typescript model

**Comment by melinashak-noaa** [comment]
checked all expansions and they are working properly, also wrote some additional unit tests just for reference. 

Currently species code comes in as a number or string. In TripsAPI keep the codes as is and validate them by calling a view in couch which returns codes as strings or numbers. Once complete, convert species codes to strings and call expansions. Then in the formatter convert numeric species codes back to numbers again, and call the couch view to log both pacfin and wcgop species codes in the results doc
