### ISSUE TITLE
TripsApi FishTicket Validation - unhandled error if fish ticket does not exist

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#2026]
4|boatnet-trips-api-server-DEV  | (node:11621) UnhandledPromiseRejectionWarning: TypeError: catchVal.fishTickets is not iterable
4|boatnet-trips-api-server-DEV  |     at /opt/pm2/DEV/TripsApi/util/validator.ts:198:43
4|boatnet-trips-api-server-DEV  |     at Generator.next (<anonymous>)
4|boatnet-trips-api-server-DEV  |     at /opt/pm2/DEV/TripsApi/util/validator.ts:8:71
4|boatnet-trips-api-server-DEV  |     at new Promise (<anonymous>)
4|boatnet-trips-api-server-DEV  |     at __awaiter (/opt/pm2/DEV/TripsApi/util/validator.ts:4:12)
4|boatnet-trips-api-server-DEV  |     at validateFishTickets (/opt/pm2/DEV/TripsApi/util/validator.ts:199:12)
4|boatnet-trips-api-server-DEV  |     at Object.<anonymous> (/opt/pm2/DEV/TripsApi/util/validator.ts:42:32)
4|boatnet-trips-api-server-DEV  |     at Generator.next (<anonymous>)
4|boatnet-trips-api-server-DEV  |     at fulfilled (/opt/pm2/DEV/TripsApi/util/validator.ts:5:58)
4|boatnet-trips-api-server-DEV  |     at process._tickCallback (internal/process/next_tick.js:68:7)
4|boatnet-trips-api-server-DEV  | (node:11621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

Observed the above error (in application error log) when submission contains a fish ticket that does not exist / can not be loaded.  I believe it's possible the fish ticket number is valid, but we do not yet have the fish ticket data, so need to allow for the possibility we just can't validate the fish ticket species.

Currently this case does not return any response - handle the error gracefully + make sure validations complete and the TripsApi returns a response.

**Comment by melinashak-noaa** [comment]
Just created a fix for this: https://github.com/nwfsc-fram/TripsApi/pull/117
