### ISSUE TITLE
EM Review view not showing some values

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2027]
@melinashak-noaa @sethgerou-noaa 

EM review data submitted for trip 100249 is not showing the values for the fields below.

Return State
Resubmission
Provider
Reviewer Name Total Review Time

![image](https://user-images.githubusercontent.com/31421964/98729206-6cd1a800-234f-11eb-8bac-dad523c55005.png)

**Comment by melinashak-noaa** [comment]
okay just updated the code those fields should show up now.

**Comment by neilriley-NOAA** [comment]
Thanks. Looks good now.
