### ISSUE TITLE
Test: Task Management displays revision count. relates to #2021

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#2031]
give the app until at least 3:30 before testing - relies on a view that's still re-indexing in prod.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa Do I have these definitions right?

VER l.b./ rv. -  Logbook version / revision count

Err l.b./ rv.  Number of errors in logbook / revision count

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 

I intended these to mean:
VER l.b./ rv. = logbook revision / review revision
Err l.b./ rv. = logbook errors / review errors

so, VER = revision, Err = errors, l.b. = logbook, and rv. = review

let me know if that makes sense or if you would like to try something else.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa these abbreviations make sense. I don't have any better suggestions at this time. unless you can format it so we can spell out Revision and Error to do something like:

Revision
l.b./ rv. 

Also, Can you center justify and format these column so there is some space between Err l.b./ rv. and the next column.

![image](https://user-images.githubusercontent.com/31421964/98982762-b7306180-24d4-11eb-906f-a08f440e7def.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the VER l.b./ rv. works for logbook. 

the Err l.b./ rv does not work for logbook errors. I submitted data for trip 100266 with a bogus fish ticket number. and the count remained at 0/0. I am pretty sure we have a check for bogus fish ticket numbers.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA 
Believe it or not '123456E' is a valid ftid (returns a row from pacfin.comprehensive_fish_ticket)- hence no error.

**Comment by neilriley-NOAA** [comment]
Oh wow. that would explain it. It does make me wonder if we should have a couple high level checks. For instance this specific ticket was from 2019 and the trip was 2020.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa resubmitted data with a bogus fish ticket. The error check and the logbook counts works properly. I still need to check the EM review submission.

![image](https://user-images.githubusercontent.com/31421964/99565178-3532b380-2980-11eb-91e7-4ad7183a655d.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa @melinashak-noaa 

EM Review - Test data uploaded for trip 10266 with bogus fish ticket. It was not flagged as an error. 

![image](https://user-images.githubusercontent.com/31421964/99574158-dc691800-298b-11eb-8b5a-1142fce6bc4f.png)

**Comment by melinashak-noaa** [comment]
Oh I have this check for logbook fish tickets, but thought people didn't submit fish ticket data for reviews. I can add these checks to reviews if needed

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa I think the reviewer may or may not submit fish tickets with review.  If fish tickets are submitted, they should be validated, but no error should be thrown if no fish tickets are provided.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  that is correct. thanks

**Comment by melinashak-noaa** [comment]
Okay fish ticket check should be working for EM review now. Tested it and seems to be working fine
