### ISSUE TITLE
Fix discrepancy between taxonomy-alias docs

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#2033]
In this EM [document](https://nwcdevfram2.nwfsc2.noaa.gov:6984/_utils/#database/master-dev/22f26efc097ff8682bf3aae78156f48a), pacfinSpeciesCode and wcgopSpeciesCode are populated as top level attributes. In this [document](https://nwcdevfram2.nwfsc2.noaa.gov:6984/_utils/#database/master-dev/22f26efc097ff8682bf3aae78156f48a), these fields are nested under taxonomy and legacy. We prefer all the documents to be similar to the EM one.

**Comment by NickShafferNOAA** [comment]
Pacfin code has been added to the docs at surface level where previously was only buried in the taxonomy sub document.
