### ISSUE TITLE
EM logbook and 3rd party review gear types

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2034]
@sethgerou-noaa @melinashak-noaa 

After polling a few data users, we decided we need to keep the NetTypeCode that is collected in the logbook. Everyone decided there really isn't a need to have these net types translate directly to the observer data. The codes that need to be added to the API lookups and logbook are listed below.  

I am wondering if we can make one field for NetType / GearType? This would allow us to include the fixed gear types in the same drop down. This is a change in gear codes. So not sure if this screw with any of the calculations.

NetTypeCode | Description
-- | --
B | Bottom or Roller Trawl
D | Danish or Scottish Seine
F | Selective Flatfish Trawl
L | Large Footrope Trawl (slope > 8" footrope)
M | Pelagic (mid water) Trawl
S | Small Footrope Trawl (slope < 8" footrope)

GearTypeCode | Description
-- | --
P | Fish pot
HL | Hook   & Line
LS | Longline   (snap)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA I'll implement the netType lookups.

Combining gear type and net type will definitely affect some of the expansions, but certainly doable if you think the single field will make logbook data entry easier.  

It does strike me that some data reports users might expect the numeric gear type along with the letter net type, even if the fields may be somewhat redundant.  If you wanted to keep both, we could have some of the e logbook net types auto populate based on gear type selection.  eg. user selects 1 | Groundfish trawl, footrope < 8 inches (small footrope), and netType is auto populated as 'S'.
Or the tripsApi could derive net type from gear type, or vice versa.  Maybe the api user supplies one of the combined letter codes to a 'gear' field, and the api automatically adds the corresponding gearTypeCode value to the submission.

@melinashak-noaa any thoughts on expansion logic impact of changing from gear type + net type to a single field that combines both?  Headache? No big deal?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 

the logbooks are going to have the net type letter code for trawl and the fixed gear logbooks have the gear type name ( ie pot, hook and line, longline snap). So my thought was to have the codes listed above. it seems confusing to me if we give them a mix of letters and numbers. looking at the data provided by PSMFC they just give the letter code to our analyst.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA

Ah, ok, didn't realize that PSMFC was already giving letter codes.

any thoughts on what to call the combined field?  It should be something different than gearType or gearTypeCode as that's an existing lookup.  fishingGear?  operationalGear?   I guess I'm really asking what the lookup docs in couch should be called - we can label the field in the tripsApi and on the e logbook whatever we like (though I'd suggest the submitted docs should probably have the same field name as the lookup docs.)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 

I guess I was thinking we would combine the existing lookup for gearType with the netType and one list of codes. Maybe we should chat about this.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA yeah, we should discuss - the existing gear-type lookup docs have observer numeric codes - unless we want to use those, we need a different lookup type for these letter codes.

**Comment by neilriley-NOAA** [comment]
I guess I am suggesting we scrap the numeric codes.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA the number gearType codes are not needed for the tablet app?  that would be a pretty big change, and affect all historical records.

**Comment by neilriley-NOAA** [comment]
Oh right, I wasn't thinking of the impacts of observer data. we should discuss. Let's discuss next dev meeting on Monday.

**Comment by sethgerou-noaa** [comment]
@BHHorness-NOAA this is the ticket discussing combined gear type and net type for em logbook and review docs.

**Comment by sethgerou-noaa** [comment]
To Do:
- [ ] add gear and net-type models
- [ ] update impacted models
- [ ] create lookups
- [ ] update openApi spec / swagger hub
- [ ] update trips api docs lookups page
- [ ] update e logbook
- [ ] update trips api validations
- [ ] update trips api catchEvaluator
- [ ] update tripsApi formatter - line 71
- [ ] update lostFixedGear, lostCodend, and discardMortalityRates expansions (where necessary)

**Comment by sethgerou-noaa** [comment]
@melinashak-noaa it does look like the discardMortalityRates expansion will require some updates to integrate the new gear and netType attributes/options.  I'll leave that to you if that's OK.

**Comment by sethgerou-noaa** [comment]
closing this ticket and making a new one for discardMortalityRates expansion update
