### ISSUE TITLE
Species grouping membership 

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#2035]
Hello, 

Few questions about species groupings. 

1) What species are associated with the groups: 
Sanddab Unid 
Shortspine/ Longspine Thornyhead

Originally I had planned to traverse the parent child links in the taxonomy-alias doc to figure out what species are associated with which group, Nick mentioned this may not be correct. So wanted to understand what's the correct way to do this and how do I get the wcgop codes associated with a group? Currently, when I was traversing the tree I only getting pacfin codes, not wcgop codes. 

2) Also how do I get the species associated with WCGOP Code: 100 Common Name: Flatfish Unid? Should I just reference the list in WCGOP Code: 3005 Common Name Flatfish Unid(IFQ) - Only IFQ flatfish species? 

@BHHorness-NOAA @neilriley-NOAA @NickShafferNOAA

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa @NickShafferNOAA @BHHorness-NOAA 

1. The THDS - Thornyhead Unspecified group is made of 2 species. 

-  Thornyhead Shortspine & Longspine Thornyhead

  Sanddab Unid is made up of; 

Longfin Sanddab	LDAB	125
Speckled Sanddab	SSDB	126
Pacific Sanddab	PDAB	137
Sanddab Unid	SDAB	136

2. WCGOP Code: 100 Common Name: Flatfish Unid should include all IFQ and NonIFQ flatfish species. If the species_sub_category was added to Couch as it was in Oracle, you could simply identify all Flatfish Unid using species_sub_category =  102 | Flatfish

**Comment by BHHorness-NOAA** [comment]
Sanddab Unid is Citharichthys in the Taxonomy documents.  @NickShafferNOAA Are the wcgop ids and Pacfin codes that Neil calls out entered in either the taxonomy docs or the alias docs for species belonging to this genus?  That is the route @melinashak-noaa was going to originally use for this.    FYI @neilriley-NOAA   Does anyone have any objections to going that route for this?

**Comment by neilriley-NOAA** [comment]
@BHHorness-NOAA it is all flatfish species.

**Comment by melinashak-noaa** [comment]
Okay got it, made a fix to use taxonomy/taxonomy-alias-by-taxonomy-id view to get pacfin and wcgop codes for children. 
https://github.com/nwfsc-fram/TripsApi/commit/b4460ba25951dc55916c1a30ae4a9fec89264321
