### ISSUE TITLE
Create haul date after return date error

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2036]
@melinashak-noaa @sethgerou-noaa 

Create a validation when haul date after return date in the logbook. This should not be possible.

**Comment by melinashak-noaa** [comment]
okay just added that check

**Comment by sethgerou-noaa** [comment]
reopening so I remember to add the validation to the e logbook as well

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa @sethgerou-noaa Not sure if this was supposed to be working, but I was able to submit data with the haul date after the return date.

![image](https://user-images.githubusercontent.com/31421964/99128083-bd027180-25be-11eb-8044-4bad0d3ebd7c.png)

**Comment by melinashak-noaa** [comment]
oh, realized I misread this, thought talking about adding a check that haul start date should be before haul end date. Okay also added a check that haul end date should be before trip return date https://github.com/nwfsc-fram/TripsApi/commit/5e5d68c73734a4566d0a0c46462df3744d5c7f69. I'll update the ticket once this fix is deployed and you can test it out
