### ISSUE TITLE
EM data error report

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2045]
@sethgerou-noaa @melinashak-noaa 

Currently, logbook and EM review errors can only be seen by looking within each individual trip. It would be helpful to have an error report that contains logbook and em review errors for all trip.  I was thinking this could be accessed from a link in the drop down after the "Data Comparison" screen.

![image](https://user-images.githubusercontent.com/31421964/99720033-f412d000-2a61-11eb-9954-ad8216df3881.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA sounds doable.  assuming this takes shape as a table, would a row be a trip with errors, or would each error be it's own row (so a single poorly entered trip could span many rows)?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I would think it would be the latter: Each error be it's own row (so a single poorly entered trip could span many rows).

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa

This looks great. Since warnings may be able to persist in the data, I am wondering if we should have a field in the report where NMFS staff would be able to acknowledge the warnings that can't be resolved. This way we know someone has looked at it. I was think thinking this could be a check box something?
