### ISSUE TITLE
Racking tool

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#2076]

**Comment by phillipbizzell-NOAA** [comment]
Here's my first attempt at the Bios module.  
**Report :** This would allow debriefers to run a few default queries or create a custom report for dissections for display or export. 
**Log Dissections:**  Checks Dissection Type, Barcode, and Rack (species/year) against data entry.  Once scanned a dissection is marked as received.  Entries in the "Rack" may need to be ordered sequentially by barcode (needs discussion).  
**Process Dissections:**  End of year processing of samples.  Table layout will depend on dissection type selection. Would love to be able to easily import data files from external labs or paste into module. Only Biospecimen admins would have access to this tab and have ability to create new racks. 
@Jeibner-NOAA please have a look at the excel sheets when you have time, would love your feedback.
[Bios mockup.xlsx](https://github.com/nwfsc-fram/boatnet/files/6580928/Bios.mockup.xlsx)

**Comment by melinashak-noaa** [comment]
Thanks Phillip, I'll take a look at this.
