### ISSUE TITLE
Patch node.js

### ISSUE THREAD

**Issue by Curt-Whitmire-NOAA** [nwfsc-fram/boatnet#2137]
@sethgerou-noaa , per request by Shane Yamamoto, please update node.js to address recent [security issues](https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/). 

If someone else on the Data Team is more appropriate to address this, please tag them.

Thanks!

**Comment by sethgerou-noaa** [comment]
on it.  will update node.js on my machine and do some testing before requesting sys admins update on Boatnet servers

**Comment by Curt-Whitmire-NOAA** [comment]
Thanks Seth. Let me know if you encounter any issues that I need to discuss with Shane. And apologies if I added tags to this issue that aren't appropriate. My first foray into opening an issue on Github!

**Comment by sethgerou-noaa** [comment]
updated dev and prod to node v10.23.1 and tested
