### ISSUE TITLE
EM Errors page - Error Type 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2154]
@sethgerou-noaa 

Trip 100263 has missing weight and counts error descriptions in the "Error Type" column. I was under the impression this column would be used for displaying the error severity (i.e. warning, error, show stopper) . These seem to be more of a description. I am wondering if we should parse these two things out?

![image](https://user-images.githubusercontent.com/31421964/106646064-133ddb80-6542-11eb-84b6-cff73bda7264.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA you are correct - this field is for 'warning' or 'show stopper'. The 'Missing Weight' and 'Missing Count' values were old data from when this was not the case.  I submitted updated data for 100263, and the only remaining error type value is 'warning' (for missing fish ticket), so I believe this is functioning as expected.

**Comment by neilriley-NOAA** [comment]
Thanks for confirming.
