### ISSUE TITLE
Allow TERs to be disabled in Optecs by setting a flag in Oracle

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#2155]
Right now I can't really disable TERs in Optecs (and still have them run against the legacy OBSPROD web app) without making code changes and rebuild.  There's currently a hardcoded python list that explicitly defines which TERs to disable.  Planning on adding a column in the OBSPROD.TRIP_CHECKS that Optecs can then pull and build that list.  Should require changes to that table in Oracle, possible reconfiguring the trigger that helps sync the table to SQLite, and adjusting the code in Optecs.

**Comment by jimfellows-NOAA** [comment]
Notes of How TERs work in Optecs:

1. The RUN TER button is on the TripErrorReportsScreen.qml, this kicks the process off 
2. On clicked, button first checks if trips need to be evaluated, if yes
3. evaluateTripchecksThenRunTER function runs, which pops the prompt for user, if user clicks yes
4. errorReports.evaluateTripChecks() runs (errorReports is an instance of ObserverErrorReports)
5. If trip_checks_are_evaluated() is false, TripCheckOptecsManager.evaluate runs (line 562 in ObserverErrorReports.py)
6. TRIP_CHECKS_OPTECS table is dropped and recreated (if it exists already)
7. TripChecksOptecsManager._evaluate_checks_on_trip runs.  This takes current trip and runs TERs pulled from TRIP_CHECKS (_OPTECS table hasn't been populated yet) with _build_trip_check_dictionary_from_trip_checks()
8. For each TER in new dict, run _evaluate_one_check
9. _evaluate_on_check injects/formats parameters, sqlparse.format https://pypi.org/project/sqlparse/ and sets execution_result to the following
	-NOT_RUN_DISABLED_IN_OBSPROD (0) if starts with TEMP, DISABLED, SEE PROCEDURE, IGNORED
	-NOT_RUN_ONLY_RUN_AT_CENTER (2) if key punch is in check message and _kp in sql statement
	-NOT_RUN_ORACLE_PLUS_JOIN (3) if (+) exists
	-NOT_RUN_HAVING_BEFORE_GROUP (4) , checked with function
	-NOT_RUN_UNRECOGNIZED_MACRO (5) if any of the hardcoded oracle functions are found in sql
	-NOT_RUN_DISABLED_IN_OPTECS (1) if check_id is in the hardcoded list of disabled TERs.  Will changed the function to take list in python, save to settings table, then use

	*there are several other checks that verify the actual SQL and handle errors when run against SQLite

10. This execution_result integer gets written to the TRIP_CHECKS_OPTECS table in SQLite.  Optecs will only run TERs with a value >= 100, so anything that gets caught up in the above logic won't get run

**Comment by jimfellows-NOAA** [comment]
Steps to adjust Oracle:
1. Add column to OBSPROD.trip_checks:

`alter table obsprod.trip_checks add (OPTECS_DISABLED INT DEFAULT NULL);`

2. Alter OBSPROD.T_TRIP_CHECKS trigger in 3 places: insert statement column declarations, insert statement value definitions, update statement column/value definition
3. Update new column with new values; take disabled trips from hardcoded python list:

```
update obsprod.trip_checks
set OPTECS_DISABLED = CASE WHEN trip_check_id in (
    1829  
    ,1496
    ,2347
    ,1482
    ,1848
    ,1917
    ,1918
    ,1922
    ,3781
    ,3821
    ,3221
    ,2137
    ,2139
    ,1498
    ,1847
) then 1 else 0 end
;
```

Forgot that this will break Optecs since SQLite table doesn't have a way to get this field on all tablets using the current sqlite db.  Could alter the trigger to also add column to applied transactions, but probably going to table this for now.

**Comment by jimfellows-NOAA** [comment]
Can get around the breaking of SQLite by manually inserting add column ddl to applied transactions first before updating the flags in Oracle.  Tested in IFQADMIN and appears to be working, column and values successfully syncing to Optecs sqlite.  Saved full script to sql directory as DISABLE_OPTECS_flag_add.sql.

**Comment by neilriley-NOAA** [comment]
@jimfellows-NOAA I suspect these changes require a change the sync procedure as well. Something to keep in mind.

**Comment by jimfellows-NOAA** [comment]
Thanks @neilriley-NOAA yea realized that after thinking up the whole flag addition idea in Oracle.  I think the biggest issue is that when we add new columns in Oracle, that change needs a way to propagate to all SQLite databases currently deployed in the field, otherwise Optecs breaks.  Essentially the update new_field statement goes into APPLIED_TRANSACTIONS and runs on SQlite where the field doesn't exist, which causes the error.  

I've been able to successfully add the field in oracle, then manually insert a row into applied transactions thats essentially "ALTER TABLE TABLE_NAME ADD FIELD_NAME INT DEFAULT NULL".  That row should get picked up by all Optecs versions on the next sync. Tested in IFQADMIN and seems to work, but I'm worried there's something I'm not thinking about, so I'll have to give it some thought, maybe run it by Eric too before anything gets deployed.  There shouldn't be any syncing back to Oracle with this table to deal with (I don't think).

**Comment by neilriley-NOAA** [comment]
@jimfellows-NOAA That's great it is working in the test db. The only other thing I can think of is the trigger. Once the column is created, the trigger will need to be updated to account for any new inserts into the APPLIED_TRANSACTIONS table (I think).

**Comment by jimfellows-NOAA** [comment]
Documented in JIRA tickets below, will build into Optecs when I get the green light from Eric etc.  Closing this out.

https://www.fisheries.noaa.gov/jira/browse/FIELD-2101
https://www.fisheries.noaa.gov/jira/browse/FIELD-2100
