### ISSUE TITLE
Dupe spp code 999

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2191]
@sethgerou-noaa There 2 entries for Unknown spp code 999. One is listed as a Catch Grouping and one as a species code. I was going to deactivate the grouping code but wanted to double check to see if this would have an impact on any calcs or have other down stream effects?

![image](https://user-images.githubusercontent.com/31421964/108532139-61feab80-728c-11eb-9cab-ad1232f394ba.png)

**Comment by sethgerou-noaa** [comment]
I've disabled the species code (Taxonomy-Alias), as the isEmExpandable flag is currently set on the Catch Grouping.  I think expansions would work correctly either way as long as one of them has that flag - That said, in this case the catch grouping makes more sense to me as the one to leave active as 999 does get expanded, which suggests a grouping.
