### ISSUE TITLE
figure out ramifications on expansions of haul level review

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#2220]

**Comment by neilriley-NOAA** [comment]
One specific use case to review: Review code for LCOD & SABL mortality rates used for EM reporting. These are fixed mortality rates.

**Comment by sethgerou-noaa** [comment]
Notes here:
https://docs.google.com/spreadsheets/d/1CTNmCk4fszPqP5VQR8G91lMAUYOE4kstrOQOhz2ZNos/edit?usp=sharing
