### ISSUE TITLE
create a mechanism to flag 25% of hauls for review.  needs to show requirement in task management.

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#2221]

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I just had confirmation from Melissa Hooper that we don't need a lot of flexibility in configuring the review rate. It does not have to be configurable by vessel, provider or some other attribute. IT would just be 25% of the hauls for each trip. This should make our lives easier.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa Melissa Hooper and McVeigh confirmed we should not follow normal rounding rules for the 25% haul selection. Instead we should always round up to the next hauls. So in a 5 haul trip we would select 2 hauls not 1.
