### ISSUE TITLE
OTS port search does not work

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2226]
@sethgerou-noaa 

The port dropdown search feature does not work. The lookup requires the user to scroll to find the port. should be able to type the name of the port in addition to scrolling. 

![image](https://user-images.githubusercontent.com/31421964/112204734-3e9f8700-8bd1-11eb-9a3b-07a6355991f0.png)

**Comment by sethgerou-noaa** [comment]
resolved
