### ISSUE TITLE
OTS sectors missing from 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2227]
@sethgerou-noaa 

The EM EFP is missing the fishery sector options.

![image](https://user-images.githubusercontent.com/31421964/112205699-47dd2380-8bd2-11eb-93e2-1a30e911b219.png)

The options available under the Federal permit option should also be available under the EM EFP

![image](https://user-images.githubusercontent.com/31421964/112205542-20865680-8bd2-11eb-8e53-122dfebc2d66.png)

**Comment by sethgerou-noaa** [comment]
resolved

**Comment by neilriley-NOAA** [comment]
I see them now. Thanks
