### ISSUE TITLE
Hide fishery code in OTS

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2302]
@sethgerou-noaa 

The fishery in OTS is displaying the fishery code next to the description. This code should should be hidden.

![image](https://user-images.githubusercontent.com/31421964/116564700-1125b780-a8ba-11eb-90f5-589cc203031d.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA no prob. - I expected at least a few of these now that I've moved lookupValue into the root of all lookups.  Please let me know of any others you come across.
