### ISSUE TITLE
How to handle wcgop ashop toggle

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#2317]
Hey Seth, just making this issue to remember to discuss the wcgop ashop toggle. Anyways, was talking to Phillip and he was saying how once a debriefer's program is set they should not have to toggle it any more. So he was thinking we could just get rid of the toggle all together but wanted to know your thoughts.

I think it would be useful for testing, but yes agree probably it's not necessary for users to view, unless maybe observers would need it. 
I was also thinking how would we set their status in the first place? Would we have to go through and create documents for each user before they logged in and set their status?

**Comment by sethgerou-noaa** [comment]
maybe we can use the isWcgop / isAshop toggles on a person/person-alias doc (observer or debriefer) after all - maybe users only see the toggle if they have both booleans set true.
