### ISSUE TITLE
OTS - move EFPs from State Permits to EFP

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2332]
@sethgerou-noaa 

Not all EFP’s are listed under EFPs...

	OR Cook Midwater H&L EFP, CA Real Good Fish Monterey Bay EFP, Emley Platt and Fosmark EFP's are listed under State permits. These are all federal EFP's and should be moved from State Permits to EFP in OTS.

@johnlafargue-noaa , @scottleach-NOAA

**Comment by sethgerou-noaa** [comment]
these have been updated per your guidance.

**Comment by neilriley-NOAA** [comment]
Looks good. Thanks

**Comment by johnlafargue-noaa** [comment]
That escalated qickly. Thanks Seth.

**Comment by neilriley-NOAA** [comment]
@johnlafargue-noaa  @scottleach-NOAA 

the OR Cook Midwater H&L EFP, CA Real Good Fish Monterey Bay EFP, Emley Platt and Fosmark EFP's EFP's still show under the Federal Permit. Just wanted to confirm these should only show under EFP?

**Comment by johnlafargue-noaa** [comment]
I believe so.  It's most intuitive to my brain.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa 

EFP's still show under the Federal Permit. These should only show under the EFP header.

**Comment by sethgerou-noaa** [comment]
Updated.  If you like, remind me some time and I can show you how to make these changes (and other similar ones) yourself from the Boatnet Management Lookups Editor.
