### ISSUE TITLE
Hide buttons on login

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2340]
@sethgerou-noaa Hide the update provider and EM roster buttons under captain mode. 

![image](https://user-images.githubusercontent.com/31421964/119712648-ab274400-be15-11eb-823b-c72086b84299.png)

**Comment by sethgerou-noaa** [comment]
Those are just placeholder buttons until SDM gives an estimate of how often we need to check for new providers and vessel associations.  Once we know that, the buttons will go away and we'll implement automatic roster updates.

**Comment by neilriley-NOAA** [comment]
Got it. Thanks

**Comment by sethgerou-noaa** [comment]
if you need to make screen grabs of the home page the best option would to turn off all your roles except 'captain' - and I can turn them back on when you're done.

the captain mode and observer mode toggles would/should not be visible to a captain.

or we can photoshop out the toggles. :)

**Comment by neilriley-NOAA** [comment]
No need you can just leave as-is

**Comment by sethgerou-noaa** [comment]
sounds good
