### ISSUE TITLE
Connect Trino Query Engine to Oracle 19C with JDBC url

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#2353]
So far I've been unable to connect to our IFQ database with Trino.  I have been able to connect to our postgresDB, and my local Oracle Express test environment all from within a container using the default trino image: https://hub.docker.com/r/trinodb/trino.  I've used the oracle catalog connection configs provided by trino documentation with no results. 

https://trino.io/docs/current/connector/oracle.html

The catalog is recognized, but query hangs until I receive the error message: 

`IO Error: The Network Adapter could not establish the connection`

The host url is pingable within the container, and I've been using the parameters copied directly out of my TNS names file on my local machine for Oracle connections.  Not sure if this is a configuration on the Oracle side.  Similar JDBC setup with SQuirrel client hasn't had a problem.

I already have mongo connected, so making this connection will open up the ability to join our oracle data set with our ETL'd mongo data, and do some serious QA/QC.

**Comment by jimfellows-NOAA** [comment]
attempted jdbc:oracle:thin:@example.net:1521/ORCLCDB format, and put entire TNS description, both still not working.

**Comment by ericbrasseur-NOAA** [comment]
possibly an issue with the vpn?  The IFQ is not public facing.

**Comment by jimfellows-NOAA** [comment]
VPN shouldn't be an issue, the server to set this up is on the internal network and I'm able to ping the oracle host.  It does seem to be some sort of networking issue, I'm guess on the oracle side, but could be wrong there.  A few articles with some ideas:

http://www.dba-oracle.com/t_network_adapter_could_not_establish_connection.htm
https://stackoverflow.com/questions/12574414/io-error-the-network-adapter-could-not-establish-the-connection
https://stackoverflow.com/questions/24127839/oracle-sql-developer-failure-test-failed-the-network-adapter-could-not-estab

**Comment by jimfellows-NOAA** [comment]
Firewall issue here, had IT (Marcus) allow communication between our dev server and the oracle server.  Containerized Oracle connections and connections straight from the dev server OS are now open and working.
