### ISSUE TITLE
API species code validation error

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2362]
@sethgerou-noaa the api errors out saying that a numeric species code needs quotes. assuming the quotes only should apply to the Pacfin codes?

![image](https://user-images.githubusercontent.com/31421964/123182499-71f9e800-d444-11eb-859f-dead7f1b99de.png)

**Comment by neilriley-NOAA** [comment]
successfully submitted data for tripId 100308. however the species weight is not displaying in the EM data screen. there for nothing is displaying in the data comparison screen. 

![image](https://user-images.githubusercontent.com/31421964/123868924-313b1c80-d8e5-11eb-9d25-a790b0dc2c79.png)

**Comment by sethgerou-noaa** [comment]
was submitted as 'speciesweight', but needs to be 'speciesWeight'.
I changed the attribute in the couch doc and can see the weight on the EM Review screen now.

**Comment by neilriley-NOAA** [comment]
duh. case sensitive...should have caught that.

**Comment by neilriley-NOAA** [comment]
any thoughts on why nothing is displayed in the data comparison screen?

**Comment by sethgerou-noaa** [comment]
probably needs to be resubmitted with a speciesWeight value so expansions and groupings re-run.  I just changed the couch doc so it would display as review data.

**Comment by neilriley-NOAA** [comment]
just reloaded data but still not displaying the data comparison screen for trip 100308
