### ISSUE TITLE
add "provider" to logbook json example

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2365]
@sethgerou-noaa the "provider" field is missing from the logbook json example in the app.

![image](https://user-images.githubusercontent.com/31421964/123316259-7de7b780-d4e1-11eb-8afa-ee20dfb242d5.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa. this change looks fine. correct me if I am wrong but we would not be able to identify the person (3rd party staff person) that submitted the data?  Wondering if we need to add review name?

**Comment by sethgerou-noaa** [comment]
We expect reviewerName in submissions - we also store the boatnet username of the boatnet account that submitted the data to the api.  https://github.com/nwfsc-fram/boatnet-module/blob/master/bn-models/src/models/trips-api/catches.ts

I'd think reviewerName would be the more reliable means of determining who submitted the data as a 3rd party provider could elect to use a single boatnet account to link all their software to the tripsApi.

This is another case where it would be useful to have a listing of required logbook fields and required review fields.

**Comment by neilriley-NOAA** [comment]
Agreed. I am working on a listing of required logbook fields and required review fields today.
