### ISSUE TITLE
Elogbook not displaying catch weight and count 

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2371]
@sethgerou-noaa any logbook weights and counts submitted via the api are not displayed in the app.

![image](https://user-images.githubusercontent.com/31421964/123441774-12f1bb80-d589-11eb-895a-0c0a22a73980.png)

**Comment by sethgerou-noaa** [comment]
what trip # is this?

**Comment by neilriley-NOAA** [comment]
100309

**Comment by sethgerou-noaa** [comment]
Ah, these need to be submitted as 'speciesWeight' and 'speciesCount'.

Not sure how we want to handle validation - these fields are not required currently, as there are cases where either one of the values is not required / can't be supplied.  Also, It could get tricky to check for incorrect attribute names nested inside arrays.

**Comment by neilriley-NOAA** [comment]
so the example json in the EM API Portal is not correct. Can you update the example json so others don't run into this issue. since these aren't required, I am not sure how to validate. can we start with rejecting data that has a field name that doesn't match the api?

**Comment by sethgerou-noaa** [comment]
I've updated the examples.  

I'll need to think/research  a bit on how to reject field names that don't match the api - unfortunately most validation seems to be meant to validate the values, not the fields.

**Comment by neilriley-NOAA** [comment]
Looks good. Thanks.
