### ISSUE TITLE
EM Review screen not displaying data

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2381]
@sethgerou-noaa data is not displayed upon clicking on the EM review" link. It is blank until you hit enter. data should be displayed when the page is opened.

![image](https://user-images.githubusercontent.com/31421964/123871611-b4aa3d00-d8e8-11eb-9fdc-873fb8ab4662.png)

**Comment by sethgerou-noaa** [comment]
should be working now - likely need to do CTRL + SHIFT+ R to get/use new code.
