### ISSUE TITLE
OTS calendar bug when creating trip

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2388]
@sethgerou-noaa 

Trying to create a new trip from my laptop. The "done" button is hidden, when the browser is at normal 100% zoom. THe calendar doesn't appear to scale to the level of zoom.

![image](https://user-images.githubusercontent.com/31421964/124813364-a6c46f80-df19-11eb-9cc8-1502fbcb7802.png)

**Comment by sethgerou-noaa** [comment]
should be fixed now

**Comment by neilriley-NOAA** [comment]
looks good
