### ISSUE TITLE
add EM logbook error

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2392]
@sethgerou-noaa Add error when EM logbook data fishery is anything other than the active fishery lookup options:
Example trip is 100316

<html>
<body>
<h5 id="fishery" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 500; line-height: 1.2; font-size: 1.25rem; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;">field: </span><span style="box-sizing: border-box;">fishery</span></h5>

Lookup | Description | Usage | Level
-- | -- | -- | --
Electronic Monitoring EFP | Electronic Monitoring EFP | logbook | trip
Limited Entry ITQ EM | Limited Entry ITQ EM | logbook | trip
Limited Entry Sablefish Fixed Gear EM | Limited Entry Sablefish Fixed Gear EM | logbook | trip

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by sethgerou-noaa** [comment]
previous validation just required fishery value to be a valid fishery - I've updated to require fishery to be an active EM fishery

**Comment by neilriley-NOAA** [comment]
tested with trip 100319. works well.
