### ISSUE TITLE
EM Results Page not displaying review data

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2400]
@sethgerou-noaa EM Results page is not displaying the  results for EM review data. example 100319 in Prod.

![image](https://user-images.githubusercontent.com/31421964/126536791-7e0b0b50-b8fe-4450-bb50-6deba5432cb5.png)

**Comment by sethgerou-noaa** [comment]
Weird, I'm seeing Rows.
![image](https://user-images.githubusercontent.com/38139361/126720427-e295f4ae-8fa1-4871-8dd6-0aebe41614ac.png)
Are you seeing the review rows now?

**Comment by neilriley-NOAA** [comment]
This is displaying records. I guess I was hung up on the redundancy in some of the values. for my own understanding, is the the "IFQ Reporting" section display the final result that is debited from the vessel accounts?

**Comment by sethgerou-noaa** [comment]
Yes, those are the values that would get written to the staging table.

**Comment by neilriley-NOAA** [comment]
Thanks. Closing ticket.
