### ISSUE TITLE
EM Review page not displaying "timeOnDeck" field

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2401]
@sethgerou-noaa EM Results page is not displaying the timeOnDeck" field for EM review data. example 100319 in Prod.

![image](https://user-images.githubusercontent.com/31421964/126536791-7e0b0b50-b8fe-4450-bb50-6deba5432cb5.png)

**Comment by sethgerou-noaa** [comment]
added a Time On Deck column

**Comment by neilriley-NOAA** [comment]
I see it now
