### ISSUE TITLE
EM fish ticket error bug

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2402]
@sethgerou-noaa the fish ticket error is not calculating correctly. I suspect this is an issue with the time submitted with the fish ticket date. The time shouldn't be factored in since only a date will be submitted. Initially, I though this may be related to the time zone but I resubmitted test data without a time or accounting for the time zone and the error still triggered. example trip 100323

![image](https://user-images.githubusercontent.com/31421964/126685001-b7e550ae-c341-4cb3-9919-7b46b6ddc730.png)

**Comment by sethgerou-noaa** [comment]
just to confirm, we're just talking about error # 2 in the screen shot, correct?

**Comment by neilriley-NOAA** [comment]
That is correct

**Comment by sethgerou-noaa** [comment]
should be resolved now

**Comment by neilriley-NOAA** [comment]
looks good.
