### ISSUE TITLE
fate should not be required for a retained catch

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2409]
fate should not be required for a retained catch. The API currently required fate for retained catch from the third party.

**Comment by sethgerou-noaa** [comment]
made 'fate' validation for disposition = 'Discarded' only.

**Comment by neilriley-NOAA** [comment]
This isn't working correctly. I was able to submit review data for a fixed gear trip 100325. should be rejected at time of submission.

**Comment by sethgerou-noaa** [comment]
Are you saying there should be a validation that dis-allows 'fate' on retained catch?  I thought you just didn't want it required for retained.

**Comment by neilriley-NOAA** [comment]
Yes, correct we should reject data at the time of submission when 'fate' exists for a retained catch. fate is specific to discarded catch.
