### ISSUE TITLE
fixed haul error for Start date time on fixed gear trip

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2411]
Start date time for a haul may occur before the start of a trip. Often a vessel will set gear on the previous trip and retrieve on the next one so this scenario should not prevent the upload of data.

Haul level errors: haul# 1 {"startDateTime":["Start date time must occur after trip departure date time: 2021-07-18T04:00:00-08:00 and before haul end date 2021-07-18T18:19:00-08:00"]}

**Comment by sethgerou-noaa** [comment]
so the updated validation would be something like: 
haul start date time can not be before trip start date time if gear is 'trawl' or 'hook & line'.  
(so haul start date time before trip start date time is not an error for 'fish pot' and 'longline (snap)') 

Is that correct?

**Comment by neilriley-NOAA** [comment]
nope. haul start date time can not be before trip start date time if gear is 'trawl' only. H&L could be deployed prior to the start of the trip.

**Comment by sethgerou-noaa** [comment]
ah, ok.  got it.

**Comment by sethgerou-noaa** [comment]
removed the haul start can not be before trip start validation for everything but trawl

**Comment by neilriley-NOAA** [comment]
tested trawl trip 100327 and FG trip 100329
