### ISSUE TITLE
add auth/login

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#248]

**Comment by sethgerou-noaa** [comment]
getting an error - suspect it's related to failed lerna run build - will have Will take a look.

**Comment by wsmith-nwfsc** [comment]
Can take a look- is there a branch with the problem?
(also, be sure to run "lerna bootstrap" and "lerna clean -y" when you see or make changes to package.json; I just run it whenever I pull down master)

**Comment by sethgerou-noaa** [comment]
yeah, my process was, lerna bootstrap, lerna clean, lerna run build with my code (built ok),
then I checked out and pulled master, switched back to my branch, merged master and repeated the lerna steps, then received a build failure.

the obs-web branch on github should be exactly where I'm at.

**Comment by wsmith-nwfsc** [comment]
I got it to build by changing line 153 in OTSManagement.vue to:
```
    private currentTarget: any = undefined;
// or
// private currentTarget!: any;
```
(you had it untyped)
