### ISSUE TITLE
Populate CouchDB with EM EFP vessels

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#264]

**Comment by sethgerou-noaa** [comment]
Is this the complete list?
Alyssa Ann, Blue Pacific, Brita Michelle, Buck  & Ann, Donna J, Fishwish, Little Joe, Moriah Lee, Pioneer, Southeast, Timmy Boy, Alex, Cape Windy, Joy Ann, Last Straw, Mr. Morgan, Noahs Ark, Chellissa, Miss Moriah, Pacific Bully, Madeline, Steve C.
Will verify with Neil.

**Comment by toddhay-NOAA** [comment]
@neilriley ?
