### ISSUE TITLE
Push ETL OBSPROD data to Central CouchDB Server

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#267]

**Comment by wsmith-nwfsc** [comment]
@Mak-NOAA this will be the data you need to start creating your CouchDB views.

**Comment by NickShafferNOAA** [comment]
Ran an initial bulk pull, data now exists in CouchDB ready to be worked with and tested against for most stuff. Data should be up-to-date as of today (April 17th, 2019). 

Since many changes have been made to the code, I'm going to be re-testing the daily update process against a separate test database for the next week or so before switching to run it against master-dev.

**Comment by toddhay-NOAA** [comment]
Great work and news on this @NickShafferNOAA .  I'm curious, how long did the bulk transfer take anyways?

**Comment by NickShafferNOAA** [comment]
The process takes about an hour and a half from start to finish, including the initial loading of the tables into memory.

**Comment by wsmith-nwfsc** [comment]
Gloriously 266 MB!

**Comment by wsmith-nwfsc** [comment]
Duplicated as master-dev, and replicating (some) lookups to lookups-dev via a replication filter. Also made lookups-dev readonly no non-admins via a validation_function. #305

**Comment by NickShafferNOAA** [comment]
A lot of the views on the lookup data right now might be worthless outside the scope of the ETL, as the key used on those is the legacy value used for lookups in the old system. I still need to rename those those to better communicate they're for ETL use.

**Comment by wsmith-nwfsc** [comment]
To start with, I've just started to make a few in the optecs_trawl design document, so I won't mess with the ones you've created.

**Comment by NickShafferNOAA** [comment]
Going to close this now since the bulk initial data is in Couch and there's already a ticket open for recording issues.
