### ISSUE TITLE
Create Persons / Roles / Org Management Module

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#281]
For OBS-Web, we need to create a module for managing the persons, roles, and organizations.  This will interface with the RESTful-wrapped ApexUserAdmin functions for adding/editing/deleting users/roles/applications.

**Comment by toddhay-NOAA** [comment]
This is dependent upon:

https://www.st.nmfs.noaa.gov/jira/projects/BOAT/issues/BOAT-7 - Wrapping ApexUserAdmin functions
https://www.st.nmfs.noaa.gov/jira/projects/BOAT/issues/BOAT-8 - Determining boatnet roles

**Comment by sethgerou-noaa** [comment]
stale - essentially done
