### ISSUE TITLE
Observer Assignment Screens - Design

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#293]

**Comment by sethgerou-noaa** [comment]
is this basically a list of trips with no assigned observer, where a staff person can click a trip and add an observer?

**Comment by toddhay-NOAA** [comment]
Yes, something like that @sethgerou-noaa.  I'm guessing it will have some more functionality to it as well, so we should discuss as a group.

**Comment by toddhay-NOAA** [comment]
Table containing columns of:
- Vessel name
- Captain
- Captain Phone Number
- Trip Start Date
- Trip End Date
- Fishery
- Departure Port
- Observer Name
- Selection Status

Show current year of trips + December of previous year
Two Tables
- Action Required
  -- Selected, Unassigned
  -- Sort by:  Closed Start Date to today at top
- No Action Required

Filter Toggle Buttons - Two toggle buttons - Show:  Selected Trips / Non-Selected Trips
