### ISSUE TITLE
Error in creating CouchDB view: "The request could not be processed in a reasonable amount of time."

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#306]
I tried creating an all-catch and all-catch-species view in master-dev CouchDB, but hit the title error.  Google doesn't reveal much.

**Comment by toddhay-NOAA** [comment]
Reference: https://github.com/apache/couchdb/issues/1301

**Comment by wsmith-nwfsc** [comment]
This is normal. From an email I sent to Nick a while ago:
```
 Notice that for these big DB's, the Fauxton UI will say "Timed out before a reasonable request could be made" when you create these mega-views. It's just a UI error, and the view is still being created in the background, so give it a few minutes, and then refresh the page, and the view should be created. 
```

**Comment by toddhay-NOAA** [comment]
Perhaps, although the data still isn't there this morning in master-dev > MainDocs > Views > 

all-catch  or   all-catch-species

**Comment by wsmith-nwfsc** [comment]
Looks like those views return 0 docs. Taking a look.

**Comment by wsmith-nwfsc** [comment]
A view can only return 2 things, a key and value. So this is incorrect syntax:
```
 emit(doc.disposition, doc.weightMethod, doc._rev);
```

Instead, it needs to be:
```
 emit(doc.disposition, { weightMethod: doc.weightMethod, _rev:  doc._rev)};
```

**Comment by toddhay-NOAA** [comment]
interesting, they are looking for `wcgop-catch` and `wcgop-catch-species` types, but maybe those don't properly exist yet.

**Comment by wsmith-nwfsc** [comment]
It might be more helpful to practice on the lookups-dev, which right now just contains 4 data types:
```
 LOOKUP_TYPES = [\"program\", \"species\", \"port\", \"vessel\"];
```

**Comment by toddhay-NOAA** [comment]
interesting,  not sure what we should be using for our keys in these views, but I guess we just shove all of the results into the value json object.

**Comment by toddhay-NOAA** [comment]
closing this one out.
