### ISSUE TITLE
OBSPROD > CouchDB ETL Fixes

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#307]
Please capture all fixes that need to be made for the OBSPROD > CouchDB ETL process here:

- [x] wcgop-operation should include catches of type wcgop-catch, not catch
- [x] Gear type / performance lookup not implemented
- [x] catch disposition lookup not implemented
- [x] catch / operation weight method lookup not implemented
- [x] uploadedDate property missing

All
- [x] trim all fields to remove extra whitespace
- [ ] migrate createdBy, updatedBy to email addresses once available
- [x] migrate wcgop users and contacts to persons model (see #262)
- [x] modify all date/times to be local timezone (using moment timezone library)
- [x] updated all LB weights to lbs
- [x] Trim legacy data from sub-documents
- [x] createdDate still shows zulu times, not local
- [ ] some numbers are having decimal places randomly added (ex: 2.3 turns into 2.3000000000000003)

Trips
- [ ] migrate trip captain to a person record
- [x] isPartialTrip should be boolean, not a string
- [x] fishery value should be coming from the LOOKUPS table, LOOKUP_TYPE = fishery
- [ ] tripStatus - expand document store to include open, closed, debriefed and also future, deployed, not checked, checked with errors, final review, closed
- [x] program - include only _id and name
- [ ] certificates - add these from permitNum or licenseNum from TRIPS table
- [x] fishTickets - add these
- [x] crewSize - add
- [x] fishingDays - add
- [x] firstReceiver - this comes from the OBSPROD.IFQ_DEALERS table
- [ ] waivers - points to OBSPROD.WAIVERS table
- [x] intended_gear_type is missing
- [x] add sightingEvents

Hauls
- [x] fishing locations missing

CatchSpecies
- [x] Trim species records down to _id, common name, scientific name
- [x] write out basket data
- [ ] write out specimen data

SightingEvents
- [x] Collapse confidence down to include only _id and description
- [x] Collapse beaufort down to include only _id and description
- [x] Collapse sightingConditions lookup
- [x] Collapse bodyLengthEstimate lookup

NOT DOING THESE
- [x] vessel should only contain _id, vessel name, and coastGuardNumber / state Reg Number
- [x] departurePort, returnPort should only include _id, name and state

**Comment by wsmith-nwfsc** [comment]
I think you know this, but our models should reflect the `type` used in our database.
For example, `wcgop-catch.ts` declares the type here:
```
export const WcgopCatchTypeName = 'wcgop-catch';
```
We might have missed this `XxxYyyyTypeName` export on a few models, so you'll want to fill those out.

**Comment by NickShafferNOAA** [comment]
Thanks for making this ticket, I just already found a couple things myself. Gonna fix these and scour for more small issues I might've missed.

**Comment by NickShafferNOAA** [comment]
I finally discovered the issue to the "missing" wcgop-catch-species data. The basket and dissection data was never missing as I thought it was. It was in fact being migrated over, the issue was with my view on couch to validate the data's existence. 

For some reason that I do not currently understand, adding an Array.isArray(foo) check on the nested arrays in the view before looping/accessing them fixed the issue. Removing this check limits the emitted docs. About ~80% of the documents in which the dissections/baskets are valid arrays are still ignored without this check.

@wsmith-nwfsc Any idea why this might cause such behavior?

**Comment by wsmith-nwfsc** [comment]
I'm not sure from your description, which database and view is this specifically?

**Comment by NickShafferNOAA** [comment]
In the views-test database, the hauls-with-baskets view correctly returns 83 documents right now that contain basket data, but if the If statement on line 8 is taken out, it only returns 21. I am uncertain as to why removing this check will keep some of the documents from being emitted properly

**Comment by wsmith-nwfsc** [comment]
Ok, a few suggestions. I created a views-test-wsmith with a working version, https://nwcdevfram2.nwfsc2.noaa.gov:6984/_utils/#database/views-test-wsmith/_design/views/_view/hauls-with-baskets

- Use forEach
- If you just want to see if >1 basket exists, you can emit then immediately return. No need to keep a boolean and iterate through the rest of the records.
- If you want to count interesting stuff, and only return records with baskets, it could look like this:
```
function (doc) {
    if (doc.type === 'wcgop-operation' && doc.catches) {
        var numCatches = doc.catches.length;
        var numSpecies = 0;
        var numBaskets = 0;
        doc.catches.forEach( function (cat) {
            if (cat.species) {
                numSpecies += cat.species.length;
                cat.species.forEach( function (species) {
                    if (species.basket) {
                        numBaskets += species.basket.length;
                    }
                });
            }
        });
        if (numBaskets > 0) {
            emit(doc.legacy.fishingActivityId, {numCatches: numCatches,
            numSpecies: numSpecies, numBaskets: numBaskets});
        }
    }
}
```

**Comment by wsmith-nwfsc** [comment]
Note that I use 'cat' instead of 'catch' because `catch` is a reserved keywork in JS

**Comment by NickShafferNOAA** [comment]
I did not think to remember catch was a reserve keyword, and those nested functions look more concise than what I was doing previously. Thanks for the help. I still don't understand why the valid arrays were being passed over without the array check before, though I guess it doesn't matter so long as the issue no longer happens.

**Comment by wsmith-nwfsc** [comment]
I think it was just a logic issue. With that Array.isArray statement, you were basically just checking doc.catches !== undefined.

```
if(Array.isArray(doc.catches)){ // This verifies that doc.catches is defined
        for(var i = 0; i < doc.catches.length; i++){ // doc.catches.length will return a value
```
Versus:
```
        for(var i = 0; i < doc.catches.length; i++){ // doc.catches.length will "crash" because doc.catches is undefined, and the whole function will not run.
```

**Comment by NickShafferNOAA** [comment]
Moved this to "done". Created a few tickets from what was left here. Will create new ones as issues pop up instead of doing these check boxes.
