### ISSUE TITLE
User Config / Manage Users - should I build these out to read and write from the database?

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#369]

**Comment by sethgerou-noaa** [comment]
@toddhay-NOAA   cc: @wsmith-nwfsc 

Should I build out Obs-web User Management and/or User Config, or back-burner for now?  
I need some level of User Config sooner rather than later so I can store a Captain's active vessel, and a user's notification preferences.

Do we still have ?s about what we will store in our Person records vs. what's in APEX User Admin.?

**Comment by toddhay-NOAA** [comment]
so I think the ink has dried on the Person model in terms of what we'll store in there versus in ApEx User Admin.  

If you need this for OTS, go ahead and start building it out.  My only request is to keep an open mind on this one in the sense that we would like to use this for all of the Obs-Web user management and not just OTS, so try to think beyond OTS a bit here.

**Comment by sethgerou-noaa** [comment]
I take it you mean, build an exhaustive tool, that can handle all the User/Person details one might want to view, update, yeah?  Will do!

Looks like we're handling roles in Apex User Admin,
as the Person model just has: 
  type ApplicationRole = string; // TODO Lookup - match ApEx User Admin

I'm curious how we access/use/manage roles, but I guess I don't need to know right this moment.

What I do need is a means to look up the person record for the current logged in user.  
From dev-auth-server, I only see a username, hashedPW, roles, and couchDB info
- Do I get more from ApEx User Admin?  
- Should we store the ApEx User Admin username as part of the Person record?  Another reference?

**Comment by toddhay-NOAA** [comment]
So our goal is to build out some screens for doing the user management in Obs-Web, but we don't have that in place right now, instead someone has to login to the ApEx app to handle that, but I want it integrated into our UI.  

We have not actually generated the Persons records yet, that is on the ToDo list for @NickShafferNOAA .

I think ApexUserAdmin only gives you back a validated yes/no response and then @wsmith-nwfsc wraps that with the auth server, but he can explain that better than me.

**Comment by toddhay-NOAA** [comment]
some more food for though on this @sethgerou-noaa.  I would actually like for you to build out this User Config/Management as a bn-persons module under the libs folder.  I want to be able to reuse this module in other, non-Observer applications as well.
