### ISSUE TITLE
User DB Replication - How to accomplish?

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#400]
In talking with Shane, it sounds like this is an open question as to how the replication will occur for the user databases.

**Comment by wsmith-nwfsc** [comment]
The method that makes the most sense, I think, is to have the auth server configure the replication tasks for the user DB's.

**Comment by wsmith-nwfsc** [comment]
We decided that the auth server method would be problematic, and are going in favor of the couchdb built-in clustering.
If that fails for some reason, then we could try the auth server configuration method.
