### ISSUE TITLE
Create jenkins job for deploying auth server to dev and production

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#407]
Please create two separate jobs on the production jenkins:

- [x] Development
- [x] Production

**Comment by wsmith-nwfsc** [comment]
I now have this deployment pipeline fully functional across my two local VM's, one is running Jenkins, and the other as the web server (just has node 10 and pm2 installed on it) 
Using Jenkins plugins, the scripting here is very minimal, so we're just pending having pm2 run as we hope on nwcdevmeow1.
I've written up all the steps I did on my local VM's to get this up and running, and will translate into final docs for the auth server, obs-trips, obs-ots.

![image](https://user-images.githubusercontent.com/12972097/59077379-3a389b80-888f-11e9-8ce6-a5c54c46d104.png)

Jenkins plugins used:
* Copy Artifact Plugin
* Delivery Pipeline Plugin (optional but nice to have, shown above)
* Publish Over SSH

**Comment by wsmith-nwfsc** [comment]
Full pipeline to Dev now running for Auth, document created for Prod
