### ISSUE TITLE
Fix issues on boatnet table page

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#426]
you probably see this too on trips/ trip details, probably worth tracking down what's going on there 
![](https://lh3.googleusercontent.com/-kgdy_1tLWeY/XOcilxBcJ8I/AAAAAAAACOQ/Sely4JUqWQA2Wd--UuW3-t5bKP36ssGvQCK8BGAs/s0/2019-05-23.png)

**Comment by melinashak-noaa** [comment]
currently don't see this issue any more. i'll keep it open for now, but believe it may be a non-issue

**Comment by toddhay-NOAA** [comment]
Go ahead and close it and reopen if it reoccurs.

**Comment by wsmith-nwfsc** [comment]
I think I fixed  (at least part) of this, if I'm thinking of the same thing in #481
