### ISSUE TITLE
Create Edit button + dialog popup for changing selected cell values

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#431]

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  this was quite difficult ...being able to create an editable qasar table with dynamic columns (basically the columns selected on the trips tab). I don't have any functionality yet to talk to couchdb. Assuming it looks good, I'll need some time with @sethgerou-noaa or @wsmith-nwfsc to figure out how to update couchdb.

For now share your thoughts:
<img width="675" alt="Screen Shot 2019-06-29 at 9 33 05 PM" src="https://user-images.githubusercontent.com/20570382/60392352-8b663480-9ab5-11e9-8e14-3c38068cb29d.png">

I think we need to ask the users which columns they want editing before going any further.

I also assumed that if the user wants to edit for example Trip status in row 1 and Vessel in row 2, I will show Trip status and Vessel for both row 1 and row 2 in the dialog box.

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, for the Edit + popup, I'm envisioning it where a user has selected 1 or more cells of a given column, then she or he clicks the Edit button, and up comes a dialogue box.  Here is a mockup of what I envision the editing box to look like:

![BulkEditing](https://user-images.githubusercontent.com/29761374/60465301-a34cce00-9c05-11e9-8a65-2c303d413856.png)

Also, the current column doesn't look very good from a user's perspective, as when I'm dragging down the Vessel column (in this example), it highlights all of the other columns around it and doesn't actually highlight the cells that I've already touched.  We want this to have a look and feel like MS Excel where one can swiped down a column and the cells are highlighted as you move down the column and do not do anything with the other columns.  

Here is how it currently looks:

![CurrentColumnSelection](https://user-images.githubusercontent.com/29761374/60465580-4d2c5a80-9c06-11e9-894e-3c433b656bbd.png)

Yet this is how we want it to look:

![SelectCells](https://user-images.githubusercontent.com/29761374/60465676-8a90e800-9c06-11e9-893d-07722cd08280.png)

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA what happens when a user selects more than one column and clicks Edit? The dialog box just picks one of the columns?

**Comment by Mak-NOAA** [comment]
Also I'm not sure how we can replicate Excel as we are already doing mousedown and mouseup. Let me know if you have any suggestions there.

**Comment by toddhay-NOAA** [comment]
The active column would be the column where the user initiated the mouse down event, so that would be the one shown in the dialog box.

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA it's possible to select more than one column. So there is no concept of "active" column. So I can select 3 vessels and 2 trip statuses. Do you want me to recode it so that selection is only limited to one column at a time?

**Comment by toddhay-NOAA** [comment]
The column where the user initial clicks the mouse button would be the column shown in the edit dialog.

**Comment by toddhay-NOAA** [comment]
I want it to be such that only that initially selected column is highlighted, even if the user wanders away from that column while he or she still has the mouse button clicked and is holding it down.

**Comment by Mak-NOAA** [comment]
so if user highlights column A and then decides to highlight and select column B, column A gets unselected?

**Comment by toddhay-NOAA** [comment]
so if a user first highlights some cells in column A, but then decides, you know what, I meant column B.  He or she would then click on the appropriate starting cell in column B, move the mouse up or down to select the cells of interest, and then release the mouse click.  The previously highlight Column A cells would be unlighted the moment that he or she started highlighting the column B cells.

**Comment by Mak-NOAA** [comment]
Got it, ok so we're doing one column at a time.

**Comment by toddhay-NOAA** [comment]
Yes, definitely one column at a time.

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA the front is done, for the purpose of this ticket, are we doing backend too? I think I'll need some time with Seth/Will for actual couchdb updates. 

I do wish there was a better way to get the actual column Value dynamically instead of a switch statement here: https://github.com/nwfsc-fram/boatnet/blob/master/apps/obs-web/src/views/DebrieferTrips.vue#L444 
a workaround is to have the "Previous Value" row to always say "Multiple"

**Comment by toddhay-NOAA** [comment]
The edit button is not working, giving me a bunch of errors:

![Errors](https://user-images.githubusercontent.com/29761374/60628609-117cc680-9da7-11e9-88da-de85dce9413e.png)

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA try again

**Comment by toddhay-NOAA** [comment]
looks good @Mak-NOAA , closing...
