### ISSUE TITLE
Add column-level filtering above each shown column

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#432]
We want the ability to show text boxes above each table column, such that when a user types in it, it auto-filters the values in that particular column

**Comment by toddhay-NOAA** [comment]
@melinashak-noaa - I wonder, perhaps we should bake this into the BoatnetTable that you've built as an option for showing/hiding these filter text boxes, so then we can reuse these across any of our BoatnetTables

FYI:  @sethgerou-noaa , @wsmith-nwfsc

**Comment by toddhay-NOAA** [comment]
an example of this is here:  https://datatables.net/extensions/fixedheader/examples/options/columnFiltering.html

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA did you mean that you want the data filtering capability of Data Tables to be created for Quasar?

**Comment by Mak-NOAA** [comment]
I posted this question in Quasar forum as I investigate https://forum.quasar-framework.org/topic/4022/column-level-filtering-above-each-shown-column-in-quasar-table

**Comment by Mak-NOAA** [comment]
Still developing on filtering but not there

**Comment by toddhay-NOAA** [comment]
duplicate of #968, closing this task
