### ISSUE TITLE
Allow selection of multiple table rows

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#437]

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  I presume https://quasar.dev/vue-components/table#Example--Multiple-selection-and-custom-selected-rows-label should work for this?

**Comment by Mak-NOAA** [comment]
Have some bugs sorting out in Quasar forum: https://forum.quasar-framework.org/topic/3855/qtable-with-multiple-selection-and-qpopupedit

**Comment by Mak-NOAA** [comment]
Looks like the row selection is working now.... @toddhay-NOAA check it out

**Comment by toddhay-NOAA** [comment]
functionally in place, might want to work on styling at some point, but closing it for now.
