### ISSUE TITLE
Create delete button that is activated when rows are selected

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#438]

**Comment by Mak-NOAA** [comment]
Bug being collaborated on here: https://forum.quasar-framework.org/topic/3892/trigger-on-deselection-of-qtable-rows/3

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA with @metalsadman's changes merged, the delete button should not be properly enabled/disabled
