### ISSUE TITLE
Tally: enable species list 

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#463]
to test we will need the complete species list available.

**Comment by wsmith-nwfsc** [comment]
This is how it currently is, using the same species that OPTECS has:
![image](https://user-images.githubusercontent.com/12972097/58727788-23c7a700-839a-11e9-995d-f14a71aa8b33.png)

**Comment by ericbrasseur-NOAA** [comment]
Cool, wasn't live just now so I wanted to be sure.
