### ISSUE TITLE
Remove Duplicate Lookups

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#523]
Still seeing duplicate lookups - Do you know what's causing this?  Have a way to resolve?

**Comment by toddhay-NOAA** [comment]
@wsmith-nwfsc, please look into why this is happening and get this cleaned up.

**Comment by wsmith-nwfsc** [comment]
The lookups-dev is mirrored from master-dev, and when we imported all new records, we ended up with duplicates for basically everything (since we didn't use the same document _id's.)
We'll have to nuke lookups-dev and rebuild it.

**Comment by wsmith-nwfsc** [comment]
And I just realized our pouch db's will have both records. Need to think about how to "nuke" those.

**Comment by wsmith-nwfsc** [comment]
Looks good in Dev and Prod now. Might have a lot of tombstones, but the duplicates seem to be removed.

![image](https://user-images.githubusercontent.com/12972097/62738359-00972480-b9e7-11e9-8826-e876b43a4226.png)

**Comment by NickShafferNOAA** [comment]
Great, glad that worked.

Here are the steps taken:

- Short script to add the property _deleted = true to all documents ("deleting" docs this way will ensure they're carried over by the replication process)
- Backed up lookups-dev into lookups-dev-backup
- Dropped / recreated lookups-dev (there should be a "purge" deleted docs command to use instead going forward)
- Moved design docs from lookups-dev-backup into the newly made lookups-dev
- updated replication document to reboot replication process


As I was talking with @wsmith-nwfsc about this, we realized this uncovered the issue of growing deleted documents taking up space. Deleting docs this way allows them to be replicated properly, but its still stored under the hood. It's probably ignorable for now but these "tombstones" as Will just put it (I like the terminology there), might be a problem in a real world environment if they keep being replicated to pouch DBs and piling up.

**Comment by wsmith-nwfsc** [comment]
Adding to this ticket, CouchDB docs discuss "Periodic Relocation" as a method to deal with DB's with lots of deletions. I don't really suspect we'll have that many deleted Lookups, so shouldn't be too much of an issue moving forward.
https://eclipsesource.com/blogs/2015/04/20/how-to-finally-delete-documents-in-couchdb/

And from the couchdb docs:
{noformat}
"  If your use case creates lots of deleted documents (for example, if you are storing short-term data like log entries, message queues, etc), you might want to periodically switch to a new database and delete the old one (once the entries in it have all expired)." 
{noformat}

**Comment by sethgerou-noaa** [comment]
Not sure whether this is related/expected, but I've seen many, many pouch console errors like this:

![image](https://user-images.githubusercontent.com/38139361/62790089-2bcd5280-ba7f-11e9-8ab3-1c2e80dec546.png)

And an expanded error looks like this:

![image](https://user-images.githubusercontent.com/38139361/62790211-751da200-ba7f-11e9-9058-6986d962931f.png)

Is this pouch attempting to mark the lookups as deleted?  Do users need to clear their caches?
After I clear my cache, I no longer see duplicates.

**Comment by wsmith-nwfsc** [comment]
Might be a side effect of a big deletion that @NickShafferNOAA performed yesterday to get rid of the duplications. See #523

We should merge #469 soon too
