### ISSUE TITLE
Trips cards are too wide for mobile

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#539]
The trip cards are just a bit too wide to completely appear on a standard-sized mobile phone (see the enclosed screenshot)

**Comment by toddhay-NOAA** [comment]
![CardsTooWide](https://user-images.githubusercontent.com/29761374/59731875-b8d0f980-91fc-11e9-8b27-d583aa1746ba.png)

**Comment by sethgerou-noaa** [comment]
I have been unable to duplicate this issue in Chrome or Firefox, serving locally or with the dev deployment.
Would you please try ctrl + shft + r on the trips page to see if that re-adjusts element scaling?

**Comment by toddhay-NOAA** [comment]
seems to be fine now, closing this ticket.
