### ISSUE TITLE
Jenkins Docker tasks leaking resources

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#548]
When a Docker instance finishes, the cleanup script kills all docker instances, including any that are running in another executor.
Need to fix script to not clobber running instances.

**Comment by wsmith-nwfsc** [comment]
Clobbering seems fixed now, but we're seeing unchecked disk usage due to lack of pruning.
Investigating the best way to handle this.

**Comment by wsmith-nwfsc** [comment]
Experimenting with node:10-alpine image which is ~80 MB versus 600 MB

**Comment by toddhay-NOAA** [comment]
FYI @wsmith-nwfsc, in my Saildrone deploy script, in the docker Makefile found here:

https://github.com/nwfsc-fram/SaildroneTS/blob/master/jenkins/deploy/Makefile

I do my image cleanup in the extract method as follows:

```
	# Show docker images before removing dangling images
	docker images

	# Clean up dangling images (i.e. the non-intermediate none:none images)
	# docker rmi $(docker images -f "dangling=true" -q --no-trunc) 2>/dev/null
	docker image prune --force

	# Show docker images after removing dangling images
	docker images
```

I would also note that when I build docker in the build method, I build with no-cache:

```docker build --no-cache=true -t ${docker_image} .```

not sure if the no-cache=true might be causing part of the issue.  I did that so as to prevent caching of  my all_data.tar artifact that is produced at the end of each deployment run

**Comment by wsmith-nwfsc** [comment]
This seems to help--although, I see that there are still ~36 images listed, so still working on this:

```
+ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 36
```

**Comment by wsmith-nwfsc** [comment]
Added the purge to primary build jobs as well, which seems to keep the Images count from growing uncontrollably. Shall keep an eye on it. 
Created docker-test job to manually perform basic checks.
