### ISSUE TITLE
User Config - sometimes it disappears

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#562]
This is partially related to userDB to master-dev replication, and partially related to non-reactive v-model on initial load.

Correct v-model reactivity.
Won't completely work correctly until replication works.

**Comment by neilriley-NOAA** [comment]
Unable to access anything on the User Config.  It just hangs as a blank screen.

**Comment by neilriley-NOAA** [comment]
The user config screen just appeared. I am not sure if it just took 10 minutes to load or if I did something differently? 

Now that I have access to the screen, I am unable to enter details each field. When I try to enter specific details in the fields, they disappear when I tab to a new field.

**Comment by toddhay-NOAA** [comment]
Thanks for this feedback @neilriley-NOAA.  @sethgerou-noaa is aware of this, but the details you're providing are helpful.
