### ISSUE TITLE
ETL Vessels

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#566]
Only ETL over the vessels selected in 2019 and then we'll clean up from there.   The appropriate WCGOP query is:

```
-- 593 Vessels selected for 2019 coverage
SELECT COUNT( DISTINCT vessel_id) 
FROM selection_history sh JOIN selection_periods sp ON sh.selection_period_id = sp.selection_period_id
WHERE sp.start_date >= '01-JAN-19'; 
```

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA , please get with @neilriley-NOAA as the vessels seem to missing a bunch of the active vessels

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I just looked on OTS and was able to find the Excalibur under the vessel search. @NickShafferNOAA confirmed 593 vessels were pulled from OBSPROD to couch.

**Comment by NickShafferNOAA** [comment]
@toddhay-NOAA I looked in couch again just recently and found that the couch view I was using and the view @sethgerou-noaa  is using are two different ones. Looking at the two view definitions, it doesn't make sense they're returning different data. I am investigating it.

**Comment by sethgerou-noaa** [comment]
In Vessel Management?  I can find the Excalibur in the search on the trips page, but not on the Vessel Management page.

**Comment by sethgerou-noaa** [comment]
> @sethgerou-noaa I just looked on OTS and was able to find the Excalibur under the vessel search. @NickShafferNOAA confirmed 593 vessels were pulled from OBSPROD to couch.

In Vessel Management?  I can find the Excalibur in the search on the trips page, but not on the Vessel Management page.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa my mistake the Excalibur does not show up in Vessel Management. But it does show when I try to stat a new trip.

**Comment by NickShafferNOAA** [comment]
@toddhay-NOAA ,
I was going over the data and noticed the query itself doesn't return some of the vessels in question. @neilriley-NOAA informed me that it excludes a lot of catch shares and EM vessels. Should I go back to ETLing the entirety of the vessels table, or is there a different way to restrict the active vessels?

**Comment by neilriley-NOAA** [comment]
In my opinion, we need to ETL the entire vessels table for legacy purposes. For future data collection and OTS we only need all IFQ, EM and NCS vessels where data was collected in the last year.

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA , yes I think you should pull over all of the vessels and then we'll clean on the couch side of things.

**Comment by NickShafferNOAA** [comment]
Double checked that this has been done. Vessels have been copied over, with an associated active contact where applicable.

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA Was this a one time migration? I continue to add vessels and valid contacts to OBSPROD, so I would think we would want to continue to migrate these records.

**Comment by NickShafferNOAA** [comment]
For now just a one time migration. I haven't yet finalized/automated the update logic for all of the obsprod data, it's a separate issue on the to-do list.

**Comment by neilriley-NOAA** [comment]
Makes sense. Thanks for the clarification.
