### ISSUE TITLE
OTS can't assign role

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#567]
I am unable to assign myself any role in OTS. I have tried to do this using Chrome and Firefox.

**Comment by sethgerou-noaa** [comment]
Sorry, it looks like you can add roles, but OTS isn't doing anything with your choices at present...
we're still waiting on some ApexUserAdmin functionality to implement role management. 

The only role that effects app behavior currently is 'Observer' - only users with the Observer role are listed as options to assign as the Observer on a trip.  

If you like, I can add the Observer role to your user via the database so you can schedule yourself on trips.

**Comment by scottleach-NOAA** [comment]
Sure that would allow me to test a few more things out.
