### ISSUE TITLE
OTS can't fill fields in User Config with Chrome 

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#568]
This issue occurs using Chrome 75.0.3770.100 (Official Build) (64-bit). When I enter information into a field in User Config the information I entered disappears when I click out of the field, tab, or enter. Sometimes I am able to hit save and when I navigate away some of the fields I entered information into that then disappeared now show the info I entered. 

Using firefox I did not have this problem and was able to enter information into the fields without issue.

**Comment by sethgerou-noaa** [comment]
when you have a chance, would you please browse to the home screen, then user config, and let me know whether the email fields are still misbehaving?  (Will enabled data sync between your userDB and masterDB - seeing if that helps)  note to self: likely non-reactive when user is not found in masterDB.

**Comment by sethgerou-noaa** [comment]
should be working now.
