### ISSUE TITLE
Initial Sync Pulls Large # of Records

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#569]
@wsmith-nwfsc, @sethgerou-noaa , @NickShafferNOAA 

All-
   So I noticed that when I did an initial load of Obs-Web, that it pulled down some 200,000 records for lookups data and I'm trying to figure out, what is all of that data?  Can you shed some light on what are all of these records?  I'd like to trim this down as much as possible:

![image](https://user-images.githubusercontent.com/29761374/60354897-278f1f00-9982-11e9-824a-84f77dca7f8f.png)

**Comment by sethgerou-noaa** [comment]
Looks like there are thousands of wcgop-operation documents in lookups-dev added at the end of last week.  Were these supposed to go somewhere else?  I don't think we want them in lookups.

**Comment by toddhay-NOAA** [comment]
Not sure, @NickShafferNOAA , can you shed some light on these documents?

**Comment by wsmith-nwfsc** [comment]
This was because there was a missing filter from master-dev to lookups-dev on prod. Fixed.
