### ISSUE TITLE
Auth popup after login in to observer-web prod

### ISSUE THREAD

**Issue by Mak-NOAA** [nwfsc-fram/boatnet#572]
I get a popup that asks for credentials _after_ I login to the https://www.nwfsc.noaa.gov/observer-web/

I enter the same credentials username/password that I used to login to the app on the popup it doesn't work. I tried to remove add and remove @noaa.gov 

<img width="1146" alt="Screen Shot 2019-06-28 at 10 59 41 AM" src="https://user-images.githubusercontent.com/20570382/60361963-8362a380-9994-11e9-8e7c-e6a43fcbfc32.png">
<img width="1366" alt="Screen Shot 2019-06-28 at 11 01 57 AM" src="https://user-images.githubusercontent.com/20570382/60361970-865d9400-9994-11e9-9ead-8f344e4ca60b.png">

**Comment by wsmith-nwfsc** [comment]
I think something is messed up on the prod couchdb.

Replication on prod, isn't working and although I see you logged in OK to the auth server, your couchdb user wasn't created/updated, so you're getting the 401 unauthorized from CouchDB.

Other weird behaviors on prod CouchDB make me think it's misconfigured.

**Comment by wsmith-nwfsc** [comment]
Looks like the couchdb IP is blocked from prod server. Sent IT request to resolve it, will update once it's working.

**Comment by wsmith-nwfsc** [comment]
@Mak-NOAA This appears to be resolved--give it a shot now.

**Comment by Mak-NOAA** [comment]
@wsmith-nwfsc yeap it's good
