### ISSUE TITLE
Search for vessel does not completely filter

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#585]
When typing values in the vessel search box, it should filter down the list of available vessels to only show those that match the values entered in the search box.  Right now it removes items before the relevant item but keeps in other items below that do not match the search term.  Please remove the items that do not match the search term.

**Comment by sethgerou-noaa** [comment]
Implemented 'starts with' search that returns only vessel name that start with the search term.

Note: There are currently too many vessels to load all into memory on page load (takes too long) - so vessel search is constrained by Couch's search capabilities - meaning searching for a substring ('includes' search) requires indexing on every possible starting point like: 

// master-dev/obs-web/searchable-vessels

function (doc) {
  var i;
  if (doc.type === 'vessel' && doc.vesselName) {
    for (i = 0; i < doc.vesselName.length; i += 1) {
      emit(doc.vesselName.slice(i), doc);
    }
  }
  emit(doc._id, 1);
}

While this works fine, couch sorts the indexed keys.
I haven't found a way to return the results alphabetically (which couch would need to do to return the appropriate 20 results).

Will get Will's thoughts on this when he returns, and will revisit when vessels have been limited to currently active - would be much easier to implement 'includes' if we could load all vessels on page load, and filter with search.
