### ISSUE TITLE
Auth server: Create replication docs for UserDBs to MasterDB

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#592]
Architecture/ workflow top-level notes:
* Auth server will create replication task via POST to CouchDB. 
* Replication docs will go in userdb/_replicator.
* Simple doc versioning (e.g. "version": 1) will be used to determine if replication needs updating.
* A selector object will be applied to prevent replication of tally-related data to master, and possibly other doc types.

**Comment by wsmith-nwfsc** [comment]
UserDB replication (with versioning) is in place. Currently the following selector omits tally docs from replication:

"selector": {
    "$nor": [
      {"type": "tally-data"},
      {"type": "tally-layout"},
      {"type": "tally-template"}
    ]
  },

**Comment by wsmith-nwfsc** [comment]
Attn @sethgerou-noaa the auth server now creates replication docs in userdb/_replicator.
I removed the manually created ones; they will be recreated when the user logs in.

**Comment by sethgerou-noaa** [comment]
Nice!  That's awesome!
