### ISSUE TITLE
Catch - Delete Species - completely remove the species from the grouping.  Include a confirmation dialog that also lists an option to move the species rather than delete it.

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#598]

**Comment by ericbrasseur-NOAA** [comment]
Note: extra caution if there is underlying data associated with the species.  Currently we do not allow a species to be deleted if it has a weight/count or bio record.  I am still hesitant to allow that.  Move should be an option but delete must be limited to species with no underlying data, 

or if allowed with underlying data, the original data should be recoverable. The deleted items should be flagged as deleted and hidden from the observer, the observer should have an option to restore them while still on the same page, and the records should be available to a debriefer is they choose to view them.  The debriefer should receive a notice that records were deleted when reviewing the data.
