### ISSUE TITLE
Enable jenkins building permissions to team members

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#604]
Currently @sethgerou-noaa gets the following error:

```pending—‘sgerou’ lacks permission to run on ‘Jenkins’```

**Comment by wsmith-nwfsc** [comment]
mshak also getting this error.
Trying to repro on my VM.

**Comment by wsmith-nwfsc** [comment]
Anthony is comparing prod jenkins configuration.

**Comment by wsmith-nwfsc** [comment]
We disabled the global configuration: Build Authorization, Run as User
