### ISSUE TITLE
Auth server: Retrieve roles from ApexUserAdmin

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#617]

**Comment by toddhay-NOAA** [comment]
details highlighted in https://www.st.nmfs.noaa.gov/jira/browse/BOAT-7

**Comment by wsmith-nwfsc** [comment]
Roles now coming from BOATNET_OBSERVER application in AUA. CouchDB is updated automatically when user logs in with these roles:
{pre}
 Roles status result from oracle:  [ 'observer', 'debriefer', 'data_steward', 'development_staff' ]
{pre}
