### ISSUE TITLE
Auth server: add RESTful endpoints for role management (for OTS)

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#638]
See BOAT-7, BOAT-13

**Comment by wsmith-nwfsc** [comment]
Added OpenAPI definitions to auth server (for existing endpoints) and will use this to self-document the roles functionality

**Comment by wsmith-nwfsc** [comment]
Full API and dev implementation in place #677

**Comment by toddhay-NOAA** [comment]
Please push to production once ready.

**Comment by wsmith-nwfsc** [comment]
https://nwcdevmeow1.nwfsc.noaa.gov:9000/api-docs
https://nwcprodmeow1.nwfsc.noaa.gov:9000/api-docs/ + reverse proxy endpoint
