### ISSUE TITLE
revisit virtutal keyboard - this one's got issues

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#649]
- weird to see between keys
- doesn't move field so it's visible
- odd key arrangement

**Comment by toddhay-NOAA** [comment]
I might add to the list that a user cannot move the keyboard, which can be done with some of the keyboards in OPTECS that are embedded in a dialog widget.

**Comment by toddhay-NOAA** [comment]
Thinking out loud a bit on this.  I'm sort of thinking that for the keyboard, we'll have two modes:

- Stand alone keyboard - where an auto-complete is not needed/used
- Keyboard coupled with auto-filter/complete list to the right (ala OPTECS Vessel selection widgets)

We could look at rolling our own keyboard widget that you then be used in both of these modes, or potentially reuse an existing one, such as:

https://www.npmjs.com/package/simple-keyboard

For the numpad, we'll need it to have two different modes as well:

- Float support
- Integer support - do not allow float entries
