### ISSUE TITLE
Jenkins Docker scripts deleting images in-use

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#655]
The saildrone docker instance no longer leaks resources, but now it deletes images in-use by other builds.
I believe this is because they all share the node 10 base image, and that gets nuked.

Example build failure:

(boatnet-build-all-web-PROD is running, and salmon-server-pull kicks off)

Done in 271.15s.
unknown parent image ID sha256:4dd92232de43b011d6c0816d5b905544a86d85a44f6c0db8e312291ae4268d9d
make[1]: *** [build] Error 1

**Comment by wsmith-nwfsc** [comment]
Current workaround is just to re-run the build.

**Comment by toddhay-NOAA** [comment]
A decent article explaining the different types of docker images:

https://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/

**Comment by toddhay-NOAA** [comment]
what's odd is the command we're using is to delete only the bad <none>.<none> images per that above article, i.e. we are not deleting the intermediate images, but still we're having the conflicts between saildrone and offer services.  I wonder if the salmon service conflicts with boatnet as well?
