### ISSUE TITLE
Unable to save changes to couch - Error: Error with put request for CouchDB database master-dev at https://www.nwfsc.noaa.gov/couchdb/master-dev/c9e71f7179b97ca3d484d3f9e21f83ed. 403 Forbidden

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#669]

**Comment by wsmith-nwfsc** [comment]
Which user?

**Comment by sethgerou-noaa** [comment]
seth.gerou on prod observer-web.

**Comment by wsmith-nwfsc** [comment]
Also just noticed #671 
Investigating...

**Comment by wsmith-nwfsc** [comment]
The validation doc had 'debriefer' role hardcoded. I changed that to 'captain' for now, so please test that.
Need to come up with a better validation doc that uses the couchdb Permissions to determine whether user permission is readonly.

**Comment by wsmith-nwfsc** [comment]
#672 for that validation doc improvement. We can close this ticket if you can now write to the DB as 'captain' (e.g. it's behaving like I expect it to)

**Comment by sethgerou-noaa** [comment]
working now, thanks!
