### ISSUE TITLE
Push software updates to installed PWA

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#683]
In talking with Seth, when the OBS-Web PWA is installed, it does not automatically update the software.

**Comment by wsmith-nwfsc** [comment]
Related/ same as to #277 
I'll add code from linusBorg https://forum.vuejs.org/t/vue-cli-3-project-with-pwa-not-busting-cache-on-new-builds/50252/6 here to speed up the process (currently requires closing the tab, it sounds like.)

**Comment by wsmith-nwfsc** [comment]
Appears to be applying itself automatically now in #685 
![image](https://user-images.githubusercontent.com/12972097/62084377-113ce300-b20e-11e9-8dfd-e1c34c6dfc00.png)
