### ISSUE TITLE
Create Debriefing Balsamiq Mockups

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#69]
Leverage ideas from A-SHOP NORPAC Data Editor (NDE) and WCGOP OBSPROD Debriefing component, as well as McVeigh's excel proposed mockup.

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  here's my first draft for Debriefing module:

![list](https://user-images.githubusercontent.com/20570382/52313954-5cfc8700-2965-11e9-992f-627944c1b0e2.png)
![detail](https://user-images.githubusercontent.com/20570382/52313955-5ff77780-2965-11e9-92a4-5f3054d823b2.png)

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, I think we want to work up the mockups so they leverage what we're thinking in terms of some flattened views ala #193.  So with these three flattened views, we would then want to allow some rapid filtering and sorting, and then enable a debriefer to select cells of interest for editing.  I think you and I need a whiteboard session where we can walk through this concept a bit.

**Comment by Mak-NOAA** [comment]
Yeah this will require whiteboarding. How does that affect the current OAT mocks that we have ? Like how do you make it from our current workflow to the 3 flattened views in #193 ?

**Comment by toddhay-NOAA** [comment]
I'm thinking that a user clicks on one of the trips and that takes them to a trips data view and the debrieferr can then select which of the three views to look at (catch species, containers/baskets, specimens).  We then want to give the user a bunch of widgets for selecting some predefined filters (i.e. click on a Trip Info button and it only shows the trip info level of detail from the flattened view).  Those are the items that we'll want to whiteboard out.

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, in preparation for our Thursday meeting, please start working up some mockups for the 3 flattened views;

- Catch Species Items
- Containers / Baskets
- Specimens

Think about how the observer staff/debriefers will want to filter down to items of interested.  For instance, I'm thinking initially that we'll give them some predefined filters for trips, hauls, catch species, etc., similar to the hierarchy that they were using over on NDE.

**Comment by Mak-NOAA** [comment]
Will do

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  here it is https://balsamiq.cloud/sbkeqjt/pc90mhm/r4ED1 feel free to comment before we dig into more realistic data as I have a feeling I'll need to update the table content again :)

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, comments as follows:

- General - We should have text boxes above each column for filtering within that column
- Hauls - I think we need an example for a trawl haul and for a fixed gear haul
- Views - We'll likely have MMSBT, HLFC, and BRD views as well, so go ahead and add then to the View types, but don't create the flattened tables for these yet, as we're still working through the models
-  Bulk Change - We'll need a bulk change button somewhere in the top section, such that if a user selects multiple values in a given column, he/she can click the bulk change button and modify the value
- Real Values - Can you put some real values in these columns as you have a lot of placeholders in there currently.
- Specimens - For Biostructures, that is an array of biostructures, so we're going to need to split those apart to dynamically generate columns for when we have a given biostructure type.  Typical biostructures that we'll encounter include:  scales, finrays, snouts, otoliths, finclips, tissues, and whole specimens

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA please re-review the mocks and let me know if it's ready to be shared with the rest of the folks. The starting point would be the error page: https://balsamiq.cloud/sbkeqjt/pc90mhm/rE1B0

**Comment by toddhay-NOAA** [comment]
Balsamiq mockups:  https://balsamiq.cloud/sbkeqjt/pc90mhm/r4ED1

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA, comments as follows:

- Observer - Should be text field with autocomplete (unclear if that is what you're trying to convey or not)
- Trip - textfield with autocomplete
- Bulk Update -- highlighting one or more cells from the same column show enable this button.  Clicking on this button should open a dialogue whereby the user can identify the update type (change value or nullify I'm thinking are the two most likely change types).  
- Delete button (close to the Bulk Update I'm thinking) -- Highlighting one or more rows should enable this button and the rows can be deleted after a dialogue confirmation box
- Shown Columns should be Show/Hide Columns
- Show/Hide Columns should be a button that opens up a dialogue
- Show/Hide Columns dialog should have two list boxes, the left one contains those column names that are not currently shown and the right one the column names that are currently shown.  Highlighting single or multiple columns in either box and double clicking should move the items back and forth between the columns and then either show or hide them appropriately.  Something along the following lines:

![Sict6](https://user-images.githubusercontent.com/29761374/56335207-759cd080-6150-11e9-94f8-6a691fe6e905.png)

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  please review https://balsamiq.cloud/sbkeqjt/pc90mhm/rE1B0

**Comment by toddhay-NOAA** [comment]
This looks good for now @mak, I'm going to close out this task.

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , here is some feedback for the flattened views that I received from the Observer team:

- Lower-level views should only show the pertinent information for that level, with identifiers for the higher levels.  For instance:
  -- Trips - Show Trip # + Trip-level information
  -- Hauls - Show Trip #, Haul #, Haul-level information
  -- Catch - Show Trip #, Haul #, Catch Disposition +Weight Method, Catch-level information
  -- CatchSpecies - Show Trip #, Haul #, Catch Disposition + Weight Method, Catch Species, CatchSpecies-level information
  -- Baskets - Show Trip #, Haul #, Catch Disposition + Weight Method, Catch Species, Basket #, Basket-level information
  -- Specimens - Show Trip #, Haul #, Catch Disposition + Weight Method, Catch Species, Specimen #, Specimen-level information

- Force creation of a catch species record before someone can change a specimen species property, i.e. if they were to try and create a new catch species
- Show/Hide Column - Allow the user to save off these states as defined views that he/she can reopen

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA  bullet one is complete and I believe the other two bullets are good requirements for development but not necessary to mock

https://balsamiq.cloud/sbkeqjt/pc90mhm/r7D29

**Comment by toddhay-NOAA** [comment]
I concur @Mak-NOAA, please go ahead and proceed to developing the views and web app table showing the views
