### ISSUE TITLE
obs-electron: Update packages 

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#7]
There is a useful command to check if your packages need upgrade (security updates, etc) which is:

`npm outdated`

This will show "Current", "Wanted" (which is newest compatible version), and "Latest" which can be incompatible with what you're running. Packages listed in red should be updated, and yellow is recommended. To automatically update your package.json to "Wanted" the command is:

`npm update`
This also seems to implicitly run `npm install` Then re-run to make sure everything's up to date:
`npm outdated`

Created this ticket to track this operation for obs-electron to try and reduce the security issue warnings. @sethgerou-noaa we should do this step regularly for obs-web as well.

Source for this I came across: https://docs.npmjs.com/getting-started/updating-local-packages

**Comment by sethgerou-noaa** [comment]
updated obs-web packages - resolved all security advisories
