### ISSUE TITLE
Taxonomy ETL

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#706]
Rough listing of major sub-items done and todo:

- [x] Script against itis' api to create taxon documents
- [x] Make script async
- [x] Script to flatten taxon documents / compare to DW
- [x] Track down and document all edge cases
- [x] Fix edge cases
- [x] qa/qa ETL'd data
- [x] Incorporate Pacfin
- [ ] Incorporate AFS/worms

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA , please provide an update on this ticket.

**Comment by NickShafferNOAA** [comment]
Done some qa/qc work. Currently incorporating pacfin. Unlikely to get to incorporating AFS/Worms in the near future, as I've been told that Itis usually updates their items after AFS does, making their data quite reliable, so connecting to a second/third system is low on the priority list (perhaps after taxonomy-alias / groupings are entirely done).

**Comment by toddhay-NOAA** [comment]
If you've already tied to ITIS, let's call that good enough for now, and just skip doing AFS and worms.  I want to get you beyond the taxonomy tasks and onto other ETL work.
