### ISSUE TITLE
Fix Duplicates in lookups-dev DB

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#711]

**Comment by NickShafferNOAA** [comment]
Duplicate of #523

Created this in error, can be ignored.

**Comment by toddhay-NOAA** [comment]
Go ahead and delete this ticket then
__________________________
Todd Hay, Ph.D.
NWFSC / FRAM
206.302.2449
todd.hay@noaa.gov
https://www.nwfsc.noaa.gov/data

**Comment by NickShafferNOAA** [comment]
I looked for the delete option but cannot find it, I think only administrators of the repository can delete tickets.
