### ISSUE TITLE
Auth prod swagger interface has incorrect URLs

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#729]
The auth prod swagger interface has incorrect urls.  For instance, it has:

https://www.nwfsc.noaa.gov/api/v1/login

whereas it should be:

https://www.nwfsc.noaa.gov/auth/api/v1/login

This is clearly a reverse proxy-related issue.  Please correct all URLs

**Comment by wsmith-nwfsc** [comment]
I've been using https://nwcprodmeow1.nwfsc.noaa.gov:9000/api-docs/ for this, but since that's VPN-only, it makes sense to figure out how to do this through our reverse proxy for future public-facing services as well.

**Comment by toddhay-NOAA** [comment]
@wsmith-nwfsc , I'd like to demonstrate this OpenAPI capability at the upcoming Electronic Technology workshop that I'm attending the week after next, so please try to address this particular issue by Monday the 26th.
