### ISSUE TITLE
Auth server is returning 401 errors (/login) and timing out

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#731]
Error message is:

```
Error: Backend communciation error: Error: NJS-040: connection request timeout
```

**Comment by toddhay-NOAA** [comment]
I'm guessing that this is related to the clobbering of the Oracle connection pool that we discussed.

**Comment by wsmith-nwfsc** [comment]
BOAT-21 is the internal ticket for this. It is related to Oracle connection pool filling up and not allowing new Oracle connections. Investigating...

**Comment by wsmith-nwfsc** [comment]
Made some error handling updates, and along with Mak's push to Prod, I haven't been able to reproduce this since. #728 will keep an eye on this.

**Comment by wsmith-nwfsc** [comment]
Hmm, reopening--I saw the pool connections jump from 1 to 2 in a log, investigating users-details code which seems to be related to the bump (it should stay at 1)

**Comment by wsmith-nwfsc** [comment]
Looks like it went back to 1 connection, can't repro, so will continue to monitor.

**Comment by wsmith-nwfsc** [comment]
Added logging to trace missing connection.close() if it happens again.
