### ISSUE TITLE
Enable multiple observers to edit the same trips/hauls data

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#752]
There could be up to three observers on a given A-SHOP trip, and they will all need to be able to add, edit, and delete the data from the trips.

**Comment by wsmith-nwfsc** [comment]
Brainstormed an approach that I think will work well with our architecture (will require limited internet connectivity to transfer the UUID of the trip, but will support offline.) I'll draw up a sequence diagram when I get to this ticket.

**Comment by wsmith-nwfsc** [comment]
moved to #1061
