### ISSUE TITLE
Create A-SHOP Trips Details screens

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#754]

**Comment by melinashak-noaa** [comment]
Created trips, hauls, and catch mockups. Showed them to Vanessa's team and will revised them based on their feedback. Sent them over again and currently working on incorporating those comments. Also will need to mockup the specimen screens.

**Comment by toddhay-NOAA** [comment]
For the specimens, I would really like for us to try and use a common specimens screen capability across observers and surveys.  We have specified this already for the WCGOP side of the house, so please start with that.
