### ISSUE TITLE
Delay in populating the Vessel pulldown for Set Active Vessel

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#762]
Currently there is a delay when clicking in the Set Active Vessel pulldown for a new trip.  Can we speed this up?

**Comment by sethgerou-noaa** [comment]
I've implemented a function that runs all views (that are currently in use) as soon as the first data sync (of lookups) is completed - this takes some time to execute, so there's a progress bar letting the user know something is happening.  Once the indexing is done, select options are very fast to load and filter.
