### ISSUE TITLE
Taxonomy Alias ETL

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#767]
- [x] ashop scientific/common names
- [x] warehouse scientific/common names
- [x] wcgop scientific/common names
- [x] pacfin

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA, please provide an update on this ticket.

**Comment by NickShafferNOAA** [comment]
Alias documents from scientific name have been created, as well as from common names from ashop/wcgop/warehouse. Going to do the same for pacfin once those species records are all turned into taxonomy documents.
