### ISSUE TITLE
Add remember me checkbox to login page

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#781]

**Comment by ericbrasseur-NOAA** [comment]
All for it if you can.  I use lastpass to get around it for lots of sites and apps but do appreciate it.  Cuts down on forgetting usernames.

**Comment by toddhay-NOAA** [comment]
and our captains may not use lastpass or something similar, so it might impact them more if we don't do this.

**Comment by toddhay-NOAA** [comment]
let's discuss with Will how the JWT works.

**Comment by wsmith-nwfsc** [comment]
We weren't allowed to do this for OPTECS, but possibly worth asking the IT folks if it's OK for web apps.
