### ISSUE TITLE
New trip departure / return dates are not selectable

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#787]
I just cleared my browser cache for all time on my windows 10 laptop, I logged into OTS, went to create a new trip for the Joy Ann vessel, and none of the dates are selectable, they're all grayed out:

![NonSelectableDates](https://user-images.githubusercontent.com/29761374/63909016-21470e80-c9d6-11e9-96bd-2bce950126eb.png)

**Comment by sethgerou-noaa** [comment]
whoops.  my variables to store existing trip start and end dates were initialized with invalid dates, so if there's no active trip, the dates filter function returns all dates invalid.

Fix will be up in ~15 minutes.
