### ISSUE TITLE
User Config - keyboard for active vessel doesn't exist

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#791]
@sethgerou-noaa When I click on the Active Vessel entry in User Config the keyboard doesn't display
@toddhay-NOAA 

![image](https://user-images.githubusercontent.com/31421964/63954108-69e2e400-ca37-11e9-8995-a0653a50d875.png)

**Comment by sethgerou-noaa** [comment]
it isn't supposed to - the user is picking from a list of vessels they are the captain of - can't imagine this will be more than 3, so I'm just listing available options (no search/autocomplete).

If you're not seeing any vessel options, remember you first need to add yourself as a captain of a vessel in vessel management.

**Comment by neilriley-NOAA** [comment]
ahhh. that is right. Thanks for the reminder.

**Comment by toddhay-NOAA** [comment]
while I understand closing this, I worry that we consistently run into this problem and we're the folks who have developed this, so to me, that says we may have a bad workflow here for this concept.  What do you all think?  I think we should discuss a bit more, so reopening it for now.

@scottleach-NOAA , @johnlafargue-noaa

**Comment by sethgerou-noaa** [comment]
active vessel selection is no longer in user config - now selected on trips and declarations pages
