### ISSUE TITLE
New Trip, existing port selected, enter text field, auto-select all of the text

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#796]
RIght now if a user clicks on one of the auto-complete fields, it puts the cursor at the end of the text.  Rather, auto-select all of the text so that when the user starts typing it overwrites all of the existing text and they can start searching right away without having to backspace all of the previous port characters.

**Comment by sethgerou-noaa** [comment]
@toddhay-NOAA - I currently have all ports listed, so the keyboard doesn't take up half the screen, which I think is a pretty good experience.  Let me know what you think.

**Comment by toddhay-NOAA** [comment]
yes, this is good.  Just in general though, for when we have auto-complete fields, I think it makes sense to auto-select all of the existing text in a field when a user clicks into that so he/she can start typing and overwrite the existing text.
