### ISSUE TITLE
Create instructions for our github workflow

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#82]
We'll want to document git commands for our team workflow:
1) creating feature branch
2) keeping branch up-to-date with master via rebase or merge
3) creating a pull request
4) merging back into master

**Comment by Mak-NOAA** [comment]
Thanks @wsmith-nwfsc !

**Comment by wsmith-nwfsc** [comment]
I guess this was already on the README at the bottom, and in boatnet/CONTRIBUTING.md
