### ISSUE TITLE
captain name search doesn't return all names

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#820]
The captain name search does easily return and existing name.  For example, if I type Scott Leach nothing shows up (see screen shot). But if I type Scottleach it shows up.  Is there a way to improve the search feature to display all the names without typing the exact user name in. Seem like this leaves us open to creating duplicate names.

![assign captain](https://user-images.githubusercontent.com/31421964/64390734-e444d280-cffa-11e9-9e99-e7b41b424031.png)

**Comment by sethgerou-noaa** [comment]
I believe the app is just returning too many Scotts for Scott Leach to show up in the first 10 results.  I'm switching the query to search only active person documents, and extending the results to 20 items.
