### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#825]
Create a common login screen that can be used across apps. 

First figure out what the different login screens will look like, and how similar they will be. This will help determine which components to make common.

**Comment by melinashak-noaa** [comment]
Created common login, and menu bar. Pull request here: https://github.com/nwfsc-fram/boatnet/pull/859

**Comment by melinashak-noaa** [comment]
yesterday worked on updating the code to address Seth's comments. Today just looking at my ashop code and seeing how to modify it to pass in different configs in preparation for tomorrow's discussion.

**Comment by melinashak-noaa** [comment]
checked in code, but running into jenkins build issues, spending today trying to resolve them. Getting this odd issue: Consulted with seth, and he thought it may be a typescript version issue, but modified versions and still getting this error. 

ERROR in C:/Users/Melina.Shak/Documents/src/boatnet/apps/ashop/src/_store/index.ts                                                                   38:3 Type 'Plugin[]' is not assignable to type 'Plugin[]'.                                                                         Type 'Plugin' is not assignable to type 'Plugin'.                                                                                  Types of parameters 'store' and 'store' are incompatible.                                                                                              Type 'Store' is not assignable to type 'Store'.                                                                                    Types of property 'registerModule' are incompatible.                                                                                                   Type '{ (path: string, module: Module, options?: ModuleOptions \| undefined): void; (path: string[], module: Module RootState>, options?: ModuleOptions \| undefined): void; }' is not assignable to type '{ (path: string, module: Module, options?: Modu leOptions \| undefined): void; (path: string[], module: Module, options?: ModuleOptions \| undefined): void; }'.                                    Types of parameters 'module' and 'module' are incompatible.                                                                                            Type 'Module' is not assignable to type 'Module'.                                                                        Types of property 'actions' are incompatible.                                                                                                          Type 'ActionTree \| undefined' is not assignable to type 'ActionTree \| undefined'.                                        Type 'ActionTree' is not assignable to type 'ActionTree'.                                                                Index signatures are incompatible.                                                                                                                     Type 'Action' is not assignable to type 'Action'.                                                                        Type 'ActionHandler' is not assignable to type 'Action'.                                                                 Type 'ActionHandler' is not assignable to type 'ActionHandler'.                                                          Type 'unknown' is not assignable to type 'RootState'.                                                                      36 \|     tripsState                                                                                                                                  37 \|   },                                                                                                                                          > 38 \|   plugins: [vuexLocalStorage.plugin]                                                                                                               \|   ^                                                                                                                                             39 \| };                                                                                                                                              40 \|                                                                                                                                                 41 \| export default new Vuex.Store(store);                                                                                                                                                                                                                                                 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
--

**Comment by melinashak-noaa** [comment]
jenkins build succeeded now. Had an issues [here ](https://github.com/nwfsc-fram/boatnet/blob/master/apps/ashop/package.json) where typescript was set to ^3.4.2 instead of 3.4.2. Now everything is working okay.

**Comment by toddhay-NOAA** [comment]
has this been refactored as a component?  If so, and there is nothing else to do, please go ahead and close this.  Although, I think we need to remove the Quasar version as that means nothing to the user.
