### ISSUE TITLE
Lerna issues with auth.service.ts

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#838]
In my obs-ashop node-modules folder getting an error in the auth.service.ts file when importing certain libraries. I see in the obs-wcgop auth.service.ts file, the imports reference the common node-modules folder, but for some reason mine are not doing that. Not sure if it has to do with how lerna set stuff up, but it doesn't seem to be able to reference things properly. 

Code: [here](https://github.com/nwfsc-fram/boatnet/blob/master/libs/bn-auth/src/_services/auth.service.ts#L9)
Error: 
Module '"c:/Users/Melina.Shak/Documents/src/boatnet/node_modules/@types/jsonwebtoken/index"' has no default export.ts(1192)

Code: [here](https://github.com/nwfsc-fram/boatnet/blob/master/libs/bn-auth/src/_services/auth.service.ts#L7)
Error: Module '"c:/Users/Melina.Shak/Documents/src/boatnet/node_modules/@types/crypto-js/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flagts(1259)
index.d.ts(6, 1): This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

I added allowSyntheticDefaultImports=true to my tsconfig.json file, but still getting the same error

**Comment by wsmith-nwfsc** [comment]
Is this a result of running ```quasar build`` or running ```lerna bootstrap && lerna run build```?

**Comment by melinashak-noaa** [comment]
so this is when i run lerna clean, then lerna bootstrap. But now I ran lerna bootstrap, lerna clean, lerna run build, as specified on the github README and now don't see a node-modules folder generated under ashop, but it's there for wcgop and ots. Does this mean lerna isn't exactly working?

**Comment by wsmith-nwfsc** [comment]
Sounds like lerna just isn't seeing obs-ashop as a project, but I think the issue you are seeing is something else. After you did the bootstrap/clean/run build, did the error go away?
Does `quasar build` work for obs-ashop?

**Comment by melinashak-noaa** [comment]
hmm odd just ran lerna bootstrap and this time it generated the auth.service.ts file and the imports look okay, gotta double check though

**Comment by melinashak-noaa** [comment]
so yes quasar build seems to be working and quasar dev serves the page and I see the login page, but in the console I see 404 error:
![image](https://user-images.githubusercontent.com/44685558/64724195-df62a180-d486-11e9-97fb-000a5d75f231.png)

also now having an issues with this import now: import { authService } from '@boatnet/bn-auth';
hmmmm i'll keep looking for what's going on

**Comment by melinashak-noaa** [comment]
ended up just using vue cli and this resolved the issue
