### ISSUE TITLE
Create common data viewer

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#862]
- [ ] Allow selection of attributes (select criteria)
- [ ] Allow filtering of values for the attributes (where criteria)

**Comment by sethgerou-noaa** [comment]
Spent some (too much) time trying to get Multicorn foreign data wrapper working.  Ran into issue after issue getting it set up properly, and still haven't managed to get it working.

Only appears to work in Linux, so I'm not thinking this is a great option.

**Comment by sethgerou-noaa** [comment]
closing this one - don't believe it captures anything that's not being addressed by another ticket
