### ISSUE TITLE
Research high profile Vuejs projects for component-based approaches

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#877]
Determine if they have multiple deployment/configuration targets and how they are handling this

**Comment by melinashak-noaa** [comment]
This [project ](https://github.com/Alexays/Epiboard) does something similar. They show a variety of cards of different types similar to how we show different components. They store these different card types in state then loop through them to display the cards. 

https://github.com/Alexays/Epiboard/blob/master/src/components/Home/index.vue#L28

**Comment by melinashak-noaa** [comment]
This is also interesting: https://nuxtjs.org, it's a vue framework used to make building vue apps easier. It takes care of routing and optimizes your code to load faster. Probably not quite relevant to this topic, but just something interesting I found while searching for high profile projects and wanted to share.

**Comment by toddhay-NOAA** [comment]
interesting @melinashak-noaa , I've definitely heard of nuxtjs via different articles and podcasts.

**Comment by toddhay-NOAA** [comment]
Team, are we satisified with our approach towards components such that we can close this ticket?

**Comment by toddhay-NOAA** [comment]
closing out this task
