### ISSUE TITLE
Unit Testing - define how and scope

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#880]
- [x] Try to run built-in Vue.js tests
- [x] Refer to Node Weekly article on unit tests in Vue.js
- [x] Implement a sample unit test

**Comment by SaOgaz-NOAA** [comment]
Some helpful links to different unit testing libraries: https://github.com/vuejs/awesome-vue#test

**Comment by toddhay-NOAA** [comment]
article on unit testing at vue mastery:

https://www.vuemastery.com/blog/unit-testing-vue-1

**Comment by toddhay-NOAA** [comment]
More links of interest:

https://vue-test-utils.vuejs.org/
https://vue-test-utils.vuejs.org/guides/testing-single-file-components-with-jest.html

**Comment by toddhay-NOAA** [comment]
Who wants to take the lead on defining how we set up our unit testing?  @wsmith-nwfsc ?

**Comment by wsmith-nwfsc** [comment]
Shall demo Monday
