### ISSUE TITLE
Define coding standard for refactoring large Vue.js files

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#882]
We want to restrict the number of lines of code in any given file to say, less than 500 lines.  To do this, we need to define how we're going to store additional functions in a set of external files, and also where we store common functions/ts files.

- [ ] Verify that the ```<script lang="ts" src="src/utils_example.ts" />``` format makes sense and works

- [ ] Document our coding standard for this in CONTRIBUTING.md

**Comment by wsmith-nwfsc** [comment]
- [ ] Verify that the ```<script lang="ts" src="src/utils_example.ts" />``` format makes sense and works

- [ ] Document our coding standard for this in CONTRIBUTING.md

**Comment by wsmith-nwfsc** [comment]
Updated https://github.com/nwfsc-fram/boatnet/blob/master/CONTRIBUTING.md
