### ISSUE TITLE
Define Boatnet Coding Standards

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#890]
Develop a markdown file for capturing our coding standards.  This will includes items such as:

- [x] Maximum number of lines of code per file
- [x] Organization of leave behind code (not sure of the correct name here)

Markdown document is here:

https://github.com/nwfsc-fram/boatnet/blob/master/docs/dev-notes/coding-standards.md

**Comment by wsmith-nwfsc** [comment]
Also, since we use Quasar quite a bit, learning from their code for development of our own components would be helpful:

https://medium.com/quasar-framework/wip-look-at-the-source-code-please-1b905ea4906
