### ISSUE TITLE
Refactor Boatnet Layout Common Component into config files

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#896]
Currently these are split in the layouts\Default.vue files in the ashop and the bn-common folders, rather these should be defined in the application configuration files

**Comment by toddhay-NOAA** [comment]
@melinashak-noaa , in chatting with @sethgerou-noaa , it sounds like you are already working on this refactoring... creating the ticket here to keep track of that work.

**Comment by melinashak-noaa** [comment]
Finished this, with this pull request: https://github.com/nwfsc-fram/boatnet/pull/897
