### ISSUE TITLE
Create Boatnet NPM package

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#908]

**Comment by wsmith-nwfsc** [comment]
Going to try and leverage unit/e2e testing while I develop this, pending #880

**Comment by wsmith-nwfsc** [comment]
I have created the @boatnet organization, and will publish like that (e.g. @boatnet/bn-couch )

**Comment by wsmith-nwfsc** [comment]
Created and published bn-test-example, bn-util, bn-models.
Will create another ticket for remaining auth/pouch/couch modules
