### ISSUE TITLE
Review Vue 3.0 Composition Functions, Report back to team

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#909]
We want to make a decision as to our future development approach within Vue:

- Templates
- Classes
- Composition Functions

Please review and make a recommendation at our next team meeting

**Comment by toddhay-NOAA** [comment]
Vuejs Composition Functions:

https://github.com/vuejs/rfcs/pull/17?utm_campaign=Vue.js%20News&utm_medium=email&utm_source=Revue%20newsletter#issuecomment-494242121

**Comment by melinashak-noaa** [comment]
Currently reading through documentation on the new Vue Composition API: 
https://vue-composition-api-rfc.netlify.com/#basic-example

Here's the most recent RFC's (request for comments)
https://github.com/vuejs/rfcs/pull/78

And here's an older one along with it's documentation 
https://github.com/vuejs/rfcs/pull/42#adoption-strategy
https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md

**Comment by melinashak-noaa** [comment]
Going to experiment with the composition api by installing the plugin and modifying a few components to use this new syntax and see how it goes.

**Comment by melinashak-noaa** [comment]
Modified tripDetails page in ashop to use composition style and it's working successfully. Here's working PR https://github.com/nwfsc-fram/boatnet/pull/918

**Comment by melinashak-noaa** [comment]
quick presentation for team: https://docs.google.com/presentation/d/18issdqbG5Dg-DlH0-d1FyuIFeqeGZ1aC7YgR45ZJcQ8/edit?usp=sharing
