### ISSUE TITLE
Observer-web does not work on iphone

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#925]
I’m trying to hit observer-web from my new iPhone but the page just times out.  It is an iPhone XR.  Please investigate the service and ensure that everything is operational.

I’m hitting:

https://www.nwfsc.noaa.gov/observer-web

**Comment by wsmith-nwfsc** [comment]
Works OK from my Android phone.

**Comment by wsmith-nwfsc** [comment]
The Sync Data and Indexing Data progress bars are very cool btw, nice @sethgerou-noaa !

**Comment by toddhay-NOAA** [comment]
all seems to be working today, so closing out this ticket.  Not sure what the issue was.  I just tried it again in Safari, downloaded the app, everything sync'd just fine.
