### ISSUE TITLE
Pull active permits nightly

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#927]
Pull these down nightly so we have these for offline permit selection for OTS

- [ ] Pull down active permits nightly
- [ ] Update EM EFP roster with latest permits

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA , didn't you do this work already as part of the milestone?

**Comment by BHHorness-NOAA** [comment]
Learning Jenkins slowing this one down - moving to next milestone.

**Comment by NickShafferNOAA** [comment]
I believe I (finally) understand how to create a jenkins job from start to finish (huge thanks to Sara). The permits script is now successfully running. I just need to get it running on a timer, and figure out why Jenkins is labeling it a failure when it has successfully ran.

**Comment by NickShafferNOAA** [comment]
Figured out why it was failing. Makefile script was trying to copy and save a tgz that didn't exist because the jenkins configuration does not have that set up to do. Going to test run it on a timer for a day or so before setting it up against master-dev but otherwise it should be all good.
