### ISSUE TITLE
Create new endpoint for boatnet app and add it the jenkins build

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#930]
This will be our boatnet endpoint from which any of the apps can be run

**Comment by wsmith-nwfsc** [comment]
#894 related

**Comment by wsmith-nwfsc** [comment]
Change observer-trips to boatnet

**Comment by toddhay-NOAA** [comment]
This will require some coordination with Marcus and Anthony to modify the reverse proxy.  Let me know if you want me to send out a final email on this front today.

**Comment by wsmith-nwfsc** [comment]
Will try to get this set up early on Monday.

**Comment by wsmith-nwfsc** [comment]
Emailed Marcus and Anthony.
Once they've made the change, I'll merge #1047

**Comment by wsmith-nwfsc** [comment]
Deployed
