### ISSUE TITLE
OPTECS FG

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#933]
Implement [OPTECS FG](https://www.st.nmfs.noaa.gov/jira/secure/RapidBoard.jspa?rapidView=44&view=planning.nodetail&quickFilter=1154&quickFilter=578&issueLimit=100) to include:

- [x] [FIELD-1930](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1930)
- [x] [FIELD-1931](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1931)
- [x] [FIELD-1857](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1857) (like set)
- de-scoped [FIELD-1886](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1886) (more like set)
- de-scoped [FIELD-1900](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1900) (auto-weight like set)
- [x] [FIELD-1898](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1898)
- [x] [FIELD-1891](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1891) (warning on bio list)
- [x] [FIELD-1839](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1839) (species calc rounding)
- [x] [FIELD-1905](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1905) (icon)

- [x] [FIELD-1959](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1964)DR already in use after nav away to add cal requirement.
- [x] [FIELD-1964](https://www.st.nmfs.noaa.gov/jira/browse/FIELD-1964)Weights not initially updating correctly

- [x] 20-ish other new tickets (too numerous to keep updating this ticket.)

**Comment by wsmith-nwfsc** [comment]
release candidate build Monday morning, expecting a few straggling must-fix bugs as they do final testing, but switching to no-new-features.
