### ISSUE TITLE
Create OLE Mockups

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#934]

**Comment by SaOgaz-NOAA** [comment]
First pass at this is almost done.  One more quick review on them with Seth before Thursday's meeting. They are stored in our balsamiq cloud. We should probably make a new ticket for the next iteration/batch of mockups, so post meeting with Seth I will close this issue.

**Comment by SaOgaz-NOAA** [comment]
First round of mock-ups done! This encompasses the "captain / new declaration" side of the app.  The other two pieces being the OLE user specific screens, and the incident reporting screens.
