### ISSUE TITLE
Revise Debriefer Mockups

### ISSUE THREAD

**Issue by melinashak-noaa** [nwfsc-fram/boatnet#939]
https://docs.google.com/document/d/10TcFfWZ49O96NKLa9FcBF5lwG0rlN8wbIKU4-V7X_I0/edit#

- [x] Filters - A-SHOP needs to be able to identify more than 1 observer/deployment and review their data at the same time
- [ ] Filters - Add Mode Toggle buttons (In-Season v. Debriefing) - The Debriefing is what we're currently showing.  The In-Season should allow for an ad-hoc selection of trips of interest for review.
- [x] Summary Tab - Enable filtering by Trip
- [x] QA/QC Tab - Sub-tab items - Add Open Error count in parentheses after the title, i.e. Trips (3), Hauls (13), etc.
- [x] QA/QC Tab - Vertically stack the Errors + Data tables
- [x] QA/QC Tab - Add Error Popup button that would pop the Errors Table to a separate window, but highlighting an error would still highlight the relevant data back in the Data Table
- [ ] QA/QC Tab - Add Feedback button that once clicked, opens a separate window for capturing the Feedback in a table.  Table columns include Trip #, Hauls, Haul #, Issue, Error Code (if applicable), Notes
- [ ] QA/QC Tab / Errors Table - Right mouse click, send to Feedback form capability
- [x] QA/QC Tab / Errors Table - Add Error Type column (3 possible values Warning, Error, Data Processing)
- [x] QA/QC Tab / Errors Table - Add Status column (3 possible values - Open, Closed, Override)
- [x] QA/QC Tab / Errors Table - Add Filter toggle buttons for Error Types (show the 3 buttons)
- [x] QA/QC Tab / Errors Table - Add Filter toggle buttons for Status (show the 3 buttons)

**Comment by toddhay-NOAA** [comment]
FYI, the existing WCGOP data checksheet is here:  https://drive.google.com/file/d/0B-J04uwRx-2IajdSSW90dUJDMDA/view?usp=sharing

**Comment by toddhay-NOAA** [comment]
@melinashak-noaa, the mockups are looking really good.  A couple of items of immediate feedback:

- Data Check Sheet - Change this to be the Feedback button that is discussed in the description section of this ticket.  I.e. rename the button to be Feedback and similarly rename the popup form Feedback as well.

- Remove the QA/QC accordions - Keep the Errors + Data tables, but remove the accordion widget as the debriefers already indicated that they always want to see both the Errors and Data tables at the same time

- Cascade Filtering Toggle Button - Add a cascading filtering toggle button that, once selected, will copy the filtering from the higher levels (i.e. a Trips tab filter in place will be copied down to the Hauls, Catch, etc. tabs) to the lower tab levels.  When unselected, each tab's filtering works independently.
