### ISSUE TITLE
Enable A-SHOP app for PWA

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#945]
In reviewing the app with the A-SHOP team today, we realized that it is not currently PWA-enabled where it can be downloaded.  Please correct.

**Comment by toddhay-NOAA** [comment]
FYI @wsmith-nwfsc, @sethgerou-noaa - please assist Melina in doing this as needed.

**Comment by wsmith-nwfsc** [comment]
PWA is enabled by default, but only when built (webpack and minimized) and deployed to a HTTPS endpoint.
