### ISSUE TITLE
Full Vuese test on two Vue/ts files

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#958]
I will do one test of a old style Vue class components file, and one test of the new composition files that Melina worked on.

**Comment by wsmith-nwfsc** [comment]
I'm emplumpening an existing Vue file with comments for Sara to vuese-ify as an example.

**Comment by SaOgaz-NOAA** [comment]
To see progress on this: PR #965

**Comment by SaOgaz-NOAA** [comment]
Closing this ticket as I'm "done", but we definitely need to discuss this as a group.
