### ISSUE TITLE
Show sample trips + haul + catch data for debriefing module

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#969]

**Comment by toddhay-NOAA** [comment]
just preselect 5 or 10 trips for this for right now, so we can showcase how the filtering and tabs will work at the next meeting.

**Comment by melinashak-noaa** [comment]
There key was changed in the operations view preventing the documents from loading in the hauls, catch, catch species page ect. To resolve this modified the query to no longer use the view. Instead, just fetch from couch using the keys we are interested in.

**Comment by toddhay-NOAA** [comment]
@melinashak-noaa, for the upcoming meeting, please be sure to have the following primevue datatable features in place for this:

- [ ] column-level filtering (which I think you already have)
- [ ] column sorting
- [ ] inline editing (but don't worry about it actually writing back to something right now)

**Comment by melinashak-noaa** [comment]
This is mostly done, got the editing and resizing working, still need to push those changes into production. For some reason doesn't seem like I can have filtering and editing don't seem to work so looking into how to resolve this issue and get them both working at once.

**Comment by melinashak-noaa** [comment]
Completed with https://github.com/nwfsc-fram/boatnet/commit/cee6edd0fa8003a720fa09722673104eb858a33f
