### ISSUE TITLE
One Touch account setup

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#971]
We need to figure out the workflow for users making new accounts, getting hooked up to vessels, etc.

- [x] Sara to create permissions matrix to get started. 
- [ ] Resolve how shared trip data would work pouch and couch. If we only allow online-only, or have other rules (policy) this is simpler.

Existing roles from boatnet: see models/lookups/person.ts (in @boatnet/bn-models)

**Comment by SaOgaz-NOAA** [comment]
@sethgerou-noaa any idea what kind of "due date" we should stick onto this ticket?  Obviously something we need for OX as well, so not sure what that timeline is.

**Comment by sethgerou-noaa** [comment]
I think you, Will, Melina, and I should meet about this in the next couple weeks and decide what's reasonable.  I'm not thinking streamlined account creation is part of MVP for OTS, so there's no real time pressure, but it would be good to keep the ball rolling on the requirement.

**Comment by wsmith-nwfsc** [comment]
Currently we create accounts for non-NOAA people in our Apex User Admin (AUA) tool, which our auth service talks to. This is what the bn-auth module talks to, so we could just use this. We would create an APPLICATION_NAME in AUA and these users would go there, if that makes sense.
The auth service has routines for user creation, updates etc (via OpenAPI)

**Comment by wsmith-nwfsc** [comment]
This will probably tie into the Communications Module (which will handle SMS texts, emails, etc)

**Comment by wsmith-nwfsc** [comment]
We have the start of a roles/ permissions matrix somewhere. @SaOgaz-NOAA requests it.

**Comment by SaOgaz-NOAA** [comment]
Opened new ticket for next step here. However, before close this I want to clarify the expectation for OLE.

New users (captains) will be able to create an account for themselves, but it will not be associated with any vessels.  How the vessels are then attached to user accounts is a bit of a TBD, since we first need to figure out how we're handling vessels from an OLE perspective.

Does that sound right @sethgerou-noaa, @wsmith-nwfsc ?

**Comment by wsmith-nwfsc** [comment]
Yes, we expect a data steward/admin to perform that -- perhaps the captain will "request" a vessel association, to make that process a one-click move

**Comment by sethgerou-noaa** [comment]
I'd propose the captain can request a vessel association by entering a vessel ID (coast guard # or state reg #) and then a staff member approves/not

**Comment by SaOgaz-NOAA** [comment]
Okay, closing this ticket and opening new one.
