### ISSUE TITLE
Data Model additions for OLE

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#972]
We need to figure out how the OLE data is going to fit into the current boatnet data model.

**Comment by SaOgaz-NOAA** [comment]
Side node: make sure vessel pass codes is incorporated into that data model

**Comment by SaOgaz-NOAA** [comment]
We met and sort of came up with a plan for the OLE data and how it would be stored in couch, but, after some post meeting discussion with @wsmith-nwfsc, he felt that we should keep the idea of having a separate OLEVessel document so that the OLE records are kept separately from other observer data.  This will particularly help us not be sharing additional vessel data when it's not necessary, and vice versa.

The OLEVessel document would extend Vessel (which will really be BaseVessel eventually) and add in a declaration id number, and a set of active declarations and closed declarations.

I'm fine with this, thoughts @sethgerou-noaa?

**Comment by BHHorness-NOAA** [comment]
This is still open, questions have been delineated in a new ticket
