### ISSUE TITLE
refactor organization and naming of views

### ISSUE THREAD

**Issue by NickShafferNOAA** [nwfsc-fram/boatnet#979]

**Comment by BHHorness-NOAA** [comment]
Nick will schedule a meeting to demo and solicit input.  Full team

**Comment by NickShafferNOAA** [comment]
I have preliminary idea/design. Need feedback/discussion. Moving this to the next milestone.

**Comment by wsmith-nwfsc** [comment]
#1059 for dumping + restore of design docs
- [ ] (Create an issue for this) - utility to allow us to use github for source control and push updates to couchdb from the command line, or similar approach

**Comment by NickShafferNOAA** [comment]
Closing this. It seems we've reaches a conclusion as to how to organize our views. Created a separate ticket to track implementation of this and source code. 

Notes from meeting: 

 - Combine "docs"/lookups design doc idea into just "docs".
 - Design documents are application/software driven. One per fishery/survey program + one for each individual application that queries couch. (+ oddity "utility" type docs. e.g., protocols, taxonomy).
 - Naming style of design docs and views will follow what we've been using for github files,all lowercase separated by a dash: "-" 
 - Create single design doc / view that will map/reduce a distinct list of all doc types to replace as many existing views as possible.
